import { MaterialIcons } from "@expo/vector-icons";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { HOBEE } from "@/components/hobee/design-tokens";

export function BackHeader({ title, subtitle, onBack, right }: { title: string; subtitle?: string; onBack: () => void; right?: React.ReactNode }) {
  return <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="ย้อนกลับ" onPress={onBack} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><View style={styles.headerCopy}><Text style={styles.headerTitle}>{title}</Text>{subtitle ? <Text numberOfLines={1} style={styles.headerSubtitle}>{subtitle}</Text> : null}</View>{right ?? <View style={styles.headerRightPlaceholder} />}</View>;
}

export function PriceBlock({ price, compareAt, label }: { price: string; compareAt?: string; label?: string }) {
  return <View>{label ? <Text style={styles.priceLabel}>{label}</Text> : null}<View style={styles.priceRow}><Text style={styles.price}>{price}</Text>{compareAt ? <Text style={styles.compare}>{compareAt}</Text> : null}</View></View>;
}

export function RatingBlock({ rating, count }: { rating: number; count: number }) { return <View style={styles.rating}><MaterialIcons name="star" size={17} color={HOBEE.colors.goldDark} /><Text style={styles.ratingText}>{rating.toFixed(1)}</Text><Text style={styles.ratingCount}>({count})</Text></View>; }

export function InfoRow({ icon, label, value, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; label: string; value: string; onPress?: () => void }) { const body = <><View style={styles.infoIcon}><MaterialIcons name={icon} size={20} color={HOBEE.colors.botanical} /></View><View style={styles.infoCopy}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>{onPress ? <MaterialIcons name="chevron-right" size={23} color={HOBEE.colors.muted} /> : null}</>; return onPress ? <Pressable onPress={onPress} style={({ pressed }) => [styles.infoRow, pressed && styles.pressed]}>{body}</Pressable> : <View style={styles.infoRow}>{body}</View>; }

export function SummaryRow({ label, value, emphasis = false, muted = false }: { label: string; value: string; emphasis?: boolean; muted?: boolean }) { return <View style={styles.summaryRow}><Text style={[styles.summaryLabel, muted && styles.summaryMuted]}>{label}</Text><Text style={[styles.summaryValue, emphasis && styles.summaryEmphasis, muted && styles.summaryMuted]}>{value}</Text></View>; }

const STATUS: Record<string, { background: string; color: string; label: string }> = {
  pending: { background: "#FFF1C8", color: "#8B6617", label: "รอดำเนินการ" },
  awaiting_payment: { background: "#FFF1C8", color: "#8B6617", label: "รอชำระเงิน" },
  paid: { background: "#DEF5E9", color: "#167457", label: "ชำระแล้ว" },
  processing: { background: "#E6EFFF", color: "#366BB9", label: "กำลังเตรียมสินค้า" },
  shipped: { background: "#E6EFFF", color: "#366BB9", label: "จัดส่งแล้ว" },
  delivered: { background: "#DEF5E9", color: "#167457", label: "ส่งสำเร็จ" },
  cancelled: { background: "#FFE8E4", color: "#B65045", label: "ยกเลิกแล้ว" },
  refunded: { background: "#F0E8FF", color: "#7652AA", label: "คืนเงินแล้ว" },
};

export function StatusChip({ status, label }: { status: string; label?: string }) { const token = STATUS[status] ?? STATUS.pending; return <View style={[styles.status, { backgroundColor: token.background }]}><Text style={[styles.statusText, { color: token.color }]}>{label ?? token.label}</Text></View>; }

export function OrderTimeline({ steps }: { steps: { label: string; value: string; active: boolean; last?: boolean }[] }) { return <View style={styles.timelineCard}>{steps.map((step) => <View key={step.label} style={styles.timelineRow}><View style={styles.timelineRail}><View style={[styles.timelineDot, step.active && styles.timelineDotActive]}><MaterialIcons name={step.active ? "check" : "circle"} size={11} color="#FFFFFF" /></View>{!step.last ? <View style={[styles.timelineLine, step.active && styles.timelineLineActive]} /> : null}</View><View style={styles.timelineCopy}><Text style={styles.timelineLabel}>{step.label}</Text><Text style={styles.timelineValue}>{step.value}</Text></View></View>)}</View>; }

export function StickyBottomCTA({ primaryLabel, onPrimary, primaryDisabled, secondaryLabel, onSecondary, context }: { primaryLabel: string; onPrimary: () => void; primaryDisabled?: boolean; secondaryLabel?: string; onSecondary?: () => void; context?: React.ReactNode }) { const insets = useSafeAreaInsets(); return <View style={[styles.sticky, { paddingBottom: Math.max(insets.bottom, 12) }]}>{context ? <View style={styles.stickyContext}>{context}</View> : null}<View style={styles.stickyActions}>{secondaryLabel && onSecondary ? <Pressable onPress={onSecondary} style={({ pressed }) => [styles.secondary, pressed && styles.pressed]}><Text style={styles.secondaryText}>{secondaryLabel}</Text></Pressable> : null}<Pressable disabled={primaryDisabled} onPress={onPrimary} style={({ pressed }) => [styles.primary, primaryDisabled && styles.primaryDisabled, pressed && !primaryDisabled && styles.pressed]}><Text style={styles.primaryText}>{primaryLabel}</Text><MaterialIcons name="arrow-forward" size={20} color={HOBEE.colors.ink} /></Pressable></View></View>; }

export function AccountQuickAction({ icon, title, description, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; description: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.quick, pressed && styles.pressed]}><View style={styles.quickIcon}><MaterialIcons name={icon} size={23} color={HOBEE.colors.botanical} /></View><Text numberOfLines={1} style={styles.quickTitle}>{title}</Text><Text numberOfLines={1} style={styles.quickDescription}>{description}</Text></Pressable>; }

export function ProfileHeader({ name, detail, actionLabel, onAction }: { name: string; detail: string; actionLabel: string; onAction: () => void }) { return <View style={styles.profileCard}><View style={styles.avatar}><MaterialIcons name="person" size={34} color="#FFFFFF" /></View><View style={styles.profileCopy}><Text style={styles.profileName}>{name}</Text><Text numberOfLines={1} style={styles.profileDetail}>{detail}</Text></View><Pressable onPress={onAction} style={({ pressed }) => [styles.profileAction, pressed && styles.pressed]}><Text style={styles.profileActionText}>{actionLabel}</Text></Pressable></View>; }

export function PointsCard({ points }: { points: number }) { return <View style={styles.points}><Text style={styles.pointsLabel}>คะแนนสะสมของคุณ</Text><Text style={styles.pointsValue}>{points.toLocaleString("th-TH")}</Text><Text style={styles.pointsDetail}>คะแนนจะสะสมเมื่อคำสั่งซื้อได้รับการยืนยัน</Text></View>; }

const styles = StyleSheet.create({
  header: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 18 }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface }, headerCopy: { flex: 1 }, headerTitle: { color: HOBEE.colors.ink, fontSize: 23, fontWeight: "900" }, headerSubtitle: { marginTop: 2, color: HOBEE.colors.muted, fontSize: 13, fontWeight: "600" }, headerRightPlaceholder: { width: 42 },
  priceLabel: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "700" }, priceRow: { flexDirection: "row", alignItems: "baseline", gap: 8 }, price: { marginTop: 3, color: HOBEE.colors.ink, fontSize: 27, fontWeight: "900" }, compare: { color: HOBEE.colors.muted, fontSize: 14, fontWeight: "600", textDecorationLine: "line-through" }, rating: { flexDirection: "row", alignItems: "center", gap: 3 }, ratingText: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" }, ratingCount: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600" },
  infoRow: { flexDirection: "row", alignItems: "center", gap: 12, minHeight: 66, borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border, paddingVertical: 9 }, infoIcon: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#E2F7EE" }, infoCopy: { flex: 1 }, infoLabel: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "700" }, infoValue: { marginTop: 2, color: HOBEE.colors.ink, fontSize: 14, fontWeight: "800" },
  summaryRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 10 }, summaryLabel: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "700" }, summaryValue: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "800" }, summaryEmphasis: { fontSize: 21, fontWeight: "900" }, summaryMuted: { color: HOBEE.colors.muted },
  status: { alignSelf: "flex-start", borderRadius: 14, paddingHorizontal: 10, paddingVertical: 6 }, statusText: { fontSize: 11, fontWeight: "900" },
  timelineCard: { borderRadius: 23, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 15 }, timelineRow: { flexDirection: "row", minHeight: 60 }, timelineRail: { width: 26, alignItems: "center" }, timelineDot: { width: 20, height: 20, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: "#D9D5CF" }, timelineDotActive: { backgroundColor: HOBEE.colors.botanical }, timelineLine: { width: 2, flex: 1, marginVertical: 2, backgroundColor: "#E4E0DA" }, timelineLineActive: { backgroundColor: "#9BD9C6" }, timelineCopy: { flex: 1, paddingBottom: 10 }, timelineLabel: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" }, timelineValue: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 13, fontWeight: "600" },
  sticky: { borderTopWidth: 1, borderTopColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 20, paddingTop: 10 }, stickyContext: { marginBottom: 9 }, stickyActions: { flexDirection: "row", gap: 10 }, primary: { height: 52, flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 18, backgroundColor: HOBEE.colors.gold }, primaryDisabled: { opacity: 0.45 }, primaryText: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, secondary: { height: 52, alignItems: "center", justifyContent: "center", borderRadius: 18, borderWidth: 1, borderColor: HOBEE.colors.gold, paddingHorizontal: 16 }, secondaryText: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" },
  quick: { width: "48%", minHeight: 126, borderRadius: 22, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 14, ...HOBEE.shadow }, quickIcon: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#E2F7EE" }, quickTitle: { marginTop: 11, color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900" }, quickDescription: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600" },
  profileCard: { flexDirection: "row", alignItems: "center", gap: 12, borderRadius: 24, backgroundColor: HOBEE.colors.nav, padding: 17 }, avatar: { width: 56, height: 56, alignItems: "center", justifyContent: "center", borderRadius: 28, backgroundColor: HOBEE.colors.gold }, profileCopy: { flex: 1 }, profileName: { color: "#FFFFFF", fontSize: 19, fontWeight: "900" }, profileDetail: { marginTop: 3, color: "#D8D4CF", fontSize: 12, fontWeight: "600" }, profileAction: { borderRadius: 15, backgroundColor: "#FFFFFF", paddingHorizontal: 11, paddingVertical: 9 }, profileActionText: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "900" }, points: { borderRadius: 24, backgroundColor: HOBEE.colors.nav, padding: 20 }, pointsLabel: { color: "#D8D4CF", fontSize: 13, fontWeight: "700" }, pointsValue: { marginTop: 5, color: "#FFFFFF", fontSize: 38, fontWeight: "900" }, pointsDetail: { marginTop: 7, color: "#D8D4CF", fontSize: 12, fontWeight: "600" },
  pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] },
});
