import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import type { CommunityRecommendation } from "@/lib/community-hub";
import type { CommunityClub } from "@/lib/community-hub";
import type { CommunityActivity } from "@/lib/community-hub";

const TONE: Record<CommunityRecommendation["entityType"], string> = { STORY: HOBEE.atmosphere.skyMist, CLUB: HOBEE.atmosphere.botanicalMist, ACTIVITY: HOBEE.atmosphere.peachMist, JOB: HOBEE.atmosphere.warmCream, TRIP: "#E9F1F7", CREATOR: "#F2EAF8", ANNOUNCEMENT: "#F5F0E7", STORE: "#E8F5F0", RESTAURANT: "#FCEDE4", DESTINATION: "#EAF1FA", COURSE: "#F1ECFF", EVENT: "#FEF3D5" };
const ICON: Record<CommunityRecommendation["entityType"], keyof typeof MaterialIcons.glyphMap> = { STORY: "article", CLUB: "groups", ACTIVITY: "event", JOB: "work-outline", TRIP: "luggage", CREATOR: "person", ANNOUNCEMENT: "campaign", STORE: "storefront", RESTAURANT: "restaurant", DESTINATION: "place", COURSE: "school", EVENT: "event-available" };

export function CommunityRecommendationCard({ item, onPress }: { item: CommunityRecommendation; onPress: () => void }) {
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><Image source={{ uri: item.image }} style={styles.image} resizeMode="cover" /><View style={styles.body}><View style={[styles.badge, { backgroundColor: TONE[item.entityType] }]}><MaterialIcons name={ICON[item.entityType]} size={13} color={HOBEE.colors.botanical} /><Text style={styles.badgeText}>{item.badge}</Text></View><Text numberOfLines={2} style={styles.title}>{item.title}</Text><Text numberOfLines={2} style={styles.subtitle}>{item.subtitle}</Text><View style={styles.footer}><MaterialIcons name="location-on" size={14} color={HOBEE.colors.goldDark} /><Text style={styles.province}>{item.province === "other" ? "จังหวัดอื่น" : item.province}</Text><MaterialIcons name="arrow-forward" size={17} color={HOBEE.colors.ink} /></View></View></Pressable>;
}

export function CommunityClubCard({ club, onPress }: { club: CommunityClub; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.club, pressed && styles.pressed]}><Image source={{ uri: club.image }} style={styles.clubImage} /><View style={styles.clubBody}><View style={styles.clubBadge}><MaterialIcons name={club.icon as keyof typeof MaterialIcons.glyphMap} size={14} color={HOBEE.colors.botanical} /><Text style={styles.clubBadgeText}>{club.category}</Text></View><Text numberOfLines={1} style={styles.clubTitle}>{club.name}</Text><Text numberOfLines={2} style={styles.clubDescription}>{club.description}</Text><View style={styles.clubFooter}><Text style={styles.clubState}>{club.membershipState === "joined" ? "เข้าร่วมแล้ว" : club.membershipState === "pending" ? "รออนุมัติ" : club.private ? "ชมรมส่วนตัว" : "เข้าร่วมได้"}</Text><MaterialIcons name="chevron-right" size={19} color={HOBEE.colors.ink} /></View></View></Pressable>; }

export function CommunityActivityCard({ activity, onPress }: { activity: CommunityActivity; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.activity, pressed && styles.pressed]}><Image source={{ uri: activity.image }} style={styles.activityImage} /><View style={styles.activityBody}><Text style={styles.activityDate}>{activity.startsAt.slice(0, 10)}</Text><Text numberOfLines={2} style={styles.activityTitle}>{activity.title}</Text><Text numberOfLines={1} style={styles.activityMeta}>{activity.location} · {activity.category}</Text><View style={styles.activityFooter}><Text style={styles.activityCapacity}>{activity.joinState === "joined" ? "เข้าร่วมแล้ว" : activity.joinState === "waitlist" ? "อยู่ในคิว" : "ดูรายละเอียด"}</Text><MaterialIcons name="chevron-right" size={19} color={HOBEE.colors.ink} /></View></View></Pressable>; }

const styles = StyleSheet.create({ card: { overflow: "hidden", borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.colors.surface, marginBottom: 13, ...HOBEE.elevation.card }, image: { width: "100%", height: 168, backgroundColor: HOBEE.atmosphere.warmCream }, body: { gap: 8, padding: 14 }, badge: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 5, borderRadius: HOBEE.radius.pill, paddingHorizontal: 9, paddingVertical: 5 }, badgeText: { color: HOBEE.colors.botanical, fontSize: 10, fontWeight: "900" }, title: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900", lineHeight: 22 }, subtitle: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 17 }, footer: { flexDirection: "row", alignItems: "center", gap: 5, borderTopWidth: 1, borderTopColor: HOBEE.colors.border, marginTop: 2, paddingTop: 10 }, province: { flex: 1, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700", textTransform: "capitalize" }, club: { overflow: "hidden", borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.colors.surface, marginBottom: 13, ...HOBEE.elevation.card }, clubImage: { width: "100%", height: 138, backgroundColor: HOBEE.atmosphere.botanicalMist }, clubBody: { gap: 7, padding: 13 }, clubBadge: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 5, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.atmosphere.botanicalMist, paddingHorizontal: 8, paddingVertical: 5 }, clubBadgeText: { color: HOBEE.colors.botanical, fontSize: 10, fontWeight: "900" }, clubTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, clubDescription: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 17 }, clubFooter: { flexDirection: "row", alignItems: "center", borderTopWidth: 1, borderTopColor: HOBEE.colors.border, marginTop: 3, paddingTop: 10 }, clubState: { flex: 1, color: HOBEE.colors.goldDark, fontSize: 11, fontWeight: "900" }, activity: { overflow: "hidden", borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.colors.surface, marginBottom: 13, ...HOBEE.elevation.card }, activityImage: { width: "100%", height: 142, backgroundColor: HOBEE.atmosphere.skyMist }, activityBody: { gap: 7, padding: 13 }, activityDate: { color: HOBEE.colors.goldDark, fontSize: 10, fontWeight: "900" }, activityTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900", lineHeight: 22 }, activityMeta: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700" }, activityFooter: { flexDirection: "row", alignItems: "center", borderTopWidth: 1, borderTopColor: HOBEE.colors.border, marginTop: 3, paddingTop: 10 }, activityCapacity: { flex: 1, color: HOBEE.colors.botanical, fontSize: 11, fontWeight: "900" }, pressed: { opacity: 0.8, transform: [{ scale: HOBEE.motion.cardPressScale }] } });
