import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { AppStatusState } from "@/components/hobee/error-screens";
import { ScreenContainer } from "@/components/screen-container";
import { LEARNING_CATEGORIES, getCourseMetadata, searchLearning, type LearningAccessType } from "@/lib/learning-platform";

type BrowseMode = "search" | "catalogue" | "category";
type StateMode = "ready" | "loading" | "error" | "offline";
type AccessFilter = "all" | LearningAccessType;

export function LearningBrowseScreen({ mode }: { mode: BrowseMode }) {
  const params = useLocalSearchParams<{ q?: string; category?: string; id?: string; state?: StateMode }>();
  const initialCategory = mode === "category" ? params.id : params.category;
  const [query, setQuery] = useState(params.q ?? ""); const [category, setCategory] = useState(initialCategory ?? "all"); const [access, setAccess] = useState<AccessFilter>("all"); const [stateMode] = useState<StateMode>(params.state ?? "ready");
  const courses = useMemo(() => searchLearning(query).filter((course) => { const metadata = getCourseMetadata(course.id); const categoryMatch = category === "all" || metadata?.tags.includes(category as never) || course.category.toLowerCase().includes(category.toLowerCase()); const accessMatch = access === "all" || metadata?.accessType === access; return categoryMatch && accessMatch; }), [query, category, access]);
  const title = mode === "search" ? "ค้นหาการเรียนรู้" : mode === "category" ? LEARNING_CATEGORIES.find((item) => item.id === category)?.label ?? "Learning Category" : "คอร์สทั้งหมด";
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#0C0D0D]" safeAreaClassName="bg-[#0C0D0D]"><View style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.canGoBack() ? router.back() : router.replace("/learn")} style={({ pressed }) => [styles.iconButton, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={23} color="#F5F2EC" /></Pressable><Text numberOfLines={1} style={styles.title}>{title}</Text><Pressable onPress={() => router.push("/learning/my-learning" as never)} style={({ pressed }) => [styles.iconButton, pressed && styles.pressed]}><MaterialIcons name="menu-book" size={21} color="#F5F2EC" /></Pressable></View>
    {stateMode !== "ready" ? <BrowseState state={stateMode} /> : <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.searchWrap}><MaterialIcons name="search" size={21} color="#B4B1AA" /><TextInput value={query} onChangeText={setQuery} placeholder="ค้นหาคอร์ส ผู้สอน หรือหัวข้อ" placeholderTextColor="#8C8A85" autoFocus={mode === "search"} returnKeyType="search" style={styles.searchInput} /><Pressable onPress={() => setQuery("")}><MaterialIcons name="close" size={19} color="#B4B1AA" /></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterRail}><Filter label="ทั้งหมด" active={category === "all"} onPress={() => setCategory("all")} />{LEARNING_CATEGORIES.map((item) => <Filter key={item.id} label={item.label} active={category === item.id} onPress={() => setCategory(item.id)} />)}</ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterRail}><Filter label="ทุกสิทธิ์" active={access === "all"} onPress={() => setAccess("all")} /><Filter label="ฟรี" active={access === "free"} onPress={() => setAccess("free")} /><Filter label="ซื้อคอร์ส" active={access === "paid"} onPress={() => setAccess("paid")} /><Filter label="สมาชิก" active={access === "subscription"} onPress={() => setAccess("subscription")} /></ScrollView><View style={styles.resultRow}><Text style={styles.resultText}>{courses.length} คอร์สใน catalogue แบบ presentation</Text><MaterialIcons name="tune" size={18} color="#DDB94F" /></View>{courses.length ? <View style={styles.grid}>{courses.map((course) => { const metadata = getCourseMetadata(course.id); return <Pressable key={course.id} onPress={() => router.push({ pathname: "/learning/[id]", params: { id: course.id } } as never)} style={({ pressed }) => [styles.courseCard, pressed && styles.pressed]}><Image source={course.image} style={styles.courseImage} /><View style={styles.courseBody}><Text numberOfLines={2} style={styles.courseTitle}>{course.title}</Text><Text numberOfLines={1} style={styles.courseMeta}>{course.instructor}</Text><View style={styles.accessBadge}><Text style={styles.accessText}>{metadata?.accessType === "free" ? "เรียนฟรี" : metadata?.accessType === "subscription" ? "สำหรับสมาชิก" : metadata?.accessType === "paid" ? "คอร์สเชิงลึก" : "Learning"}</Text></View></View></Pressable>; })}</View> : <View style={styles.empty}><MaterialIcons name="search-off" size={32} color="#E1B949" /><Text style={styles.emptyTitle}>ไม่พบคอร์สที่ตรงกับเงื่อนไข</Text><Text style={styles.emptyText}>ลองเปลี่ยนคำค้นหา หมวด หรือสิทธิ์เข้าถึง</Text><Pressable onPress={() => { setQuery(""); setCategory("all"); setAccess("all"); }} style={styles.reset}><Text style={styles.resetText}>ล้างตัวกรอง</Text></Pressable></View>}</ScrollView>}</View></ScreenContainer>;
}

function Filter({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.filter, active && styles.filterActive, pressed && styles.pressed]}><Text style={[styles.filterText, active && styles.filterTextActive]}>{label}</Text></Pressable>; }
function BrowseState({ state }: { state: StateMode }) { if (state === "loading") return <View style={styles.state}><ActivityIndicator color="#E0B747" /><Text style={styles.loadingText}>กำลังเตรียม catalogue การเรียนรู้</Text></View>; if (state === "offline") return <View style={styles.state}><AppStatusState icon="wifi-off" tone="blue" title="คุณกำลังออฟไลน์" description="Catalogue ที่เชื่อมข้อมูลจริงจะกลับมาเมื่อเชื่อมต่ออินเทอร์เน็ต" actionLabel="กลับ Learning" onAction={() => router.replace("/learn")} /></View>; return <View style={styles.state}><AppStatusState icon="error-outline" tone="rose" title="โหลด Learning catalogue ไม่สำเร็จ" description="ลองกลับไปหน้า Learning หรือเปิดใหม่อีกครั้ง" actionLabel="กลับ Learning" onAction={() => router.replace("/learn")} /></View>; }

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#0C0D0D" }, header: { height: 60, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 15, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#2A2B2A" }, iconButton: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#181A19" }, title: { maxWidth: "64%", color: "#F6F3EC", fontSize: 16, fontWeight: "900" }, content: { paddingBottom: 36 }, searchWrap: { flexDirection: "row", alignItems: "center", gap: 9, margin: 18, borderRadius: 14, borderWidth: 1, borderColor: "#3A3B38", backgroundColor: "#181A19", paddingHorizontal: 12, paddingVertical: 11 }, searchInput: { flex: 1, color: "#F5F2EC", fontSize: 13, fontWeight: "700" }, filterRail: { gap: 8, paddingHorizontal: 18, paddingBottom: 10 }, filter: { borderRadius: 16, borderWidth: 1, borderColor: "#383A37", backgroundColor: "#171918", paddingHorizontal: 12, paddingVertical: 8 }, filterActive: { borderColor: "#DDB94B", backgroundColor: "#2A261A" }, filterText: { color: "#AAA7A1", fontSize: 10, fontWeight: "900" }, filterTextActive: { color: "#F0CC63" }, resultRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 18, paddingVertical: 10 }, resultText: { color: "#A8A59E", fontSize: 10, fontWeight: "700" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 10, paddingHorizontal: 18 }, courseCard: { width: "48.3%", overflow: "hidden", borderRadius: 14, borderWidth: 1, borderColor: "#30312F", backgroundColor: "#171918" }, courseImage: { width: "100%", height: 105, backgroundColor: "#282926" }, courseBody: { padding: 10 }, courseTitle: { color: "#F2F0E9", fontSize: 12, fontWeight: "900", lineHeight: 16 }, courseMeta: { color: "#9E9B95", fontSize: 10, fontWeight: "600", marginTop: 5 }, accessBadge: { alignSelf: "flex-start", borderRadius: 7, backgroundColor: "#2B281B", marginTop: 8, paddingHorizontal: 6, paddingVertical: 4 }, accessText: { color: "#E4BF53", fontSize: 8, fontWeight: "900" }, empty: { alignItems: "center", gap: 9, paddingHorizontal: 32, paddingTop: 72 }, emptyTitle: { color: "#F3F0E9", fontSize: 16, fontWeight: "900", textAlign: "center" }, emptyText: { color: "#A6A39C", fontSize: 11, fontWeight: "600", lineHeight: 17, textAlign: "center" }, reset: { borderRadius: 10, backgroundColor: "#DDB94B", marginTop: 4, paddingHorizontal: 14, paddingVertical: 10 }, resetText: { color: "#1A1710", fontSize: 11, fontWeight: "900" }, state: { flex: 1, alignItems: "center", justifyContent: "center" }, loadingText: { color: "#C7C4BC", fontSize: 12, fontWeight: "800", marginTop: 12 }, pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] } });
