import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import * as Haptics from "expo-haptics";
import { type ReactNode, useCallback, useEffect, useRef, useState } from "react";
import { Animated, Image, NativeScrollEvent, NativeSyntheticEvent, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useCart } from "@/contexts/cart-context";
import { formatThaiBaht, type HobeeProduct } from "@/lib/hobee-data";
import { HOBEE } from "@/components/hobee/design-tokens";

const AVATAR = "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=85&w=300";

export function LocationPill({ compact = false }: { compact?: boolean } = {}) { return <Pressable onPress={() => router.push("/(tabs)/discover")} style={({ pressed }) => [styles.location, compact && styles.locationCompact, pressed && styles.pressed]}><MaterialIcons name="location-on" size={17} color={HOBEE.colors.goldDark} /><Text numberOfLines={1} style={[styles.locationText, compact && styles.locationTextCompact]}>เชียงใหม่</Text><MaterialIcons name="keyboard-arrow-down" size={17} color="#9A958E" /></Pressable>; }

export function AppHeader({ showLocation = true, brandSuffix }: { showLocation?: boolean; brandSuffix?: string } = {}) {
  const { itemCount } = useCart();
  const travelHeader = Boolean(brandSuffix);
  return <View style={[styles.header, travelHeader && styles.headerCompact]}><Pressable onPress={() => router.replace("/(tabs)")} style={({ pressed }) => [styles.brand, travelHeader && styles.brandCompact, pressed && styles.pressed]}><View style={[styles.mark, travelHeader && styles.markCompact, { backgroundColor: HOBEE.colors.darkCard, borderColor: HOBEE.colors.goldDark }]}><Text style={styles.markText}>H</Text></View><Text numberOfLines={1} style={[styles.wordmark, travelHeader && styles.wordmarkCompact]}>HOBEE</Text>{brandSuffix ? <Text numberOfLines={1} style={styles.brandSuffix}>{brandSuffix}</Text> : null}</Pressable>{showLocation ? <LocationPill compact={travelHeader} /> : <View style={styles.headerSpacer} />}<View style={styles.headerActions}><Pressable onPress={() => router.push("/cart")} style={({ pressed }) => [styles.headerIcon, travelHeader && styles.headerIconCompact, pressed && styles.pressed]}><MaterialIcons name="shopping-bag" size={travelHeader ? 25 : 28} color={HOBEE.colors.ink} />{itemCount > 0 ? <View style={styles.badge}><Text style={styles.badgeText}>{itemCount > 9 ? "9+" : itemCount}</Text></View> : null}</Pressable><Pressable onPress={() => router.push("/orders")} style={({ pressed }) => [styles.headerIcon, travelHeader && styles.headerIconCompact, pressed && styles.pressed]}><MaterialIcons name="notifications-none" size={travelHeader ? 27 : 30} color={HOBEE.colors.ink} /></Pressable>{!travelHeader ? <Pressable onPress={() => router.push("/(tabs)/account")} style={({ pressed }) => [styles.avatarButton, pressed && styles.pressed]}><Image source={{ uri: AVATAR }} style={styles.avatar} /></Pressable> : null}</View></View>;
}

export function SearchBar({ value = "", onChangeText, onClear, onPress, placeholder = "ค้นหาทริป สินค้า ร้านค้า หรือบริการ", editable = false, trailingIcon = "keyboard-voice" }: { value?: string; onChangeText?: (value: string) => void; onClear?: () => void; onPress?: () => void; placeholder?: string; editable?: boolean; trailingIcon?: keyof typeof MaterialIcons.glyphMap }) {
  const content = <><MaterialIcons name="search" size={29} color="#9C9993" />{editable ? <TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#ABA6A1" returnKeyType="search" style={styles.searchInput} /> : <Text numberOfLines={1} style={styles.searchPlaceholder}>{placeholder}</Text>}{value && onClear ? <Pressable onPress={onClear} style={styles.clear}><MaterialIcons name="close" size={22} color="#9C9993" /></Pressable> : <MaterialIcons name={trailingIcon} size={27} color="#9C9993" />}</>;
  return onPress && !editable ? <Pressable onPress={onPress} style={({ pressed }) => [styles.search, pressed && styles.pressed]}>{content}</Pressable> : <View style={styles.search}>{content}</View>;
}

export function useHeaderElevation(threshold = 8) {
  const [elevated, setElevated] = useState(false);
  const elevatedRef = useRef(false);
  const onScroll = useCallback((event: NativeSyntheticEvent<NativeScrollEvent>) => {
    const next = event.nativeEvent.contentOffset.y > threshold;
    if (next !== elevatedRef.current) {
      elevatedRef.current = next;
      setElevated(next);
    }
  }, [threshold]);
  return { elevated, onScroll };
}

export function FixedAppShell({ header, search, children, elevated = false }: { header: ReactNode; search: ReactNode; children: ReactNode; elevated?: boolean }) {
  return <View style={styles.appShell}><View style={[styles.fixedTopShell, elevated && styles.fixedTopShellElevated]}>{header}<View style={styles.fixedSearch}>{search}</View></View><View style={styles.scrollRegion}>{children}</View></View>;
}

export function SectionHeader({ title, onPress, actionLabel = "ดูทั้งหมด" }: { title: string; onPress?: () => void; actionLabel?: string }) { return <View style={styles.section}><View style={styles.sectionTitleWrap}><View style={styles.accent} /><Text style={styles.sectionTitle}>{title}</Text></View>{onPress ? <Pressable onPress={onPress} style={({ pressed }) => [styles.action, pressed && styles.pressed]}><Text style={styles.actionText}>{actionLabel}</Text><MaterialIcons name="chevron-right" size={25} color="#77716B" /></Pressable> : null}</View>; }

export function CategoryTile({ label, icon, tone, onPress }: { label: string; icon: keyof typeof MaterialIcons.glyphMap; tone: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.category, pressed && styles.pressed]}><View style={[styles.categoryIcon, { backgroundColor: tone }]}><MaterialIcons name={icon} size={30} color={HOBEE.colors.botanical} /></View><Text numberOfLines={1} style={styles.categoryLabel}>{label}</Text></Pressable>; }

export function ProductCard({ product, favorite, onFavorite, showCommerceMeta = false, onQuickAdd }: { product: HobeeProduct; favorite?: boolean; onFavorite?: () => void; showCommerceMeta?: boolean; onQuickAdd?: () => void }) {
  const [added, setAdded] = useState(false);
  const feedback = useRef(new Animated.Value(0)).current;
  const handleQuickAdd = () => {
    if (!onQuickAdd || product.stock <= 0) return;
    onQuickAdd();
    if (Platform.OS !== "web") void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    setAdded(true);
    feedback.stopAnimation();
    Animated.sequence([
      Animated.timing(feedback, { toValue: 1, duration: 160, useNativeDriver: true }),
      Animated.delay(900),
      Animated.timing(feedback, { toValue: 0, duration: 220, useNativeDriver: true }),
    ]).start(() => setAdded(false));
  };
  const feedbackStyle = { opacity: feedback, transform: [{ translateY: feedback.interpolate({ inputRange: [0, 1], outputRange: [7, 0] }) }, { scale: feedback.interpolate({ inputRange: [0, 1], outputRange: [0.94, 1] }) }] };
  return <Pressable onPress={() => router.push({ pathname: "/product/[id]", params: { id: product.id } })} style={({ pressed }) => [styles.product, pressed && styles.pressed]}><View><Image source={{ uri: product.image }} style={styles.productImage} resizeMode="cover" />{onFavorite ? <Pressable onPress={onFavorite} style={({ pressed }) => [styles.favorite, pressed && styles.favoritePressed]}><MaterialIcons name={favorite ? "favorite" : "favorite-border"} size={21} color={favorite ? HOBEE.colors.error : HOBEE.colors.ink} /></Pressable> : null}</View><View style={[styles.productBody, showCommerceMeta && styles.productBodyCommerce]}>{product.badge ? <View style={styles.productBadge}><Text style={styles.productBadgeText}>{product.badge}</Text></View> : null}<Text numberOfLines={2} style={styles.productTitle}>{product.shortName}</Text>{showCommerceMeta ? <View style={styles.ratingRow}><MaterialIcons name="star" size={15} color={HOBEE.colors.shopOrange} /><Text style={styles.ratingText}>{product.rating.toFixed(1)}</Text><Text style={styles.reviewText}>({product.reviewsCount})</Text></View> : null}<View style={styles.priceRow}><Text style={[styles.price, showCommerceMeta && styles.shopPrice]}>{formatThaiBaht(product.price)}</Text>{product.compareAtPrice ? <Text style={styles.compare}>{formatThaiBaht(product.compareAtPrice)}</Text> : null}{onQuickAdd ? <View style={styles.quickAddWrap}><Pressable disabled={product.stock <= 0} onPress={handleQuickAdd} style={({ pressed }) => [styles.quickAdd, added && styles.quickAddSuccess, pressed && styles.favoritePressed, product.stock <= 0 && styles.quickAddDisabled]}><MaterialIcons name={added ? "check" : "shopping-bag"} size={18} color={added ? "#FFFFFF" : HOBEE.colors.ink} /></Pressable>{added ? <Animated.View pointerEvents="none" style={[styles.addedBubble, feedbackStyle]}><Text style={styles.addedBubbleText}>เพิ่มแล้ว</Text></Animated.View> : null}</View> : null}</View>{showCommerceMeta ? <View style={styles.productMeta}><View style={styles.originRow}><MaterialIcons name="location-on" size={14} color={HOBEE.colors.shopLocation} /><Text numberOfLines={1} style={styles.originText}>{product.origin}</Text></View><View style={styles.stockRow}><MaterialIcons name="local-shipping" size={14} color={HOBEE.colors.shopShipping} /><Text style={styles.stockText}>{product.stock > 0 ? "พร้อมส่ง" : "สินค้าหมด"}</Text></View></View> : null}</View></Pressable>;
}

export function TripCard({ image, badge, title, detail, price, onPress }: { image: string; badge?: string; title: string; detail?: string; price?: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.trip, pressed && styles.pressed]}><View><Image source={{ uri: image }} style={styles.tripImage} resizeMode="cover" />{badge ? <View style={styles.tripBadge}><Text style={styles.tripBadgeText}>{badge}</Text></View> : null}</View><View style={styles.tripBody}><Text numberOfLines={2} style={styles.productTitle}>{title}</Text>{detail ? <Text numberOfLines={1} style={styles.detail}>{detail}</Text> : null}{price ? <Text style={styles.price}>{price}</Text> : null}</View></Pressable>; }

export function ServiceTile({ label, icon, tone, onPress }: { label: string; icon: keyof typeof MaterialIcons.glyphMap; tone: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.service, pressed && styles.pressed]}><View style={[styles.serviceIcon, { backgroundColor: tone }]}><MaterialIcons name={icon} size={27} color="#267B67" /></View><Text style={styles.serviceText}>{label}</Text></Pressable>; }

export function CommunityCard({ name, detail, image, onPress }: { name: string; detail: string; image: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.community, pressed && styles.pressed]}><View style={styles.ring}><Image source={{ uri: image }} style={styles.profile} /><View style={styles.verify}><MaterialIcons name="check" size={13} color="#FFFFFF" /></View></View><Text numberOfLines={1} style={styles.communityName}>{name}</Text><Text numberOfLines={1} style={styles.communityDetail}>{detail}</Text></Pressable>; }

export function EmptyState({ title, description, onAction, actionLabel = "ล้างตัวกรอง" }: { title: string; description: string; onAction?: () => void; actionLabel?: string }) { return <View style={styles.empty}><MaterialIcons name="search-off" size={34} color={HOBEE.colors.goldDark} /><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyText}>{description}</Text>{onAction ? <Pressable onPress={onAction} style={styles.emptyAction}><Text style={styles.emptyActionText}>{actionLabel}</Text></Pressable> : null}</View>; }

export function ProductSkeleton() {
  const pulse = useRef(new Animated.Value(0.52)).current;
  useEffect(() => { const animation = Animated.loop(Animated.sequence([Animated.timing(pulse, { toValue: 0.95, duration: 650, useNativeDriver: true }), Animated.timing(pulse, { toValue: 0.52, duration: 650, useNativeDriver: true })])); animation.start(); return () => animation.stop(); }, [pulse]);
  return <Animated.View style={[styles.skeletonGrid, { opacity: pulse }]}>{[0, 1, 2, 3].map((item) => <View key={item} style={styles.skeleton}><View style={styles.skeletonImage} /><View style={styles.skeletonLine} /><View style={[styles.skeletonLine, styles.skeletonShort]} /></View>)}</Animated.View>;
}

const styles = StyleSheet.create({
  appShell: { flex: 1 }, fixedTopShell: { zIndex: 10, borderBottomWidth: 1, borderBottomColor: "rgba(233,229,223,0.82)", backgroundColor: HOBEE.colors.canvas, paddingHorizontal: 20, paddingBottom: 13 }, fixedTopShellElevated: { borderBottomColor: "rgba(210,204,196,0.96)", shadowColor: "#1A1816", shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.12, shadowRadius: 10, elevation: 8 }, fixedSearch: { marginTop: 0 }, scrollRegion: { flex: 1 }, header: { minHeight: 70, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, headerCompact: { minHeight: 60 }, brand: { flexShrink: 1, flexDirection: "row", alignItems: "center", gap: 6 }, brandCompact: { gap: 4 }, mark: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 20, backgroundColor: "#25211F", borderWidth: 1, borderColor: "#9B762A" }, markCompact: { width: 34, height: 34, borderRadius: 17 }, markText: { color: "#FFF", fontSize: 18, fontWeight: "900" }, wordmark: { flexShrink: 0, color: HOBEE.colors.ink, fontSize: 26, fontWeight: "900", letterSpacing: -1.4 }, wordmarkCompact: { fontSize: 21, letterSpacing: -1.1 }, brandSuffix: { flexShrink: 1, color: HOBEE.colors.shopTeal, fontSize: 17, fontWeight: "900", letterSpacing: -0.8 }, headerSpacer: { flex: 1 }, location: { height: 42, flexDirection: "row", alignItems: "center", gap: 1, borderRadius: 21, borderWidth: 1, borderColor: "#E5E1DB", backgroundColor: "#FCFBFA", paddingHorizontal: 8 }, locationCompact: { maxWidth: 88, height: 36, paddingHorizontal: 6 }, locationText: { color: "#3A3632", fontSize: 15, fontWeight: "700" }, locationTextCompact: { flexShrink: 1, fontSize: 13 }, headerActions: { flexDirection: "row", alignItems: "center", flexShrink: 0 }, headerIcon: { width: 29, height: 44, alignItems: "center", justifyContent: "center" }, headerIconCompact: { width: 27, height: 40 }, badge: { position: "absolute", top: 7, right: 0, minWidth: 16, height: 16, alignItems: "center", justifyContent: "center", borderRadius: 8, backgroundColor: HOBEE.colors.gold, paddingHorizontal: 3 }, badgeText: { color: HOBEE.colors.ink, fontSize: 9, fontWeight: "900" }, avatarButton: { width: 43, height: 43, overflow: "hidden", borderRadius: 22, borderWidth: 2, borderColor: "#ECE9E4", backgroundColor: "#F2F0ED", padding: 3 }, avatar: { width: "100%", height: "100%", borderRadius: 18 },
  search: { height: 58, flexDirection: "row", alignItems: "center", gap: 13, borderRadius: 30, backgroundColor: "#F1F0EE", paddingHorizontal: 18 }, searchPlaceholder: { flex: 1, color: "#ABA6A1", fontSize: 17, fontWeight: "500" }, searchInput: { flex: 1, height: 58, color: HOBEE.colors.ink, fontSize: 17, fontWeight: "600" }, clear: { width: 30, height: 40, alignItems: "center", justifyContent: "center" },
  section: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 31, marginBottom: 16 }, sectionTitleWrap: { flexDirection: "row", alignItems: "center", gap: 12 }, accent: { width: 9, height: 40, borderRadius: 5, backgroundColor: HOBEE.colors.gold }, sectionTitle: { color: HOBEE.colors.ink, fontSize: 28, fontWeight: "900", letterSpacing: -0.8 }, action: { flexDirection: "row", alignItems: "center" }, actionText: { color: "#77716B", fontSize: 15, fontWeight: "800" },
  category: { width: "22%", height: 128, alignItems: "center", justifyContent: "center", gap: 10, borderRadius: 22, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, ...HOBEE.shadow }, categoryIcon: { width: 55, height: 55, alignItems: "center", justifyContent: "center", borderRadius: 18 }, categoryLabel: { maxWidth: "92%", color: "#262220", fontSize: 13, fontWeight: "800", textAlign: "center" },
  product: { width: "48%", overflow: "hidden", borderRadius: 23, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, ...HOBEE.shadow }, productImage: { width: "100%", height: 154, backgroundColor: "#E9E7E3" }, favorite: { position: "absolute", top: 10, right: 10, width: 36, height: 36, alignItems: "center", justifyContent: "center", borderRadius: 18, backgroundColor: "rgba(255,255,255,0.92)" }, productBody: { minHeight: 112, justifyContent: "space-between", padding: 13 }, productBodyCommerce: { minHeight: 183 }, productBadge: { alignSelf: "flex-start", marginBottom: 5, borderRadius: 12, backgroundColor: "#E0F1E8", paddingHorizontal: 9, paddingVertical: 4 }, productBadgeText: { color: "#16745F", fontSize: 10, fontWeight: "900" }, productTitle: { color: "#25211F", fontSize: 16, fontWeight: "900", lineHeight: 21 }, ratingRow: { flexDirection: "row", alignItems: "center", gap: 3, marginTop: 7 }, ratingText: { color: HOBEE.colors.shopOrange, fontSize: 13, fontWeight: "900" }, reviewText: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600" }, priceRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 6, marginTop: 10 }, price: { marginTop: 10, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, shopPrice: { color: HOBEE.colors.shopOrange }, compare: { color: "#A39E98", fontSize: 12, fontWeight: "600", textDecorationLine: "line-through" }, quickAddWrap: { marginLeft: "auto", position: "relative" }, quickAdd: { width: 31, height: 31, alignItems: "center", justifyContent: "center", borderRadius: 11, backgroundColor: "#FFF2D4" }, quickAddSuccess: { backgroundColor: HOBEE.colors.shopShipping }, quickAddDisabled: { opacity: 0.45 }, addedBubble: { position: "absolute", right: 0, bottom: 38, borderRadius: 12, backgroundColor: HOBEE.colors.shopShipping, paddingHorizontal: 8, paddingVertical: 5 }, addedBubbleText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" }, productMeta: { gap: 5, marginTop: 9, borderTopWidth: 1, borderTopColor: "#F0ECE6", paddingTop: 8 }, originRow: { flexDirection: "row", alignItems: "center", gap: 3 }, originText: { flex: 1, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600" }, stockRow: { flexDirection: "row", alignItems: "center", gap: 3 }, stockText: { color: HOBEE.colors.shopShipping, fontSize: 11, fontWeight: "800" },
  trip: { width: "100%", overflow: "hidden", borderRadius: 23, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, ...HOBEE.shadow }, tripImage: { width: "100%", height: 154, backgroundColor: "#E9E7E3" }, tripBadge: { position: "absolute", top: 12, left: 12, borderRadius: 13, backgroundColor: "#197C6A", paddingHorizontal: 10, paddingVertical: 5 }, tripBadgeText: { color: "#FFF", fontSize: 11, fontWeight: "900" }, tripBody: { minHeight: 104, justifyContent: "space-between", padding: 13 }, detail: { marginTop: 6, color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600" },
  service: { width: "48%", minHeight: 101, flexDirection: "row", alignItems: "center", gap: 11, borderRadius: 21, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 13, ...HOBEE.shadow }, serviceIcon: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 16 }, serviceText: { flex: 1, color: "#2A2624", fontSize: 16, fontWeight: "900", lineHeight: 20 },
  community: { width: "48%", minHeight: 202, alignItems: "center", justifyContent: "center", borderRadius: 24, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 15, ...HOBEE.shadow }, ring: { position: "relative", width: 91, height: 91, alignItems: "center", justifyContent: "center", borderRadius: 46, borderWidth: 5, borderColor: "#D8B047" }, profile: { width: 77, height: 77, borderRadius: 39 }, verify: { position: "absolute", right: -3, bottom: 0, width: 24, height: 24, alignItems: "center", justifyContent: "center", borderRadius: 12, borderWidth: 2, borderColor: "#FFF", backgroundColor: HOBEE.colors.gold }, communityName: { marginTop: 13, color: "#24211F", fontSize: 16, fontWeight: "900" }, communityDetail: { marginTop: 4, color: HOBEE.colors.muted, fontSize: 13, fontWeight: "600" },
  empty: { alignItems: "center", borderRadius: 24, borderWidth: 1, borderStyle: "dashed", borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 28, paddingVertical: 38 }, emptyTitle: { marginTop: 15, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, emptyText: { marginTop: 6, color: HOBEE.colors.muted, fontSize: 14, fontWeight: "600", lineHeight: 20, textAlign: "center" }, emptyAction: { marginTop: 17, borderRadius: 18, backgroundColor: HOBEE.colors.gold, paddingHorizontal: 18, paddingVertical: 10 }, emptyActionText: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" }, skeletonGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", rowGap: 16 }, skeleton: { width: "48%", overflow: "hidden", borderRadius: 23, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingBottom: 13 }, skeletonImage: { width: "100%", height: 154, backgroundColor: "#EDEAE5" }, skeletonLine: { height: 14, marginTop: 13, marginHorizontal: 13, borderRadius: 7, backgroundColor: "#EEEAE5" }, skeletonShort: { width: "46%" },
  pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] }, favoritePressed: { opacity: 0.68, transform: [{ scale: 0.92 }] },
});
