import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Image, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { useCart } from "@/contexts/cart-context";
import { formatThaiBaht, type HobeeProduct } from "@/lib/hobee-data";
import { HOBEE } from "@/components/hobee/design-tokens";

const AVATAR = "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=85&w=300";

export function LocationPill() { return <Pressable onPress={() => router.push("/(tabs)/discover")} style={({ pressed }) => [styles.location, pressed && styles.pressed]}><MaterialIcons name="location-on" size={18} color={HOBEE.colors.goldDark} /><Text style={styles.locationText}>เชียงใหม่</Text><MaterialIcons name="keyboard-arrow-down" size={18} color="#9A958E" /></Pressable>; }

export function AppHeader() {
  const { itemCount } = useCart();
  return <View style={styles.header}><Pressable onPress={() => router.replace("/(tabs)")} style={({ pressed }) => [styles.brand, pressed && styles.pressed]}><View style={styles.mark}><Text style={styles.markText}>H</Text></View><Text style={styles.wordmark}>HOBEE</Text></Pressable><LocationPill /><View style={styles.headerActions}><Pressable onPress={() => router.push("/cart")} style={({ pressed }) => [styles.headerIcon, pressed && styles.pressed]}><MaterialIcons name="shopping-bag" size={28} color={HOBEE.colors.ink} />{itemCount > 0 ? <View style={styles.badge}><Text style={styles.badgeText}>{itemCount > 9 ? "9+" : itemCount}</Text></View> : null}</Pressable><Pressable onPress={() => router.push("/orders")} style={({ pressed }) => [styles.headerIcon, pressed && styles.pressed]}><MaterialIcons name="notifications-none" size={30} color={HOBEE.colors.ink} /></Pressable><Pressable onPress={() => router.push("/(tabs)/account")} style={({ pressed }) => [styles.avatarButton, pressed && styles.pressed]}><Image source={{ uri: AVATAR }} style={styles.avatar} /></Pressable></View></View>;
}

export function SearchBar({ value = "", onChangeText, onClear, onPress, placeholder = "ค้นหาทริป สินค้า ร้านค้า หรือบริการ", editable = false }: { value?: string; onChangeText?: (value: string) => void; onClear?: () => void; onPress?: () => void; placeholder?: string; editable?: boolean }) {
  const content = <><MaterialIcons name="search" size={29} color="#9C9993" />{editable ? <TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#ABA6A1" returnKeyType="search" style={styles.searchInput} /> : <Text numberOfLines={1} style={styles.searchPlaceholder}>{placeholder}</Text>}{value && onClear ? <Pressable onPress={onClear} style={styles.clear}><MaterialIcons name="close" size={22} color="#9C9993" /></Pressable> : <MaterialIcons name="keyboard-voice" size={27} color="#9C9993" />}</>;
  return onPress && !editable ? <Pressable onPress={onPress} style={({ pressed }) => [styles.search, pressed && styles.pressed]}>{content}</Pressable> : <View style={styles.search}>{content}</View>;
}

export function SectionHeader({ title, onPress, actionLabel = "ดูทั้งหมด" }: { title: string; onPress?: () => void; actionLabel?: string }) { return <View style={styles.section}><View style={styles.sectionTitleWrap}><View style={styles.accent} /><Text style={styles.sectionTitle}>{title}</Text></View>{onPress ? <Pressable onPress={onPress} style={({ pressed }) => [styles.action, pressed && styles.pressed]}><Text style={styles.actionText}>{actionLabel}</Text><MaterialIcons name="chevron-right" size={25} color="#77716B" /></Pressable> : null}</View>; }

export function CategoryTile({ label, icon, tone, onPress }: { label: string; icon: keyof typeof MaterialIcons.glyphMap; tone: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.category, pressed && styles.pressed]}><View style={[styles.categoryIcon, { backgroundColor: tone }]}><MaterialIcons name={icon} size={30} color={HOBEE.colors.botanical} /></View><Text numberOfLines={1} style={styles.categoryLabel}>{label}</Text></Pressable>; }

export function ProductCard({ product, favorite, onFavorite }: { product: HobeeProduct; favorite?: boolean; onFavorite?: () => void }) { return <Pressable onPress={() => router.push({ pathname: "/product/[id]", params: { id: product.id } })} style={({ pressed }) => [styles.product, pressed && styles.pressed]}><View><Image source={{ uri: product.image }} style={styles.productImage} resizeMode="cover" />{onFavorite ? <Pressable onPress={onFavorite} style={({ pressed }) => [styles.favorite, pressed && styles.favoritePressed]}><MaterialIcons name={favorite ? "favorite" : "favorite-border"} size={21} color={favorite ? "#C45A57" : HOBEE.colors.ink} /></Pressable> : null}</View><View style={styles.productBody}>{product.badge ? <View style={styles.productBadge}><Text style={styles.productBadgeText}>{product.badge}</Text></View> : null}<Text numberOfLines={2} style={styles.productTitle}>{product.shortName}</Text><View style={styles.priceRow}><Text style={styles.price}>{formatThaiBaht(product.price)}</Text>{product.compareAtPrice ? <Text style={styles.compare}>{formatThaiBaht(product.compareAtPrice)}</Text> : null}</View></View></Pressable>; }

export function TripCard({ image, badge, title, detail, price, onPress }: { image: string; badge?: string; title: string; detail?: string; price?: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.trip, pressed && styles.pressed]}><View><Image source={{ uri: image }} style={styles.tripImage} resizeMode="cover" />{badge ? <View style={styles.tripBadge}><Text style={styles.tripBadgeText}>{badge}</Text></View> : null}</View><View style={styles.tripBody}><Text numberOfLines={2} style={styles.productTitle}>{title}</Text>{detail ? <Text numberOfLines={1} style={styles.detail}>{detail}</Text> : null}{price ? <Text style={styles.price}>{price}</Text> : null}</View></Pressable>; }

export function ServiceTile({ label, icon, tone, onPress }: { label: string; icon: keyof typeof MaterialIcons.glyphMap; tone: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.service, pressed && styles.pressed]}><View style={[styles.serviceIcon, { backgroundColor: tone }]}><MaterialIcons name={icon} size={27} color="#267B67" /></View><Text style={styles.serviceText}>{label}</Text></Pressable>; }

export function CommunityCard({ name, detail, image, onPress }: { name: string; detail: string; image: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.community, pressed && styles.pressed]}><View style={styles.ring}><Image source={{ uri: image }} style={styles.profile} /><View style={styles.verify}><MaterialIcons name="check" size={13} color="#FFFFFF" /></View></View><Text numberOfLines={1} style={styles.communityName}>{name}</Text><Text numberOfLines={1} style={styles.communityDetail}>{detail}</Text></Pressable>; }

export function EmptyState({ title, description, onAction, actionLabel = "ล้างตัวกรอง" }: { title: string; description: string; onAction?: () => void; actionLabel?: string }) { return <View style={styles.empty}><MaterialIcons name="search-off" size={34} color={HOBEE.colors.goldDark} /><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyText}>{description}</Text>{onAction ? <Pressable onPress={onAction} style={styles.emptyAction}><Text style={styles.emptyActionText}>{actionLabel}</Text></Pressable> : null}</View>; }

export function ProductSkeleton() { return <View style={styles.skeletonGrid}>{[0, 1, 2, 3].map((item) => <View key={item} style={styles.skeleton}><View style={styles.skeletonImage} /><View style={styles.skeletonLine} /><View style={[styles.skeletonLine, styles.skeletonShort]} /></View>)}</View>; }

const styles = StyleSheet.create({
  header: { minHeight: 70, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, brand: { flexDirection: "row", alignItems: "center", gap: 6 }, mark: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 20, backgroundColor: "#25211F", borderWidth: 1, borderColor: "#9B762A" }, markText: { color: "#FFF", fontSize: 18, fontWeight: "900" }, wordmark: { color: HOBEE.colors.ink, fontSize: 26, fontWeight: "900", letterSpacing: -1.4 }, location: { height: 42, flexDirection: "row", alignItems: "center", gap: 1, borderRadius: 21, borderWidth: 1, borderColor: "#E5E1DB", backgroundColor: "#FCFBFA", paddingHorizontal: 8 }, locationText: { color: "#3A3632", fontSize: 15, fontWeight: "700" }, headerActions: { flexDirection: "row", alignItems: "center" }, headerIcon: { width: 29, height: 44, alignItems: "center", justifyContent: "center" }, badge: { position: "absolute", top: 7, right: 0, minWidth: 16, height: 16, alignItems: "center", justifyContent: "center", borderRadius: 8, backgroundColor: HOBEE.colors.gold, paddingHorizontal: 3 }, badgeText: { color: HOBEE.colors.ink, fontSize: 9, fontWeight: "900" }, avatarButton: { width: 43, height: 43, overflow: "hidden", borderRadius: 22, borderWidth: 2, borderColor: "#ECE9E4", backgroundColor: "#F2F0ED", padding: 3 }, avatar: { width: "100%", height: "100%", borderRadius: 18 },
  search: { height: 58, flexDirection: "row", alignItems: "center", gap: 13, borderRadius: 30, backgroundColor: "#F1F0EE", paddingHorizontal: 18 }, searchPlaceholder: { flex: 1, color: "#ABA6A1", fontSize: 17, fontWeight: "500" }, searchInput: { flex: 1, height: 58, color: HOBEE.colors.ink, fontSize: 17, fontWeight: "600" }, clear: { width: 30, height: 40, alignItems: "center", justifyContent: "center" },
  section: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 31, marginBottom: 16 }, sectionTitleWrap: { flexDirection: "row", alignItems: "center", gap: 12 }, accent: { width: 9, height: 40, borderRadius: 5, backgroundColor: HOBEE.colors.gold }, sectionTitle: { color: HOBEE.colors.ink, fontSize: 28, fontWeight: "900", letterSpacing: -0.8 }, action: { flexDirection: "row", alignItems: "center" }, actionText: { color: "#77716B", fontSize: 15, fontWeight: "800" },
  category: { width: "22%", height: 128, alignItems: "center", justifyContent: "center", gap: 10, borderRadius: 22, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, ...HOBEE.shadow }, categoryIcon: { width: 55, height: 55, alignItems: "center", justifyContent: "center", borderRadius: 18 }, categoryLabel: { maxWidth: "92%", color: "#262220", fontSize: 13, fontWeight: "800", textAlign: "center" },
  product: { width: "48%", overflow: "hidden", borderRadius: 23, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, ...HOBEE.shadow }, productImage: { width: "100%", height: 154, backgroundColor: "#E9E7E3" }, favorite: { position: "absolute", top: 10, right: 10, width: 36, height: 36, alignItems: "center", justifyContent: "center", borderRadius: 18, backgroundColor: "rgba(255,255,255,0.92)" }, productBody: { minHeight: 112, justifyContent: "space-between", padding: 13 }, productBadge: { alignSelf: "flex-start", marginBottom: 5, borderRadius: 12, backgroundColor: "#E0F1E8", paddingHorizontal: 9, paddingVertical: 4 }, productBadgeText: { color: "#16745F", fontSize: 10, fontWeight: "900" }, productTitle: { color: "#25211F", fontSize: 16, fontWeight: "900", lineHeight: 21 }, priceRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 6, marginTop: 10 }, price: { marginTop: 10, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, compare: { color: "#A39E98", fontSize: 12, fontWeight: "600", textDecorationLine: "line-through" },
  trip: { width: "100%", overflow: "hidden", borderRadius: 23, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, ...HOBEE.shadow }, tripImage: { width: "100%", height: 154, backgroundColor: "#E9E7E3" }, tripBadge: { position: "absolute", top: 12, left: 12, borderRadius: 13, backgroundColor: "#197C6A", paddingHorizontal: 10, paddingVertical: 5 }, tripBadgeText: { color: "#FFF", fontSize: 11, fontWeight: "900" }, tripBody: { minHeight: 104, justifyContent: "space-between", padding: 13 }, detail: { marginTop: 6, color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600" },
  service: { width: "48%", minHeight: 101, flexDirection: "row", alignItems: "center", gap: 11, borderRadius: 21, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 13, ...HOBEE.shadow }, serviceIcon: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 16 }, serviceText: { flex: 1, color: "#2A2624", fontSize: 16, fontWeight: "900", lineHeight: 20 },
  community: { width: "48%", minHeight: 202, alignItems: "center", justifyContent: "center", borderRadius: 24, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 15, ...HOBEE.shadow }, ring: { position: "relative", width: 91, height: 91, alignItems: "center", justifyContent: "center", borderRadius: 46, borderWidth: 5, borderColor: "#D8B047" }, profile: { width: 77, height: 77, borderRadius: 39 }, verify: { position: "absolute", right: -3, bottom: 0, width: 24, height: 24, alignItems: "center", justifyContent: "center", borderRadius: 12, borderWidth: 2, borderColor: "#FFF", backgroundColor: HOBEE.colors.gold }, communityName: { marginTop: 13, color: "#24211F", fontSize: 16, fontWeight: "900" }, communityDetail: { marginTop: 4, color: HOBEE.colors.muted, fontSize: 13, fontWeight: "600" },
  empty: { alignItems: "center", borderRadius: 24, borderWidth: 1, borderStyle: "dashed", borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 28, paddingVertical: 38 }, emptyTitle: { marginTop: 15, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, emptyText: { marginTop: 6, color: HOBEE.colors.muted, fontSize: 14, fontWeight: "600", lineHeight: 20, textAlign: "center" }, emptyAction: { marginTop: 17, borderRadius: 18, backgroundColor: HOBEE.colors.gold, paddingHorizontal: 18, paddingVertical: 10 }, emptyActionText: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" }, skeletonGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", rowGap: 16 }, skeleton: { width: "48%", overflow: "hidden", borderRadius: 23, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingBottom: 13 }, skeletonImage: { width: "100%", height: 154, backgroundColor: "#EDEAE5" }, skeletonLine: { height: 14, marginTop: 13, marginHorizontal: 13, borderRadius: 7, backgroundColor: "#EEEAE5" }, skeletonShort: { width: "46%" },
  pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] }, favoritePressed: { opacity: 0.68, transform: [{ scale: 0.92 }] },
});
