import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { formatTravelPrice } from "@/lib/travel-data";
import type { TravelListing } from "@/lib/travel-types";

export function TravelListingCard({ listing, onPress }: { listing: TravelListing; onPress: () => void }) {
  const cover = listing.images[0];
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View><Image source={{ uri: cover }} style={styles.image} /><View style={styles.typeBadge}><MaterialIcons name={listing.listingType === "trip" ? "explore" : "hotel"} size={13} color="#FFFFFF" /><Text style={styles.typeText}>{listing.listingType === "trip" ? "ทริป" : listing.propertyType ?? "ที่พัก"}</Text></View>{listing.isHalalCertified ? <View style={styles.halal}><MaterialIcons name="verified" size={15} color="#157659" /></View> : null}</View><View style={styles.body}><Text numberOfLines={2} style={styles.title}>{listing.title}</Text><View style={styles.meta}><MaterialIcons name="location-on" size={14} color={HOBEE.colors.shopLocation} /><Text numberOfLines={1} style={styles.metaText}>{listing.provinceName}</Text></View><View style={styles.rating}><MaterialIcons name="star" size={15} color={HOBEE.colors.shopOrange} /><Text style={styles.ratingText}>{listing.rating.toFixed(1)}</Text><Text style={styles.reviewText}>({listing.reviewsCount})</Text></View><Text style={styles.price}>{formatTravelPrice(listing.priceFrom)}<Text style={styles.priceSuffix}>{listing.listingType === "trip" ? " / คน" : " / คืน"}</Text></Text></View></Pressable>;
}

export function TravelIntentCard({ label, icon, tone, onPress }: { label: string; icon: keyof typeof MaterialIcons.glyphMap; tone: string; onPress: () => void }) {
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.intent, pressed && styles.pressed]}><View style={[styles.intentIcon, { backgroundColor: tone }]}><MaterialIcons name={icon} size={25} color={HOBEE.colors.botanical} /></View><Text numberOfLines={2} style={styles.intentText}>{label}</Text></Pressable>;
}

export function TravelStep({ number, title, active }: { number: number; title: string; active: boolean }) {
  return <View style={styles.step}><View style={[styles.stepNumber, active && styles.stepActive]}><Text style={[styles.stepNumberText, active && styles.stepNumberActive]}>{number}</Text></View><Text numberOfLines={1} style={[styles.stepText, active && styles.stepTextActive]}>{title}</Text></View>;
}

const styles = StyleSheet.create({
  card: { width: 228, overflow: "hidden", borderRadius: 23, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, ...HOBEE.shadow }, image: { width: "100%", height: 155, backgroundColor: "#E7E5E0" }, typeBadge: { position: "absolute", left: 11, top: 11, flexDirection: "row", alignItems: "center", gap: 4, borderRadius: 13, backgroundColor: "rgba(19,79,67,0.88)", paddingHorizontal: 9, paddingVertical: 5 }, typeText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" }, halal: { position: "absolute", right: 11, top: 11, width: 29, height: 29, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: "rgba(255,255,255,0.94)" }, body: { padding: 13 }, title: { minHeight: 42, color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900", lineHeight: 21 }, meta: { flexDirection: "row", alignItems: "center", gap: 3, marginTop: 7 }, metaText: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "700" }, rating: { flexDirection: "row", alignItems: "center", gap: 3, marginTop: 7 }, ratingText: { color: HOBEE.colors.shopOrange, fontSize: 12, fontWeight: "900" }, reviewText: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600" }, price: { marginTop: 10, color: HOBEE.colors.shopOrange, fontSize: 17, fontWeight: "900" }, priceSuffix: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700" }, intent: { width: 132, minHeight: 110, alignItems: "center", justifyContent: "center", gap: 9, borderRadius: 21, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 12, ...HOBEE.shadow }, intentIcon: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: 17 }, intentText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900", lineHeight: 18, textAlign: "center" }, pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] }, step: { flex: 1, alignItems: "center", gap: 5 }, stepNumber: { width: 28, height: 28, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#E8E5E0" }, stepActive: { backgroundColor: HOBEE.colors.gold }, stepNumberText: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "900" }, stepNumberActive: { color: HOBEE.colors.ink }, stepText: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "800", textAlign: "center" }, stepTextActive: { color: HOBEE.colors.ink },
});
