import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";

export default function TravelReviewScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const [rating, setRating] = useState(0); const [note, setNote] = useState(""); const [submitted, setSubmitted] = useState(false); return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.title}>รีวิวทริป</Text><View style={styles.back} /></View><ScrollView contentContainerStyle={styles.content}>{submitted ? <View style={styles.success}><MaterialIcons name="check-circle" size={52} color={HOBEE.colors.travelTeal} /><Text style={styles.successTitle}>บันทึกรีวิวในเครื่องแล้ว</Text><Text style={styles.successText}>การส่งรีวิวจริงจะเชื่อมกับ review backend เมื่อพร้อม</Text><Pressable onPress={() => router.replace("/travel/my-trips" as never)} style={styles.submit}><Text style={styles.submitText}>กลับสู่ทริปของฉัน</Text></Pressable></View> : <><Text style={styles.heading}>การเดินทางครั้งนี้เป็นอย่างไร?</Text><Text style={styles.copy}>ให้คะแนนและเล่าประสบการณ์เพื่อช่วยนักเดินทางคนต่อไป</Text><View style={styles.stars}>{[1, 2, 3, 4, 5].map((value) => <Pressable key={value} onPress={() => setRating(value)}><MaterialIcons name={value <= rating ? "star" : "star-border"} size={39} color={HOBEE.colors.gold} /></Pressable>)}</View><TextInput value={note} onChangeText={setNote} multiline placeholder="เขียนรีวิวของคุณ" placeholderTextColor={HOBEE.colors.muted} style={styles.input} /><View style={styles.boundary}><MaterialIcons name="info-outline" size={18} color={HOBEE.colors.travelTeal} /><Text style={styles.boundaryText}>Review ID {id} อยู่ใน presentation flow และจะไม่ส่งข้อมูลขึ้น server ในขั้นนี้</Text></View><Pressable onPress={() => setSubmitted(true)} style={styles.submit}><Text style={styles.submitText}>บันทึกรีวิว</Text><MaterialIcons name="arrow-forward" size={18} color={HOBEE.colors.ink} /></Pressable></>}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", height: 62, paddingHorizontal: 18 }, back: { alignItems: "center", justifyContent: "center", width: 38, height: 38, borderRadius: 19, backgroundColor: HOBEE.colors.surface }, title: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, content: { padding: 20, paddingBottom: 40 }, heading: { color: HOBEE.colors.ink, fontSize: 23, fontWeight: "900" }, copy: { marginTop: 6, color: HOBEE.colors.muted, fontSize: 12, lineHeight: 18, fontWeight: "600" }, stars: { flexDirection: "row", justifyContent: "space-between", marginTop: 28, paddingHorizontal: 7 }, input: { minHeight: 150, marginTop: 28, borderRadius: 18, backgroundColor: HOBEE.colors.surface, color: HOBEE.colors.ink, fontSize: 13, textAlignVertical: "top", padding: 14, ...HOBEE.elevation.surface }, boundary: { flexDirection: "row", alignItems: "flex-start", gap: 8, marginTop: 15, borderRadius: 15, backgroundColor: HOBEE.atmosphere.skyMist, padding: 12 }, boundaryText: { flex: 1, color: HOBEE.colors.ink, fontSize: 10, lineHeight: 14, fontWeight: "700" }, submit: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, marginTop: 18, borderRadius: 17, backgroundColor: HOBEE.colors.gold, paddingVertical: 13 }, submitText: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "900" }, success: { alignItems: "center", gap: 10, paddingTop: 70 }, successTitle: { color: HOBEE.colors.ink, fontSize: 20, fontWeight: "900" }, successText: { color: HOBEE.colors.muted, fontSize: 12, textAlign: "center", lineHeight: 18, fontWeight: "600" } });
