import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { useState } from "react";

import { HOBEE } from "@/components/hobee/design-tokens";
import { BackHeader, InfoRow, StatusChip } from "@/components/hobee/commerce-ui";
import { PrimaryButton } from "@/components/hobee/primary-button";
import { ScreenContainer } from "@/components/screen-container";
import { useToast } from "@/contexts/toast-context";
import { hobeeApi, type PaymentAction } from "@/lib/hobee-api";

export default function PaymentScreen() {
  const { orderId } = useLocalSearchParams<{ orderId: string }>(); const { showToast } = useToast(); const [loading, setLoading] = useState(false); const [action, setAction] = useState<PaymentAction | null>(null);
  const startPromptPay = async () => { if (!hobeeApi.isConfigured()) { showToast("ยังไม่ได้ตั้งค่า Vercel payment API", "info"); return; } setLoading(true); try { const result = await hobeeApi.createPaymentIntent({ orderId, method: "opn_promptpay" }); setAction(result.action); showToast(result.action.testMode ? "สร้าง PromptPay sandbox QR แล้ว" : "สร้าง PromptPay QR แล้ว"); } catch (error) { showToast(error instanceof Error ? error.message : "ไม่สามารถเริ่มการชำระเงินได้", "error"); } finally { setLoading(false); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]" className="px-5" safeAreaClassName="pt-3"><BackHeader title="ชำระเงิน" subtitle={`คำสั่งซื้อ ${orderId.slice(0, 8).toUpperCase()}`} onBack={() => router.back()} /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>{action?.type === "promptpay_qr" ? <View style={styles.qrCard}><StatusChip status="awaiting_payment" label="รอการชำระเงิน" /><Text style={styles.qrTitle}>สแกนเพื่อชำระผ่าน PromptPay</Text><Text style={styles.qrDescription}>เปิดแอปธนาคาร เลือกสแกน QR และยืนยันยอดเงิน ระบบจะอัปเดตสถานะหลังได้รับ webhook ที่ยืนยันแล้ว</Text>{action.qrImageUrl ? <Image source={{ uri: action.qrImageUrl }} style={styles.qrImage} /> : <View style={styles.qrPlaceholder}><MaterialIcons name="qr-code-2" size={128} color={HOBEE.colors.nav} /><Text style={styles.qrHint}>QR จะปรากฏเมื่อเชื่อม Opn sandbox/live แล้ว</Text></View>}<View style={styles.awaiting}><MaterialIcons name="schedule" size={18} color={HOBEE.colors.goldDark} /><Text style={styles.awaitingText}>{action.testMode ? "โหมด sandbox — ไม่มีการเรียกเก็บเงินจริง" : "รอการยืนยันจากผู้ให้บริการชำระเงิน"}</Text></View><PrimaryButton label="ดูสถานะคำสั่งซื้อ" icon="receipt-long" variant="outline" onPress={() => router.replace("/orders")} style={styles.button} /></View> : <><View style={styles.intro}><Text style={styles.introTitle}>เลือกช่องทางที่ปลอดภัย</Text><Text style={styles.introText}>HOBEE ไม่เก็บข้อมูลบัตรของคุณ และรับสถานะการชำระเงินจาก provider ที่ยืนยันแล้วเท่านั้น</Text></View><View style={styles.method}><InfoRow icon="qr-code-2" label="PromptPay QR" value="สร้าง QR และชำระผ่านแอปธนาคารของคุณ" /><PrimaryButton label="ชำระด้วย PromptPay" icon="arrow-forward" loading={loading} onPress={() => void startPromptPay()} style={styles.button} /></View><View style={styles.method}><InfoRow icon="credit-card" label="บัตรเครดิต / เดบิต" value="ใช้ secure tokenization ของผู้ให้บริการ โดยไม่ส่งข้อมูลบัตรเข้า HOBEE" /><PrimaryButton label="เตรียมชำระด้วยบัตร" icon="lock-outline" variant="outline" onPress={() => showToast("ช่องกรอกบัตรจะเปิดหลังตั้งค่า Opn public key และ development build", "info")} style={styles.button} /></View><View style={styles.stateCard}><MaterialIcons name="info-outline" size={20} color={HOBEE.colors.botanical} /><Text style={styles.stateText}>หลังเริ่มชำระเงิน สถานะอาจเป็น รอชำระเงิน, กำลังประมวลผล, ชำระแล้ว หรือไม่สำเร็จ ตามข้อมูลจริงจาก provider</Text></View></>}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 28 }, intro: { borderRadius: 23, backgroundColor: HOBEE.colors.nav, padding: 19 }, introTitle: { color: "#FFFFFF", fontSize: 19, fontWeight: "900" }, introText: { marginTop: 7, color: "#D8D4CF", fontSize: 13, lineHeight: 19, fontWeight: "600" }, method: { marginTop: 14, borderRadius: 22, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 14, paddingBottom: 14 }, button: { marginTop: 14 }, stateCard: { flexDirection: "row", gap: 10, marginTop: 16, borderRadius: 19, backgroundColor: "#E2F7EE", padding: 14 }, stateText: { flex: 1, color: "#2B5C50", fontSize: 12, lineHeight: 18, fontWeight: "600" }, qrCard: { alignItems: "center", borderRadius: 25, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 20 }, qrTitle: { marginTop: 15, color: HOBEE.colors.ink, fontSize: 21, fontWeight: "900", textAlign: "center" }, qrDescription: { marginTop: 8, color: HOBEE.colors.muted, fontSize: 13, lineHeight: 19, textAlign: "center" }, qrImage: { width: 250, height: 250, marginTop: 19, borderRadius: 18, backgroundColor: "#FFFFFF" }, qrPlaceholder: { width: 250, height: 250, alignItems: "center", justifyContent: "center", marginTop: 19, borderRadius: 18, backgroundColor: HOBEE.colors.canvas, padding: 18 }, qrHint: { marginTop: 7, color: HOBEE.colors.muted, fontSize: 11, textAlign: "center" }, awaiting: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 16, borderRadius: 15, backgroundColor: "#FFF1C8", paddingHorizontal: 12, paddingVertical: 9 }, awaitingText: { color: "#796123", fontSize: 11, fontWeight: "700" } });
