import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router as expoRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AtmosphericCanvas } from "@/components/hobee/layered-ui";
import { MyHobeeEmptyState, MyHobeeHeader, MyHobeeSegments, formatHobeeCount, formatHobeeCurrency } from "@/components/hobee/my-hobee-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useSupabaseAuth } from "@/contexts/supabase-auth-context";
import { useToast } from "@/contexts/toast-context";
import { getMyHobeeRoleDefinition, loadMyHobeeSnapshot, roleStatusLabel, type MyHobeeSnapshot } from "@/lib/my-hobee";
import { loadMyOrganizations, type MyHobeeOrganizationMembership } from "@/lib/my-hobee-phase2";

const router = expoRouter as { push: (href: string) => void; replace: (href: string) => void };

export default function MyHobeeOverviewScreen() {
  const { user } = useSupabaseAuth();
  const { showToast } = useToast();
  const [snapshot, setSnapshot] = useState<MyHobeeSnapshot | null>(null);
  const [organizations, setOrganizations] = useState<MyHobeeOrganizationMembership[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const displayName = typeof user?.user_metadata?.full_name === "string" ? user.user_metadata.full_name : typeof user?.user_metadata?.name === "string" ? user.user_metadata.name : "สมาชิก HOBEE";
  const initial = displayName.trim().charAt(0).toUpperCase() || "H";

  const load = useCallback(async (isRefresh = false) => {
    if (!user) { setSnapshot(null); setOrganizations([]); setLoading(false); setRefreshing(false); return; }
    isRefresh ? setRefreshing(true) : setLoading(true);
    try { const [nextSnapshot, nextOrganizations] = await Promise.all([loadMyHobeeSnapshot(user.id), loadMyOrganizations(user.id)]); setSnapshot(nextSnapshot); setOrganizations(nextOrganizations); }
    catch { showToast("ยังโหลดข้อมูล My HOBEE ไม่สำเร็จ กรุณาลองใหม่", "error"); }
    finally { setLoading(false); setRefreshing(false); }
  }, [showToast, user]);

  useEffect(() => { void load(); }, [load]);

  const activeRoles = useMemo(() => snapshot?.roles.filter((role) => role.status === "approved") ?? [], [snapshot]);
  const unread = snapshot?.customer.unreadWorkItems ?? 0;
  const canShowEarnings = Boolean(snapshot && (snapshot.earnings.paidOrderCount > 0 || snapshot.earnings.pendingOrderCount > 0));

  return <ScreenContainer containerClassName="bg-[#F6F3ED]" edges={["top", "left", "right"]}><AtmosphericCanvas mood="account"><View style={styles.topSurface}><View style={styles.auraOne} /><View style={styles.auraTwo} /><MyHobeeHeader notificationCount={unread} /><View style={styles.heroRow}><View style={styles.avatar}><Text style={styles.avatarText}>{initial}</Text></View><View style={styles.heroCopy}><Text numberOfLines={1} style={styles.name}>{displayName}</Text><Text style={styles.eyebrow}>PERSONAL COMMAND CENTER</Text><Text style={styles.intro}>รวมบทบาท งาน และกิจกรรมสำคัญของคุณไว้ที่เดียว</Text></View></View><MyHobeeSegments active="overview" /></View>
    {!user ? <View style={styles.guest}><MyHobeeEmptyState icon="person-outline" title="เริ่มต้น My HOBEE ของคุณ" description="เข้าสู่ระบบเพื่อดูบทบาท งาน รายได้ และกิจกรรมที่เชื่อมกับบัญชีของคุณ" actionLabel="เข้าสู่ระบบ" onAction={() => router.push("/auth")} /></View> : <ScrollView showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={HOBEE.colors.goldDark} />} contentContainerStyle={styles.content}>
      {loading && !snapshot ? <View style={styles.loading}><ActivityIndicator color={HOBEE.colors.goldDark} /><Text style={styles.loadingText}>กำลังเตรียม My HOBEE ของคุณ</Text></View> : null}
      {snapshot ? <>
        <SectionTitle eyebrow="TODAY" title="ภาพรวมวันนี้" />
        <View style={styles.todayCard}><TodayCell icon="assignment" value={formatHobeeCount(snapshot.customer.activeCustomerOrders)} label="ออเดอร์กำลังดำเนินการ" onPress={() => router.push("/orders?status=processing")} /><View style={styles.divider} /><TodayCell icon="notifications-active" value={formatHobeeCount(snapshot.customer.unreadWorkItems)} label="งานที่ยังไม่อ่าน" onPress={() => router.push("/my-hobee/work")} /><View style={styles.divider} /><TodayCell icon="card-giftcard" value={formatHobeeCount(snapshot.customer.activeCoupons)} label="สิทธิ์พร้อมใช้" onPress={() => router.push("/rewards")} /></View>

        <View style={styles.sectionSpacing}><SectionTitle eyebrow="MY ROLES" title="บทบาทของฉัน" action="ดูทั้งหมด" onAction={() => router.push("/my-hobee/roles")} /></View>
        {snapshot.roles.length ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.roleRail}>{snapshot.roles.map((role) => { const definition = getMyHobeeRoleDefinition(role.role_type); return <Pressable key={role.id} onPress={() => router.push("/my-hobee/roles")} style={({ pressed }) => [styles.roleCard, pressed && styles.pressed]}><View style={[styles.roleIcon, { backgroundColor: definition?.color ?? HOBEE.colors.darkBase }]}><MaterialIcons name={(definition?.icon ?? "person") as keyof typeof MaterialIcons.glyphMap} size={21} color="#FFFFFF" /></View><Text numberOfLines={1} style={styles.roleLabel}>{definition?.shortLabel ?? role.role_type}</Text><View style={[styles.roleState, role.status === "approved" ? styles.roleStateApproved : styles.roleStatePending]}><Text style={[styles.roleStateText, role.status === "approved" ? styles.roleStateTextApproved : styles.roleStateTextPending]}>{roleStatusLabel(role.status)}</Text></View></Pressable>; })}</ScrollView> : <MyHobeeEmptyState icon="grid-view" title="ยังไม่มีบทบาทเพิ่มเติม" description="คุณเริ่มจากบทบาทที่เหมาะกับสิ่งที่อยากสร้างหรือให้บริการได้" actionLabel="สำรวจบทบาท" onAction={() => router.push("/my-hobee/roles")} />}

        <View style={styles.sectionSpacing}><SectionTitle eyebrow="EARNINGS" title="รายได้และความเคลื่อนไหว" action={canShowEarnings ? "ดูงาน" : undefined} onAction={canShowEarnings ? () => router.push("/my-hobee/work") : undefined} /></View>
        {canShowEarnings ? <View style={styles.earningsCard}><View style={styles.earningsAura} /><View><Text style={styles.earningsLabel}>รายได้ที่ชำระแล้วเดือนนี้</Text><Text style={styles.earningsValue}>{formatHobeeCurrency(snapshot.earnings.paidAmount)}</Text><Text style={styles.earningsMeta}>จาก {formatHobeeCount(snapshot.earnings.paidOrderCount)} ออเดอร์ของร้านคุณ</Text></View><View style={styles.earningsSide}><View style={styles.earningsIcon}><MaterialIcons name="account-balance-wallet" size={26} color={HOBEE.colors.goldDark} /></View><Text style={styles.earningsPending}>{snapshot.earnings.pendingOrderCount ? `รอติดตาม ${formatHobeeCurrency(snapshot.earnings.pendingAmount)}` : "พร้อมดูแลต่อ"}</Text></View></View> : <View style={styles.emptyEarnings}><View style={styles.emptyEarningsIcon}><MaterialIcons name="show-chart" size={22} color={HOBEE.colors.travelTeal} /></View><View style={styles.emptyEarningsCopy}><Text style={styles.emptyEarningsTitle}>รายได้จะปรากฏเมื่อมีรายการจริง</Text><Text style={styles.emptyEarningsText}>ยังไม่มีรายการจากร้านหรือบทบาทที่เชื่อมรายได้ในรอบเดือนนี้</Text></View></View>}

        <View style={styles.sectionSpacing}><SectionTitle eyebrow="WORKSPACE" title="การเข้าถึงของคุณ" /></View>
        <View style={styles.accessCard}><AccessRow icon="storefront" title="องค์กรและกิจการ" detail={organizations.length ? `${formatHobeeCount(organizations.length)} องค์กรที่คุณมีสิทธิ์เข้าถึง` : snapshot.ownedShopCount ? `${formatHobeeCount(snapshot.ownedShopCount)} ร้านที่เชื่อมกับบัญชี` : "ยังไม่มีองค์กรที่เชื่อมกับบัญชี"} onPress={() => router.push("/my-hobee/roles")} />{organizations.length ? <OrganizationStrip organizations={organizations} /> : null}<View style={styles.accessLine} /><AccessRow icon="favorite-border" title="รายการที่บันทึก" detail={`${formatHobeeCount(snapshot.customer.favoriteCount)} รายการจากบัญชีของคุณ`} onPress={() => router.push("/favorites")} /><View style={styles.accessLine} /><AccessRow icon="work-outline" title="Work Inbox" detail={unread ? `${formatHobeeCount(unread)} รายการรอคุณอยู่` : "ยังไม่มีงานที่รอดำเนินการ"} onPress={() => router.push("/my-hobee/work")} /></View>

        {activeRoles.some((role) => role.role_type === "admin") ? <Pressable onPress={() => router.push("/admin")} style={({ pressed }) => [styles.adminEntry, pressed && styles.pressed]}><MaterialIcons name="admin-panel-settings" size={22} color="#FFFFFF" /><View style={styles.adminCopy}><Text style={styles.adminTitle}>HOBEE Admin Center</Text><Text style={styles.adminText}>เข้าสู่ศูนย์ควบคุมหลังบ้านสำหรับผู้มีสิทธิ์</Text></View><MaterialIcons name="arrow-forward" size={20} color="#FFFFFF" /></Pressable> : null}
      </> : null}
    </ScrollView>}</AtmosphericCanvas></ScreenContainer>;
}

function SectionTitle({ eyebrow, title, action, onAction }: { eyebrow: string; title: string; action?: string; onAction?: () => void }) { return <View style={styles.sectionTitleRow}><View><Text style={styles.sectionEyebrow}>{eyebrow}</Text><Text style={styles.sectionTitle}>{title}</Text></View>{action && onAction ? <Pressable onPress={onAction} style={({ pressed }) => [styles.sectionAction, pressed && styles.pressed]}><Text style={styles.sectionActionText}>{action}</Text><MaterialIcons name="chevron-right" size={19} color={HOBEE.colors.muted} /></Pressable> : null}</View>; }
function TodayCell({ icon, value, label, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; value: string; label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.todayCell, pressed && styles.pressed]}><View style={styles.todayIcon}><MaterialIcons name={icon} size={18} color={HOBEE.colors.travelTeal} /></View><Text style={styles.todayValue}>{value}</Text><Text numberOfLines={2} style={styles.todayLabel}>{label}</Text></Pressable>; }
function AccessRow({ icon, title, detail, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; detail: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.accessRow, pressed && styles.pressed]}><View style={styles.accessIcon}><MaterialIcons name={icon} size={21} color={HOBEE.colors.ink} /></View><View style={styles.accessCopy}><Text style={styles.accessTitle}>{title}</Text><Text numberOfLines={1} style={styles.accessDetail}>{detail}</Text></View><MaterialIcons name="chevron-right" size={22} color={HOBEE.colors.muted} /></Pressable>; }
function OrganizationStrip({ organizations }: { organizations: MyHobeeOrganizationMembership[] }) { return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.organizationRail}>{organizations.map((membership) => <View key={membership.id} style={styles.organizationChip}><MaterialIcons name={membership.organizations?.organization_type === "hotel" ? "hotel" : membership.organizations?.organization_type === "tour_company" ? "travel-explore" : "business"} size={14} color={HOBEE.colors.travelTeal} /><Text numberOfLines={1} style={styles.organizationChipText}>{membership.organizations?.name ?? "องค์กร HOBEE"}</Text><Text style={styles.organizationRole}>{membership.member_role}</Text></View>)}</ScrollView>; }

const styles = StyleSheet.create({
  topSurface: { position: "relative", overflow: "hidden", minHeight: 213, paddingBottom: 16, backgroundColor: HOBEE.colors.darkBase, ...HOBEE.elevation.featured }, auraOne: { position: "absolute", width: 280, height: 280, right: -125, top: -150, borderRadius: 150, backgroundColor: HOBEE.colors.gold, opacity: 0.30 }, auraTwo: { position: "absolute", width: 210, height: 210, left: -112, bottom: -156, borderRadius: 120, backgroundColor: HOBEE.colors.travelTeal, opacity: 0.42 },
  heroRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: HOBEE.space.page, paddingVertical: 12 }, avatar: { width: 58, height: 58, alignItems: "center", justifyContent: "center", borderRadius: 29, borderWidth: 2, borderColor: "rgba(255,255,255,0.9)", backgroundColor: HOBEE.colors.travelTeal }, avatarText: { color: "#FFFFFF", fontSize: 23, fontWeight: "900" }, heroCopy: { flex: 1 }, name: { color: "#FFFFFF", fontSize: 21, fontWeight: "900" }, eyebrow: { marginTop: 1, color: "#E9DCA9", fontSize: 9, fontWeight: "900", letterSpacing: 0.9 }, intro: { marginTop: 3, color: "rgba(255,255,255,0.78)", fontSize: 11, fontWeight: "600" },
  guest: { flex: 1, justifyContent: "center", padding: HOBEE.space.page }, content: { gap: 16, paddingHorizontal: HOBEE.space.page, paddingTop: 22, paddingBottom: 160 }, loading: { alignItems: "center", gap: 11, paddingVertical: 40 }, loadingText: { color: HOBEE.colors.muted, fontSize: 13, fontWeight: "700" },
  sectionTitleRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between" }, sectionEyebrow: { color: HOBEE.colors.goldDark, fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, sectionTitle: { marginTop: 2, color: HOBEE.colors.ink, fontSize: 20, fontWeight: "900" }, sectionAction: { flexDirection: "row", alignItems: "center" }, sectionActionText: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "800" }, sectionSpacing: { marginTop: 6 },
  todayCard: { flexDirection: "row", alignItems: "stretch", borderRadius: HOBEE.radius.hero, backgroundColor: HOBEE.overlay.glass, paddingVertical: 13, ...HOBEE.elevation.card }, todayCell: { flex: 1, alignItems: "center", paddingHorizontal: 5 }, divider: { width: 1, marginVertical: 8, backgroundColor: HOBEE.colors.border }, todayIcon: { width: 34, height: 34, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: HOBEE.atmosphere.botanicalMist }, todayValue: { marginTop: 5, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, todayLabel: { marginTop: 2, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", lineHeight: 13, textAlign: "center" },
  roleRail: { gap: 10, paddingRight: HOBEE.space.page }, roleCard: { width: 116, borderRadius: 20, backgroundColor: HOBEE.overlay.glass, padding: 12, ...HOBEE.elevation.card }, roleIcon: { width: 39, height: 39, alignItems: "center", justifyContent: "center", borderRadius: 14 }, roleLabel: { marginTop: 11, color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, roleState: { alignSelf: "flex-start", marginTop: 6, borderRadius: 8, paddingHorizontal: 6, paddingVertical: 3 }, roleStateApproved: { backgroundColor: "#DFF3EA" }, roleStatePending: { backgroundColor: HOBEE.atmosphere.warmCream }, roleStateText: { fontSize: 9, fontWeight: "900" }, roleStateTextApproved: { color: "#1B745B" }, roleStateTextPending: { color: HOBEE.colors.goldDark },
  earningsCard: { position: "relative", overflow: "hidden", flexDirection: "row", alignItems: "center", justifyContent: "space-between", minHeight: 134, borderRadius: HOBEE.radius.hero, backgroundColor: HOBEE.colors.darkBase, padding: 18, ...HOBEE.elevation.featured }, earningsAura: { position: "absolute", width: 185, height: 185, right: -70, top: -74, borderRadius: 100, backgroundColor: HOBEE.colors.gold, opacity: 0.32 }, earningsLabel: { color: "#E9DCA9", fontSize: 11, fontWeight: "800" }, earningsValue: { marginTop: 3, color: "#FFFFFF", fontSize: 27, fontWeight: "900" }, earningsMeta: { marginTop: 5, color: "rgba(255,255,255,0.72)", fontSize: 11, fontWeight: "600" }, earningsSide: { zIndex: 1, alignItems: "flex-end", maxWidth: 108 }, earningsIcon: { width: 46, height: 46, alignItems: "center", justifyContent: "center", borderRadius: 17, backgroundColor: "rgba(255,255,255,0.92)" }, earningsPending: { marginTop: 8, color: "#FFFFFF", fontSize: 10, fontWeight: "800", textAlign: "right" },
  emptyEarnings: { flexDirection: "row", alignItems: "center", gap: 12, borderRadius: HOBEE.radius.card, backgroundColor: "#EAF7F0", padding: 15, ...HOBEE.elevation.surface }, emptyEarningsIcon: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#D4EEE4" }, emptyEarningsCopy: { flex: 1 }, emptyEarningsTitle: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" }, emptyEarningsText: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600", lineHeight: 16 },
  accessCard: { overflow: "hidden", borderRadius: HOBEE.radius.hero, backgroundColor: HOBEE.overlay.glass, ...HOBEE.elevation.card }, accessRow: { flexDirection: "row", alignItems: "center", gap: 11, minHeight: 66, paddingHorizontal: 15 }, accessIcon: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: HOBEE.atmosphere.warmCream }, accessCopy: { flex: 1 }, accessTitle: { color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900" }, accessDetail: { marginTop: 2, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600" }, accessLine: { height: 1, marginLeft: 66, backgroundColor: HOBEE.colors.border }, organizationRail: { gap: 7, paddingHorizontal: 15, paddingBottom: 13 }, organizationChip: { maxWidth: 182, flexDirection: "row", alignItems: "center", gap: 5, borderRadius: 9, backgroundColor: "#EAF5EF", paddingHorizontal: 8, paddingVertical: 6 }, organizationChipText: { maxWidth: 100, color: HOBEE.colors.ink, fontSize: 10, fontWeight: "800" }, organizationRole: { color: HOBEE.colors.travelTeal, fontSize: 9, fontWeight: "900", textTransform: "uppercase" },
  adminEntry: { flexDirection: "row", alignItems: "center", gap: 11, borderRadius: HOBEE.radius.card, backgroundColor: "#313D5A", padding: 15, ...HOBEE.elevation.card }, adminCopy: { flex: 1 }, adminTitle: { color: "#FFFFFF", fontSize: 15, fontWeight: "900" }, adminText: { marginTop: 2, color: "#D7E0F8", fontSize: 11, fontWeight: "600" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] },
});
