import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router as expoRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AtmosphericCanvas } from "@/components/hobee/layered-ui";
import { MyHobeeEmptyState, MyHobeeHeader } from "@/components/hobee/my-hobee-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useSupabaseAuth } from "@/contexts/supabase-auth-context";
import { useToast } from "@/contexts/toast-context";
import { isHobeeNotificationRoute } from "@/lib/deep-links";
import { loadMyNotifications, markMyHobeeNotificationRead, type MyHobeeNotification } from "@/lib/my-hobee-phase2";

const router = expoRouter as { push: (href: string) => void; replace: (href: string) => void };

export default function MyHobeeNotificationsScreen() {
  const { user } = useSupabaseAuth(); const { showToast } = useToast();
  const [items, setItems] = useState<MyHobeeNotification[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [updatingId, setUpdatingId] = useState<string | null>(null);
  const load = useCallback(async (isRefresh = false) => { if (!user) { setItems([]); setLoading(false); return; } isRefresh ? setRefreshing(true) : setLoading(true); try { setItems(await loadMyNotifications(user.id)); } catch { showToast("ยังโหลดการแจ้งเตือนไม่สำเร็จ", "error"); } finally { setLoading(false); setRefreshing(false); } }, [showToast, user]);
  useEffect(() => { void load(); }, [load]);
  const unread = useMemo(() => items.filter((item) => !item.is_read).length, [items]);
  const open = async (item: MyHobeeNotification) => { if (updatingId) return; setUpdatingId(item.id); try { if (!item.is_read) { await markMyHobeeNotificationRead(item.id); setItems((current) => current.map((candidate) => candidate.id === item.id ? { ...candidate, is_read: true } : candidate)); } if (isHobeeNotificationRoute(item.route)) router.push(item.route); } catch { showToast("ไม่สามารถเปิดการแจ้งเตือนได้", "error"); } finally { setUpdatingId(null); } };
  return <ScreenContainer containerClassName="bg-[#F6F3ED]" edges={["top", "left", "right"]}><AtmosphericCanvas mood="account"><View style={styles.top}><MyHobeeHeader title="NOTIFICATIONS" onBack={() => router.replace("/my-hobee")} notificationCount={unread} /><Text style={styles.title}>การแจ้งเตือน</Text><Text style={styles.subtitle}>อัปเดตที่เกี่ยวข้องกับบทบาท งาน ออเดอร์ การจอง และรายได้ของคุณ</Text><Pressable onPress={() => router.push("/my-hobee/notification-preferences")} style={({ pressed }) => [styles.preference, pressed && styles.pressed]}><MaterialIcons name="tune" size={16} color="#FFFFFF" /><Text style={styles.preferenceText}>ตั้งค่าการแจ้งเตือน</Text></Pressable></View>{!user ? <View style={styles.guest}><MyHobeeEmptyState icon="lock-outline" title="เข้าสู่ระบบเพื่อดูการแจ้งเตือน" description="รายการที่เชื่อมกับบัญชีของคุณจะแสดงที่นี่" actionLabel="เข้าสู่ระบบ" onAction={() => router.push("/auth")} /></View> : <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={HOBEE.colors.goldDark} />} contentContainerStyle={styles.content}>{loading ? <View style={styles.loading}><ActivityIndicator color={HOBEE.colors.goldDark} /></View> : items.length ? items.map((item) => <Pressable key={item.id} onPress={() => void open(item)} style={({ pressed }) => [styles.card, !item.is_read && styles.cardUnread, pressed && styles.pressed]}><View style={[styles.icon, item.notification_type.includes("ROLE") ? styles.iconGold : item.notification_type.includes("EARNING") ? styles.iconGreen : styles.iconTeal]}>{updatingId === item.id ? <ActivityIndicator size="small" color={HOBEE.colors.goldDark} /> : <MaterialIcons name={item.notification_type.includes("ROLE") ? "verified" : item.notification_type.includes("BOOKING") ? "event-available" : item.notification_type.includes("EARNING") ? "account-balance-wallet" : item.notification_type.includes("CASE") ? "support-agent" : "inventory-2"} size={20} color={HOBEE.colors.ink} />}</View><View style={styles.copy}><View style={styles.titleRow}><Text numberOfLines={1} style={styles.cardTitle}>{item.title}</Text>{!item.is_read ? <View style={styles.dot} /> : null}</View><Text numberOfLines={2} style={styles.body}>{item.body ?? "มีการอัปเดตใหม่"}</Text><Text style={styles.date}>{formatDate(item.created_at)}</Text></View><MaterialIcons name="chevron-right" size={21} color={HOBEE.colors.muted} /></Pressable>) : <MyHobeeEmptyState icon="notifications-none" title="ยังไม่มีการแจ้งเตือน" description="เมื่อบทบาท งาน ออเดอร์ หรือรายได้ของคุณมีการอัปเดต จะแสดงที่นี่" />}</ScrollView>}</AtmosphericCanvas></ScreenContainer>;
}
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : new Intl.DateTimeFormat("th-TH", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }).format(date); }
const styles = StyleSheet.create({ top: { overflow: "hidden", paddingBottom: 20, backgroundColor: HOBEE.colors.darkBase, ...HOBEE.elevation.featured }, title: { marginTop: 12, paddingHorizontal: HOBEE.space.page, color: "#FFFFFF", fontSize: 23, fontWeight: "900" }, subtitle: { marginTop: 5, paddingHorizontal: HOBEE.space.page, color: "rgba(255,255,255,0.74)", fontSize: 12, fontWeight: "600", lineHeight: 18 }, preference: { flexDirection: "row", alignItems: "center", alignSelf: "flex-start", gap: 6, marginTop: 12, marginLeft: HOBEE.space.page, borderRadius: 10, backgroundColor: "rgba(255,255,255,0.14)", paddingHorizontal: 10, paddingVertical: 8 }, preferenceText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" }, guest: { flex: 1, justifyContent: "center", padding: HOBEE.space.page }, content: { gap: 9, padding: HOBEE.space.page, paddingBottom: 160 }, loading: { alignItems: "center", paddingVertical: 45 }, card: { flexDirection: "row", alignItems: "center", gap: 11, borderRadius: HOBEE.radius.card, backgroundColor: "rgba(255,255,255,0.72)", padding: 13 }, cardUnread: { backgroundColor: HOBEE.overlay.glass, ...HOBEE.elevation.card }, icon: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 14 }, iconGold: { backgroundColor: "#FDECCB" }, iconGreen: { backgroundColor: "#DFF3EA" }, iconTeal: { backgroundColor: "#E4F2EE" }, copy: { flex: 1 }, titleRow: { flexDirection: "row", alignItems: "center", gap: 6 }, cardTitle: { flexShrink: 1, color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: HOBEE.colors.gold }, body: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600", lineHeight: 16 }, date: { marginTop: 5, color: HOBEE.colors.goldDark, fontSize: 9, fontWeight: "800" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
