import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router as expoRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AtmosphericCanvas } from "@/components/hobee/layered-ui";
import { MyHobeeEmptyState, MyHobeeHeader } from "@/components/hobee/my-hobee-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useSupabaseAuth } from "@/contexts/supabase-auth-context";
import { useToast } from "@/contexts/toast-context";
import { listNotificationPreferences, saveNotificationPreference } from "@/lib/after-sales";

const router = expoRouter as { push: (href: string) => void; replace: (href: string) => void };
const categories = [
  { key: "claims", icon: "support-agent" as const, title: "เคสหลังการขาย", description: "การอนุมัติ เคส ข้อมูลเพิ่มเติม Return และ Replacement" },
  { key: "orders", icon: "inventory-2" as const, title: "คำสั่งซื้อ", description: "สถานะออเดอร์และการดำเนินการของผู้ขาย" },
  { key: "shipping", icon: "local-shipping" as const, title: "การจัดส่ง", description: "Tracking, ถึงปลายทาง และการรับสินค้า" },
  { key: "payments", icon: "account-balance-wallet" as const, title: "การชำระเงิน", description: "การยืนยันและสถานะการชำระเงิน" },
  { key: "work", icon: "assignment" as const, title: "งานและบทบาท", description: "Work Inbox, การมอบหมายงาน และการอนุมัติบทบาท" },
  { key: "earnings", icon: "trending-up" as const, title: "รายได้", description: "การเปลี่ยนแปลงรายได้ที่บันทึกในระบบ" },
];
type Preference = { inApp: boolean; push: boolean };

export default function NotificationPreferencesScreen() {
  const { user } = useSupabaseAuth(); const { showToast } = useToast();
  const [values, setValues] = useState<Record<string, Preference>>({}); const [loading, setLoading] = useState(true); const [savingKey, setSavingKey] = useState<string | null>(null);
  const load = useCallback(async () => { if (!user) { setLoading(false); return; } setLoading(true); try { const rows = await listNotificationPreferences(); setValues(Object.fromEntries(rows.map((row) => [row.category, { inApp: row.in_app_enabled, push: row.push_enabled }]))); } catch { showToast("โหลดการตั้งค่าการแจ้งเตือนไม่สำเร็จ", "error"); } finally { setLoading(false); } }, [showToast, user]);
  useEffect(() => { void load(); }, [load]);
  const current = useMemo(() => (key: string) => values[key] ?? { inApp: true, push: true }, [values]);
  const update = async (key: string, patch: Partial<Preference>) => { const before = current(key); const next = { ...before, ...patch }; setValues((state) => ({ ...state, [key]: next })); setSavingKey(key); try { await saveNotificationPreference({ category: key, inAppEnabled: next.inApp, pushEnabled: next.push }); } catch { setValues((state) => ({ ...state, [key]: before })); showToast("บันทึกการตั้งค่าไม่สำเร็จ", "error"); } finally { setSavingKey(null); } };
  return <ScreenContainer containerClassName="bg-[#F6F3ED]" edges={["top", "left", "right"]}><AtmosphericCanvas mood="account"><View style={styles.top}><MyHobeeHeader title="NOTIFICATION SETTINGS" onBack={() => router.replace("/my-hobee/notifications")} /><Text style={styles.title}>การตั้งค่าการแจ้งเตือน</Text><Text style={styles.subtitle}>เลือกประเภทการอัปเดตที่ต้องการเห็นในแอปหรือรับเป็น push notification</Text></View>{!user ? <View style={styles.guest}><MyHobeeEmptyState icon="lock-outline" title="เข้าสู่ระบบก่อนจัดการการแจ้งเตือน" description="การตั้งค่าจะผูกกับบัญชี HOBEE ของคุณ" actionLabel="เข้าสู่ระบบ" onAction={() => router.push("/auth")} /></View> : <ScrollView contentContainerStyle={styles.content}>{loading ? <View style={styles.loading}><ActivityIndicator color={HOBEE.colors.goldDark} /></View> : <><View style={styles.info}><MaterialIcons name="info-outline" size={20} color={HOBEE.colors.travelTeal} /><Text style={styles.infoText}>การแจ้งเตือนสำคัญ เช่น การตัดสินเคสหรือสถานะการเงิน อาจยังปรากฏเพื่อความปลอดภัยของรายการ</Text></View>{categories.map((item) => { const value = current(item.key); const saving = savingKey === item.key; return <View key={item.key} style={styles.card}><View style={styles.cardHeader}><View style={styles.icon}><MaterialIcons name={item.icon} size={20} color={HOBEE.colors.ink} /></View><View style={styles.copy}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardDescription}>{item.description}</Text></View>{saving ? <ActivityIndicator size="small" color={HOBEE.colors.goldDark} /> : null}</View><View style={styles.option}><View><Text style={styles.optionTitle}>แจ้งเตือนในแอป</Text><Text style={styles.optionSub}>แสดงใน Notification Center</Text></View><Switch value={value.inApp} onValueChange={(next) => void update(item.key, { inApp: next })} trackColor={{ false: "#D9DDD9", true: "#A9D2C5" }} thumbColor={value.inApp ? HOBEE.colors.travelTeal : "#FFFFFF"} /></View><View style={styles.divider} /><View style={styles.option}><View><Text style={styles.optionTitle}>Push notification</Text><Text style={styles.optionSub}>แจ้งที่อุปกรณ์เมื่อเปิดการส่งจากระบบ</Text></View><Switch value={value.push} onValueChange={(next) => void update(item.key, { push: next })} trackColor={{ false: "#D9DDD9", true: "#F0C96D" }} thumbColor={value.push ? HOBEE.colors.goldDark : "#FFFFFF"} /></View></View>; })}</>}</ScrollView>}</AtmosphericCanvas></ScreenContainer>;
}
const styles = StyleSheet.create({ top: { overflow: "hidden", paddingBottom: 20, backgroundColor: HOBEE.colors.darkBase, ...HOBEE.elevation.featured }, title: { marginTop: 12, paddingHorizontal: HOBEE.space.page, color: "#FFFFFF", fontSize: 22, fontWeight: "900" }, subtitle: { marginTop: 5, paddingHorizontal: HOBEE.space.page, color: "rgba(255,255,255,0.74)", fontSize: 12, fontWeight: "600", lineHeight: 18 }, guest: { flex: 1, justifyContent: "center", padding: HOBEE.space.page }, content: { gap: 11, padding: HOBEE.space.page, paddingBottom: 150 }, loading: { alignItems: "center", paddingVertical: 50 }, info: { flexDirection: "row", gap: 10, borderRadius: 16, backgroundColor: "#E5F3EF", padding: 13 }, infoText: { flex: 1, color: HOBEE.colors.travelTeal, fontSize: 11, fontWeight: "700", lineHeight: 16 }, card: { borderRadius: HOBEE.radius.card, backgroundColor: "rgba(255,255,255,0.83)", padding: 14, ...HOBEE.elevation.card }, cardHeader: { flexDirection: "row", alignItems: "center", gap: 10, paddingBottom: 12 }, icon: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: "#F5E5B8" }, copy: { flex: 1 }, cardTitle: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" }, cardDescription: { marginTop: 2, color: HOBEE.colors.muted, fontSize: 10, lineHeight: 14, fontWeight: "600" }, option: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, paddingVertical: 9 }, optionTitle: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "800" }, optionSub: { marginTop: 2, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "600" }, divider: { height: 1, backgroundColor: "#EDF0ED" } });
