import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router as expoRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AtmosphericCanvas } from "@/components/hobee/layered-ui";
import { MyHobeeHeader, MyHobeeSegments } from "@/components/hobee/my-hobee-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useSupabaseAuth } from "@/contexts/supabase-auth-context";
import { useToast } from "@/contexts/toast-context";
import { MY_HOBEE_ROLE_DEFINITIONS, applyForMyHobeeRole, getMyHobeeRoleDefinition, loadMyRoles, roleStatusLabel, type MyHobeeRole, type MyHobeeRoleType } from "@/lib/my-hobee";

const router = expoRouter as { push: (href: string) => void; replace: (href: string) => void };

export default function MyHobeeRolesScreen() {
  const { user } = useSupabaseAuth();
  const { showToast } = useToast();
  const [roles, setRoles] = useState<MyHobeeRole[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [submittingRole, setSubmittingRole] = useState<MyHobeeRoleType | null>(null);
  const load = useCallback(async (isRefresh = false) => { if (!user) { setRoles([]); setLoading(false); return; } isRefresh ? setRefreshing(true) : setLoading(true); try { setRoles(await loadMyRoles(user.id)); } catch { showToast("ยังโหลดบทบาทของคุณไม่สำเร็จ", "error"); } finally { setLoading(false); setRefreshing(false); } }, [showToast, user]);
  useEffect(() => { void load(); }, [load]);
  const rolesByType = useMemo(() => new Map(roles.map((role) => [role.role_type, role])), [roles]);
  const requestRole = (roleType: MyHobeeRoleType) => { if (!user) { router.push("/auth"); return; } const role = getMyHobeeRoleDefinition(roleType); Alert.alert(`สมัคร ${role?.label ?? roleType}`, "คำขอจะถูกส่งไปพิจารณา ก่อนเปิดใช้เครื่องมือของบทบาทนี้", [{ text: "ยกเลิก", style: "cancel" }, { text: "ส่งคำขอ", onPress: () => { void (async () => { setSubmittingRole(roleType); try { await applyForMyHobeeRole(roleType); showToast("ส่งคำขอเข้าร่วมบทบาทแล้ว", "success"); await load(); } catch { showToast("ส่งคำขอไม่สำเร็จ กรุณาลองใหม่", "error"); } finally { setSubmittingRole(null); } })(); } }]); };

  return <ScreenContainer containerClassName="bg-[#F6F3ED]" edges={["top", "left", "right"]}><AtmosphericCanvas mood="account"><View style={styles.top}><MyHobeeHeader title="ROLE MARKETPLACE" onBack={() => router.replace("/my-hobee")} /><Text style={styles.title}>เลือกบทบาทที่สร้างคุณค่าให้คุณ</Text><Text style={styles.subtitle}>เริ่มจากบทบาทที่สอดคล้องกับสิ่งที่คุณทำในชุมชน HOBEE คุณเพิ่มได้มากกว่าหนึ่งบทบาท</Text><MyHobeeSegments active="roles" /></View><ScrollView showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={HOBEE.colors.goldDark} />} contentContainerStyle={styles.content}>{loading ? <View style={styles.loading}><ActivityIndicator color={HOBEE.colors.goldDark} /></View> : MY_HOBEE_ROLE_DEFINITIONS.map((definition) => { const current = rolesByType.get(definition.roleType); const active = current?.status === "approved"; const pending = current && !active; return <View key={definition.roleType} style={styles.roleCard}><View style={[styles.roleIcon, { backgroundColor: definition.color }]}><MaterialIcons name={definition.icon as keyof typeof MaterialIcons.glyphMap} size={24} color="#FFFFFF" /></View><View style={styles.roleCopy}><Text style={styles.roleTitle}>{definition.label}</Text><Text style={styles.roleDescription}>{definition.description}</Text>{current ? <View style={[styles.status, active ? styles.statusActive : styles.statusPending]}><MaterialIcons name={active ? "check-circle" : "schedule"} size={13} color={active ? HOBEE.colors.success : HOBEE.colors.goldDark} /><Text style={[styles.statusText, active ? styles.statusTextActive : styles.statusTextPending]}>{roleStatusLabel(current.status)}</Text></View> : null}</View>{current ? <Pressable onPress={() => undefined} style={styles.disabledAction}><Text style={styles.disabledActionText}>{active ? "ใช้งานแล้ว" : roleStatusLabel(current.status)}</Text></Pressable> : <Pressable disabled={submittingRole === definition.roleType} onPress={() => requestRole(definition.roleType)} style={({ pressed }) => [styles.applyAction, submittingRole === definition.roleType && styles.actionLoading, pressed && styles.pressed]}>{submittingRole === definition.roleType ? <ActivityIndicator size="small" color={HOBEE.colors.ink} /> : <><Text style={styles.applyActionText}>สมัคร</Text><MaterialIcons name="arrow-forward" size={15} color={HOBEE.colors.ink} /></>}</Pressable>}</View>; })}</ScrollView></AtmosphericCanvas></ScreenContainer>;
}

const styles = StyleSheet.create({ top: { overflow: "hidden", paddingBottom: 17, backgroundColor: HOBEE.colors.darkBase, ...HOBEE.elevation.featured }, title: { marginTop: 12, paddingHorizontal: HOBEE.space.page, color: "#FFFFFF", fontSize: 23, fontWeight: "900" }, subtitle: { marginTop: 5, paddingHorizontal: HOBEE.space.page, color: "rgba(255,255,255,0.74)", fontSize: 12, fontWeight: "600", lineHeight: 18 }, content: { gap: 11, padding: HOBEE.space.page, paddingBottom: 160 }, loading: { paddingVertical: 44, alignItems: "center" }, roleCard: { flexDirection: "row", alignItems: "center", gap: 11, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.overlay.glass, padding: 13, ...HOBEE.elevation.card }, roleIcon: { width: 46, height: 46, alignItems: "center", justifyContent: "center", borderRadius: 16 }, roleCopy: { flex: 1 }, roleTitle: { color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900" }, roleDescription: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "600", lineHeight: 14 }, status: { flexDirection: "row", alignItems: "center", alignSelf: "flex-start", gap: 4, marginTop: 6, borderRadius: 8, paddingHorizontal: 6, paddingVertical: 3 }, statusActive: { backgroundColor: "#DFF3EA" }, statusPending: { backgroundColor: HOBEE.atmosphere.warmCream }, statusText: { fontSize: 9, fontWeight: "900" }, statusTextActive: { color: "#1B745B" }, statusTextPending: { color: HOBEE.colors.goldDark }, applyAction: { flexDirection: "row", alignItems: "center", gap: 3, borderRadius: 11, backgroundColor: HOBEE.colors.gold, paddingHorizontal: 9, paddingVertical: 8 }, applyActionText: { color: HOBEE.colors.ink, fontSize: 11, fontWeight: "900" }, actionLoading: { minWidth: 52, alignItems: "center" }, disabledAction: { borderRadius: 11, backgroundColor: "#EFECE6", paddingHorizontal: 8, paddingVertical: 8 }, disabledActionText: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "800" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
