import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { COMMUNITY_REPORT_REASONS } from "@/lib/community-hub";

export default function CommunityModerationScreen() { return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.title}>Community Moderation</Text><View style={styles.back} /></View><View style={styles.hero}><MaterialIcons name="gavel" size={30} color={HOBEE.colors.goldDark} /><Text style={styles.heroTitle}>Moderation Center</Text><Text style={styles.heroText}>คิวรายงาน สิทธิ์ moderator และการระงับเนื้อหาจะแสดงเฉพาะผู้ที่ได้รับ role จริงเมื่อ Community operations source พร้อม</Text></View><Text style={styles.section}>เหตุผลการรายงานที่รองรับ</Text><View style={styles.reasons}>{COMMUNITY_REPORT_REASONS.map((item) => <View key={item.id} style={styles.reason}><MaterialIcons name="outlined-flag" size={16} color={HOBEE.colors.error} /><Text style={styles.reasonText}>{item.label}</Text></View>)}</View><View style={styles.notice}><MaterialIcons name="verified-user" size={18} color={HOBEE.colors.botanical} /><Text style={styles.noticeText}>ไม่มี action ที่เปลี่ยนสถานะสมาชิกหรือเนื้อหาจริงใน presentation workspace นี้</Text></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { gap: 14, padding: HOBEE.space.page, paddingBottom: 42 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, title: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, hero: { alignItems: "center", borderRadius: HOBEE.radius.hero, backgroundColor: HOBEE.atmosphere.warmCream, padding: 22 }, heroTitle: { color: HOBEE.colors.ink, fontSize: 20, fontWeight: "900", marginTop: 8 }, heroText: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 18, marginTop: 6, textAlign: "center" }, section: { color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900" }, reasons: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, reason: { flexDirection: "row", alignItems: "center", gap: 5, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 10, paddingVertical: 8, ...HOBEE.elevation.surface }, reasonText: { color: HOBEE.colors.ink, fontSize: 10, fontWeight: "800" }, notice: { flexDirection: "row", gap: 8, borderRadius: HOBEE.radius.medium, backgroundColor: HOBEE.atmosphere.botanicalMist, padding: 12 }, noticeText: { flex: 1, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700", lineHeight: 16 } });
