import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams, type Href } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { CommunityRecommendationCard } from "@/components/hobee/community-ui";
import { HOBEE } from "@/components/hobee/design-tokens";
import { GlobalErrorState, OfflineState } from "@/components/hobee/error-screens";
import { ScreenContainer } from "@/components/screen-container";
import { useCommunityPreferences } from "@/contexts/community-preferences-context";
import { COMMUNITY_TOPICS, findCommunitySearchResults } from "@/lib/community-hub";

export default function CommunitySearchScreen() {
  const { state } = useLocalSearchParams<{ state?: "offline" | "error" }>(); const [query, setQuery] = useState(""); const { recentSearches, addRecentSearch, clearRecentSearches } = useCommunityPreferences();
  const results = useMemo(() => findCommunitySearchResults(query), [query]);
  if (state === "offline") return <ScreenContainer edges={["top", "bottom", "left", "right"]}><OfflineState actionLabel="ลองใหม่" onAction={() => router.replace("/community/search" as Href)} /></ScreenContainer>;
  if (state === "error") return <ScreenContainer edges={["top", "bottom", "left", "right"]}><GlobalErrorState actionLabel="ลองใหม่" onAction={() => router.replace("/community/search" as Href)} /></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.top}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={23} color={HOBEE.colors.ink} /></Pressable><View style={styles.search}><MaterialIcons name="search" size={22} color={HOBEE.colors.muted} /><TextInput autoFocus value={query} onChangeText={setQuery} onSubmitEditing={() => addRecentSearch(query)} placeholder="ค้นหาเรื่องราว ชมรม กิจกรรม งาน หรือคน" placeholderTextColor={HOBEE.colors.muted} returnKeyType="search" style={styles.input} />{query ? <Pressable onPress={() => setQuery("")}><MaterialIcons name="close" size={20} color={HOBEE.colors.muted} /></Pressable> : null}</View></View><FlatList data={query ? results : []} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} renderItem={({ item }) => <CommunityRecommendationCard item={item} onPress={() => { addRecentSearch(query); router.push(item.route as Href); }} />} ListHeaderComponent={!query ? <SearchSuggestions recentSearches={recentSearches} onSelect={(value) => { setQuery(value); addRecentSearch(value); }} onClear={clearRecentSearches} /> : null} ListEmptyComponent={query ? <View style={styles.empty}><MaterialIcons name="search-off" size={34} color={HOBEE.colors.goldDark} /><Text style={styles.emptyTitle}>ไม่พบสิ่งที่ค้นหา</Text><Text style={styles.emptyText}>ลองค้นหาด้วยชื่อจังหวัด หัวข้อ หรือประเภทเนื้อหาอื่น</Text></View> : null} /></ScreenContainer>;
}
function SearchSuggestions({ recentSearches, onSelect, onClear }: { recentSearches: string[]; onSelect: (value: string) => void; onClear: () => void }) { return <View style={styles.suggestions}>{recentSearches.length ? <><View style={styles.heading}><Text style={styles.headingText}>ค้นหาล่าสุด</Text><Pressable onPress={onClear}><Text style={styles.clearText}>ล้าง</Text></Pressable></View><View style={styles.chips}>{recentSearches.map((item) => <Pressable key={item} onPress={() => onSelect(item)} style={styles.chip}><MaterialIcons name="history" size={15} color={HOBEE.colors.botanical} /><Text style={styles.chipText}>{item}</Text></Pressable>)}</View></> : null}<Text style={styles.topicTitle}>หัวข้อที่กำลังน่าสนใจ</Text><View style={styles.chips}>{COMMUNITY_TOPICS.map((topic) => <Pressable key={topic} onPress={() => onSelect(topic.replace("#", ""))} style={styles.topicChip}><Text style={styles.topicText}>{topic}</Text></Pressable>)}</View><Text style={styles.topicTitle}>ค้นหาได้จาก</Text><View style={styles.searchKinds}>{["Stories", "Clubs", "Activities", "Jobs", "People", "Creator", "Trips", "Topics"].map((item) => <View key={item} style={styles.kind}><Text style={styles.kindText}>{item}</Text></View>)}</View></View>; }
const styles = StyleSheet.create({ top: { flexDirection: "row", alignItems: "center", gap: 9, paddingHorizontal: HOBEE.space.page, paddingTop: 6, paddingBottom: 12 }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, search: { flex: 1, flexDirection: "row", alignItems: "center", gap: 9, minHeight: 50, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.atmosphere.warmCream, paddingHorizontal: 15 }, input: { flex: 1, color: HOBEE.colors.ink, fontSize: 14, fontWeight: "700" }, content: { paddingHorizontal: HOBEE.space.page, paddingBottom: 42 }, suggestions: { gap: 12, paddingTop: 8 }, heading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headingText: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, clearText: { color: HOBEE.colors.goldDark, fontSize: 12, fontWeight: "900" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { flexDirection: "row", alignItems: "center", gap: 5, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 11, paddingVertical: 8, ...HOBEE.elevation.surface }, chipText: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "800" }, topicTitle: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900", marginTop: 14 }, topicChip: { borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.atmosphere.peachMist, paddingHorizontal: 11, paddingVertical: 8 }, topicText: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "800" }, searchKinds: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, kind: { borderWidth: 1, borderColor: HOBEE.colors.border, borderRadius: HOBEE.radius.pill, paddingHorizontal: 11, paddingVertical: 8 }, kindText: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "800" }, empty: { alignItems: "center", paddingTop: 76 }, emptyTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900", marginTop: 12 }, emptyText: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", marginTop: 6, textAlign: "center" } });
