import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, type Href } from "expo-router";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { COMMUNITY_PEOPLE, COMMUNITY_TRIPS } from "@/lib/community-hub";

export default function CommunityTripsScreen() { return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><View style={styles.copy}><Text style={styles.eyebrow}>HOBEE COMMUNITY</Text><Text style={styles.title}>ทริปจากคนในชุมชน</Text></View><Pressable onPress={() => router.push("/travel/trip-builder" as Href)} style={styles.share}><MaterialIcons name="add" size={20} color={HOBEE.colors.ink} /></Pressable></View>{COMMUNITY_TRIPS.map((trip) => { const creator = COMMUNITY_PEOPLE.find((person) => person.id === trip.creatorId); return <View key={trip.id} style={styles.card}><Image source={{ uri: trip.cover }} style={styles.image} /><View style={styles.body}><Text style={styles.tripTitle}>{trip.title}</Text><Text style={styles.meta}>{trip.durationLabel} · {trip.budgetLabel}</Text>{creator ? <Pressable onPress={() => router.push(`/community/people/${creator.id}` as Href)} style={styles.creator}><Image source={{ uri: creator.avatar }} style={styles.avatar} /><Text style={styles.creatorText}>โดย {creator.name}</Text></Pressable> : null}<View style={styles.tags}>{trip.tags.map((tag) => <View key={tag} style={styles.tag}><Text style={styles.tagText}>{tag}</Text></View>)}</View><Pressable onPress={() => router.push(trip.route as Href)} style={styles.primary}><Text style={styles.primaryText}>เปิดใน Trip Builder</Text><MaterialIcons name="north-east" size={17} color={HOBEE.colors.ink} /></Pressable></View></View>; })}<View style={styles.notice}><MaterialIcons name="info-outline" size={17} color={HOBEE.colors.muted} /><Text style={styles.noticeText}>Community Trips อ้างอิง Trip Builder เดิม ไม่มีการสร้าง itinerary หรือ booking entity ซ้ำ</Text></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 42 }, header: { flexDirection: "row", alignItems: "center", gap: 11, padding: HOBEE.space.page }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, copy: { flex: 1 }, eyebrow: { color: HOBEE.colors.goldDark, fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, title: { color: HOBEE.colors.ink, fontSize: 20, fontWeight: "900", marginTop: 2 }, share: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.gold }, card: { overflow: "hidden", marginHorizontal: HOBEE.space.page, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.colors.surface, ...HOBEE.elevation.card }, image: { width: "100%", height: 210 }, body: { gap: 9, padding: 14 }, tripTitle: { color: HOBEE.colors.ink, fontSize: 19, fontWeight: "900" }, meta: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700" }, creator: { flexDirection: "row", alignItems: "center", gap: 7 }, avatar: { width: 26, height: 26, borderRadius: 13 }, creatorText: { color: HOBEE.colors.botanical, fontSize: 11, fontWeight: "900" }, tags: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, tag: { borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.atmosphere.skyMist, paddingHorizontal: 8, paddingVertical: 5 }, tagText: { color: HOBEE.colors.botanical, fontSize: 10, fontWeight: "900" }, primary: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 7, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.gold, paddingVertical: 11 }, primaryText: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "900" }, notice: { flexDirection: "row", gap: 7, marginHorizontal: HOBEE.space.page }, noticeText: { flex: 1, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", lineHeight: 15 } });
