import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { HOBEE } from "@/components/hobee/design-tokens";
import { BackHeader, InfoRow, OrderTimeline, StatusChip } from "@/components/hobee/commerce-ui";
import { ScreenContainer } from "@/components/screen-container";
import { shipmentTimelineLabel } from "@/lib/customer-journey";
import { getMyOrder, listOrderShipments, type HobeeOrder, type Shipment } from "@/lib/orders";

const timeline = ["label_created", "pickup_scheduled", "in_transit", "out_for_delivery", "delivered"];
export default function DeliveryDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [order, setOrder] = useState<HobeeOrder | null>(null); const [shipments, setShipments] = useState<Shipment[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([getMyOrder(id), listOrderShipments(id)]).then(([nextOrder, nextShipments]) => { setOrder(nextOrder); setShipments(nextShipments); }).catch((cause) => setError(cause instanceof Error ? cause.message : "ไม่สามารถอ่านข้อมูลจัดส่งได้")); }, [id]);
  const shipment = useMemo(() => shipments[0] ?? null, [shipments]);
  if (!order && !error) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="items-center justify-center"><ActivityIndicator size="large" color={HOBEE.colors.gold} /></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]" className="px-5" safeAreaClassName="pt-3"><BackHeader title="ติดตามพัสดุ" subtitle={order?.order_number ?? "คำสั่งซื้อ"} onBack={() => router.back()} />{error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text></View> : <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{shipment ? <><View style={styles.hero}><View><Text style={styles.heroLabel}>ผู้ให้บริการขนส่ง</Text><Text style={styles.provider}>{shipment.provider.toUpperCase()}</Text><Text style={styles.tracking}>{shipment.tracking_number}</Text></View><StatusChip status={shipment.status} label={shipmentTimelineLabel(shipment.status)} /></View><View style={styles.card}><InfoRow icon="confirmation-number" label="เลขติดตาม" value={shipment.tracking_number} /><InfoRow icon="event" label="ส่งสินค้า" value={shipment.shipped_at ? new Date(shipment.shipped_at).toLocaleString("th-TH") : "ยังไม่มีข้อมูลเวลา"} /><InfoRow icon="place" label="ตำแหน่งล่าสุด" value="ผู้ให้บริการยังไม่ได้ส่งข้อมูลตำแหน่ง" /></View><View style={styles.section}><Text style={styles.title}>สถานะการขนส่ง</Text><OrderTimeline steps={timeline.map((status, index) => ({ label: shipmentTimelineLabel(status), value: status === shipment.status ? "สถานะล่าสุด" : index < timeline.indexOf(shipment.status) ? "ดำเนินการแล้ว" : "รออัปเดต", active: timeline.indexOf(shipment.status) >= index, last: index === timeline.length - 1 }))} /></View><View style={styles.actions}><Pressable onPress={() => shipment.tracking_url && void Linking.openURL(shipment.tracking_url)} disabled={!shipment.tracking_url} style={({ pressed }) => [styles.primary, !shipment.tracking_url && styles.disabled, pressed && styles.pressed]}><Text style={styles.primaryText}>ติดตามพัสดุ</Text></Pressable><Pressable onPress={() => router.push(`/orders/${id}/help` as never)} style={({ pressed }) => [styles.secondary, pressed && styles.pressed]}><Text style={styles.secondaryText}>แจ้งปัญหา</Text></Pressable></View></> : <View style={styles.empty}><Text style={styles.emptyTitle}>ยังไม่มีข้อมูลพัสดุ</Text><Text style={styles.emptyCopy}>ผู้ขายจะเพิ่มเลขติดตามหลังจัดส่งสินค้า</Text></View>}</ScrollView>}</ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 32 }, hero: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", borderRadius: 24, backgroundColor: HOBEE.colors.nav, padding: 19 }, heroLabel: { color: "#D8D4CF", fontSize: 12, fontWeight: "700" }, provider: { marginTop: 5, color: "#FFFFFF", fontSize: 20, fontWeight: "900" }, tracking: { marginTop: 6, color: "#D8D4CF", fontSize: 13, fontWeight: "800" }, card: { marginTop: 18, borderRadius: 22, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 14 }, section: { marginTop: 24 }, title: { marginBottom: 10, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, actions: { flexDirection: "row", gap: 10, marginTop: 24 }, primary: { flex: 1, height: 50, alignItems: "center", justifyContent: "center", borderRadius: 17, backgroundColor: HOBEE.colors.gold }, primaryText: { color: HOBEE.colors.ink, fontWeight: "900" }, secondary: { flex: 1, height: 50, alignItems: "center", justifyContent: "center", borderRadius: 17, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface }, secondaryText: { color: HOBEE.colors.ink, fontWeight: "900" }, disabled: { opacity: 0.45 }, empty: { borderRadius: 22, borderWidth: 1, borderStyle: "dashed", borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 20 }, emptyTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, emptyCopy: { marginTop: 5, color: HOBEE.colors.muted, fontSize: 13, lineHeight: 19 }, error: { borderRadius: 22, backgroundColor: "#FFE8E4", padding: 16 }, errorText: { color: "#B65045", fontWeight: "900" }, pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] } });
