import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { goBackOr } from "@/lib/back-navigation";
export default function FoodOrderDetailScreen() { const { reference } = useLocalSearchParams<{ reference: string }>(); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => goBackOr(router, "/travel/food/orders")} style={styles.headerAction}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>Order Status</Text><View style={styles.headerAction}><MaterialIcons name="receipt-long" size={20} color={HOBEE.colors.travelTeal} /></View></View><ScrollView contentContainerStyle={styles.content}><View style={styles.preview}><Text style={styles.label}>FOOD ORDER PREVIEW</Text><Text style={styles.reference}>{reference ?? "—"}</Text><Text style={styles.previewText}>ยังไม่มี Food Order transaction ถูกสร้าง ข้อมูลและ timeline จริงจะมาจากร้านและ order API</Text></View><Text style={styles.sectionTitle}>Order Timeline</Text><View style={styles.timeline}><Step icon="check" title="Review submitted" detail="คุณส่ง Order Preview แล้ว" active /><Step icon="storefront" title="ร้านยืนยันออเดอร์" detail="รอ Food Order integration" /><Step icon="restaurant" title="กำลังเตรียมอาหาร" detail="จะแสดงสถานะจากร้าน" /><Step icon="takeout-dining" title="พร้อมรับ / กำลังจัดส่ง" detail="ตามรูปแบบ fulfilment ที่เลือก" /></View><View style={styles.boundary}><MaterialIcons name="info-outline" size={18} color={HOBEE.colors.goldDark} /><Text style={styles.boundaryText}>การยกเลิก คืนเงิน และติดตาม delivery จะแสดงเฉพาะเมื่อมี order/payment/carrier source ที่เชื่อมต่อแล้ว</Text></View></ScrollView></ScreenContainer>; }
function Step({ icon, title, detail, active = false }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; detail: string; active?: boolean }) { return <View style={styles.step}><View style={[styles.stepIcon, active && styles.stepIconActive]}><MaterialIcons name={icon} size={17} color={active ? "#FFFFFF" : HOBEE.colors.muted} /></View><View style={styles.stepCopy}><Text style={styles.stepTitle}>{title}</Text><Text style={styles.stepDetail}>{detail}</Text></View></View>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 18, paddingVertical: 10 }, headerAction: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: "#F2F0EB" }, headerTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, content: { gap: 16, padding: 18 }, preview: { gap: 6, borderRadius: 19, backgroundColor: HOBEE.atmosphere.warmCream, padding: 15 }, label: { color: HOBEE.colors.goldDark, fontSize: 9, fontWeight: "900", letterSpacing: 1 }, reference: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, previewText: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "600", lineHeight: 15 }, sectionTitle: { color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, timeline: { gap: 0, borderRadius: 19, backgroundColor: HOBEE.colors.surface, padding: 15, ...HOBEE.elevation.card }, step: { flexDirection: "row", gap: 11, minHeight: 67 }, stepIcon: { width: 32, height: 32, alignItems: "center", justifyContent: "center", borderRadius: 16, backgroundColor: "#F0ECE6" }, stepIconActive: { backgroundColor: HOBEE.colors.travelTeal }, stepCopy: { flex: 1, paddingTop: 2 }, stepTitle: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "900" }, stepDetail: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "600" }, boundary: { flexDirection: "row", gap: 8, borderRadius: 15, backgroundColor: HOBEE.atmosphere.warmCream, padding: 12 }, boundaryText: { flex: 1, color: HOBEE.colors.goldDark, fontSize: 10, fontWeight: "700", lineHeight: 15 } });
