import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { goBackOr } from "@/lib/back-navigation";
import { FOOD_COLLECTIONS } from "@/lib/food-experience";
export default function FoodCollectionsScreen() { return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => goBackOr(router, "/travel/food")} style={styles.headerAction}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>Food Collections</Text><View style={styles.headerAction}><MaterialIcons name="auto-awesome" size={20} color={HOBEE.colors.goldDark} /></View></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.intro}>คอลเลกชันอาหารเพื่อการค้นพบ เลือกแล้วจะเปิด Food Hub พร้อมหมวดที่เกี่ยวข้อง</Text>{FOOD_COLLECTIONS.map((item) => <Pressable key={item.id} onPress={() => router.replace("/travel/food" as never)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><Image source={{ uri: item.image }} style={styles.image} /><View style={styles.shade} /><View style={styles.copy}><Text style={styles.title}>{item.title}</Text><Text style={styles.subtitle}>{item.subtitle}</Text></View></Pressable>)}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 18, paddingVertical: 10 }, headerAction: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: "#F2F0EB" }, headerTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, content: { gap: 12, padding: 18 }, intro: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 18 }, card: { height: 154, overflow: "hidden", borderRadius: 22, backgroundColor: HOBEE.colors.ink }, image: { width: "100%", height: "100%" }, shade: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(12,25,23,0.4)" }, copy: { position: "absolute", left: 16, right: 16, bottom: 15 }, title: { color: "#FFFFFF", fontSize: 19, fontWeight: "900" }, subtitle: { marginTop: 4, color: "#ECFFF8", fontSize: 11, fontWeight: "700" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
