import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { HOBEE } from "@/components/hobee/design-tokens";
import { LocationPermissionState } from "@/components/hobee/local-store-ui";
import { ScreenContainer } from "@/components/screen-container";
import { goBackOr } from "@/lib/back-navigation";
import { restaurantListings } from "@/lib/restaurant-data";
export default function FoodMapScreen() { const [locationState, setLocationState] = useState<"idle" | "denied" | "unavailable">("idle"); const [selected, setSelected] = useState(restaurantListings[0]?.id); const active = restaurantListings.find((item) => item.id === selected); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.header}><Pressable onPress={() => goBackOr(router, "/travel/food")} style={styles.headerAction}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>Restaurant Map</Text><Pressable onPress={() => setLocationState("denied")} style={styles.headerAction}><MaterialIcons name="my-location" size={20} color={HOBEE.colors.travelTeal} /></Pressable></View><ScrollView contentContainerStyle={styles.content}>{locationState !== "idle" ? <LocationPermissionState state={locationState} onAllow={() => setLocationState("idle")} onSelectProvince={() => setLocationState("unavailable")} /> : null}<View style={styles.map}><View style={styles.grid}>{Array.from({ length: 18 }, (_, index) => <View key={index} style={styles.block} />)}</View><Text style={styles.mapLabel}>MAP PRESENTATION</Text><Text style={styles.mapDescription}>หมุดร้านอาหารแสดงตามข้อมูล presentation; ระยะทางและ directions จริงรอ maps/location provider</Text>{restaurantListings.slice(0, 6).map((restaurant, index) => <Pressable key={restaurant.id} onPress={() => setSelected(restaurant.id)} style={[styles.pin, { left: `${13 + (index * 17) % 70}%`, top: `${25 + (index * 23) % 50}%` }, selected === restaurant.id && styles.pinActive]}><MaterialIcons name="restaurant" size={16} color="#FFFFFF" /></Pressable>)}</View>{active ? <Pressable onPress={() => router.push({ pathname: "/travel/restaurant/[id]" as never, params: { id: active.id } })} style={({ pressed }) => [styles.selectedCard, pressed && styles.pressed]}><View style={styles.selectedIcon}><MaterialIcons name="restaurant" size={19} color={HOBEE.colors.travelTeal} /></View><View style={styles.selectedCopy}><Text style={styles.selectedName}>{active.name}</Text><Text style={styles.selectedMeta}>{active.district} · ★ {active.rating.toFixed(1)}</Text></View><MaterialIcons name="arrow-forward" size={19} color={HOBEE.colors.goldDark} /></Pressable> : null}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 18, paddingVertical: 10 }, headerAction: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: "#F2F0EB" }, headerTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, content: { gap: 12, padding: 18 }, map: { position: "relative", height: 410, overflow: "hidden", borderRadius: 24, backgroundColor: HOBEE.atmosphere.botanicalMist }, grid: { ...StyleSheet.absoluteFillObject, flexDirection: "row", flexWrap: "wrap", opacity: 0.5 }, block: { width: "25%", height: "20%", borderWidth: 0.5, borderColor: "rgba(8,123,110,0.22)" }, mapLabel: { position: "absolute", top: 28, left: 24, color: HOBEE.colors.travelDeep, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, mapDescription: { position: "absolute", top: 48, left: 24, right: 24, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", lineHeight: 15 }, pin: { position: "absolute", width: 34, height: 34, alignItems: "center", justifyContent: "center", borderRadius: 17, backgroundColor: HOBEE.colors.travelTeal, ...HOBEE.elevation.card }, pinActive: { borderWidth: 3, borderColor: HOBEE.colors.gold, transform: [{ scale: 1.17 }] }, selectedCard: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 17, backgroundColor: HOBEE.colors.surface, padding: 11, ...HOBEE.elevation.card }, selectedIcon: { width: 44, height: 44, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: HOBEE.atmosphere.botanicalMist }, selectedCopy: { flex: 1 }, selectedName: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, selectedMeta: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
