import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { goBackOr } from "@/lib/back-navigation";
const ITEMS = [["verified-user", "ข้อมูลร้านและเมนู", "ร้าน ข้อมูล Halal และเมนูบางส่วนอาจเป็น presentation data จนกว่าจะได้รับการยืนยันจาก merchant"], ["payments", "การชำระเงิน", "อย่าส่งข้อมูลบัตรผ่านข้อความ การชำระเงินจริงต้องใช้ provider flow ที่ปลอดภัยเท่านั้น"], ["delivery-dining", "รับอาหารและการจัดส่ง", "เวลารอ สถานะ rider และค่าจัดส่งจะแสดงจาก merchant/carrier source ที่เชื่อมต่อ"], ["support-agent", "ปัญหาเกี่ยวกับอาหาร", "หากได้รับรายการไม่ตรงหรือมีปัญหา ให้เปิด support/case หลัง order source พร้อมใช้งาน"]] as const;
export default function FoodSafetyScreen() { return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => goBackOr(router, "/travel/food")} style={styles.headerAction}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>Food Safety</Text><View style={styles.headerAction}><MaterialIcons name="health-and-safety" size={20} color={HOBEE.colors.travelTeal} /></View></View><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><MaterialIcons name="health-and-safety" size={31} color={HOBEE.colors.travelTeal} /><Text style={styles.heroTitle}>กินดี เที่ยวดี อย่างมั่นใจ</Text><Text style={styles.heroText}>HOBEE จะระบุข้อมูลที่เป็น presentation และข้อมูลที่ต้องรอ merchant/provider ให้ชัดเจน</Text></View>{ITEMS.map(([icon, title, text]) => <View key={title} style={styles.item}><View style={styles.itemIcon}><MaterialIcons name={icon} size={19} color={HOBEE.colors.goldDark} /></View><View style={styles.itemCopy}><Text style={styles.itemTitle}>{title}</Text><Text style={styles.itemText}>{text}</Text></View></View>)}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 18, paddingVertical: 10 }, headerAction: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: "#F2F0EB" }, headerTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, content: { gap: 12, padding: 18 }, hero: { alignItems: "center", gap: 8, borderRadius: 22, backgroundColor: HOBEE.atmosphere.botanicalMist, padding: 20 }, heroTitle: { color: HOBEE.colors.ink, fontSize: 19, fontWeight: "900" }, heroText: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600", lineHeight: 16, textAlign: "center" }, item: { flexDirection: "row", gap: 11, borderRadius: 17, backgroundColor: HOBEE.colors.surface, padding: 13, ...HOBEE.elevation.card }, itemIcon: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: HOBEE.atmosphere.warmCream }, itemCopy: { flex: 1 }, itemTitle: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, itemText: { marginTop: 4, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "600", lineHeight: 15 } });
