import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { goBackOr } from "@/lib/back-navigation";
import { restaurantListings } from "@/lib/restaurant-data";
import { useFoodPreferences } from "../../../contexts/food-preferences-context";

export default function SavedFoodScreen() {
  const { savedRestaurantIds, recentRestaurantIds, toggleRestaurant } = useFoodPreferences();
  const saved = restaurantListings.filter((item) => savedRestaurantIds.includes(item.id));
  const recent = restaurantListings.filter((item) => recentRestaurantIds.includes(item.id)).sort((a, b) => recentRestaurantIds.indexOf(a.id) - recentRestaurantIds.indexOf(b.id));
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => goBackOr(router, "/travel/food")} style={styles.headerAction}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>Saved Food</Text><Pressable onPress={() => router.push("/travel/food/orders" as never)} style={styles.headerAction}><MaterialIcons name="receipt-long" size={20} color={HOBEE.colors.travelTeal} /></Pressable></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.sectionTitle}>ร้านที่บันทึก</Text>{saved.length ? saved.map((item) => <RestaurantRow key={item.id} name={item.name} image={item.coverImage} meta={item.district} onOpen={() => router.push({ pathname: "/travel/restaurant/[id]" as never, params: { id: item.id } })} onToggle={() => toggleRestaurant(item.id)} />) : <Empty icon="favorite-border" title="ยังไม่มีร้านที่บันทึก" text="กดหัวใจจาก Food Hub เพื่อเก็บร้านไว้ดูภายหลัง" />}<Text style={styles.sectionTitle}>ดูล่าสุด</Text>{recent.length ? recent.map((item) => <RestaurantRow key={item.id} name={item.name} image={item.coverImage} meta={item.district} onOpen={() => router.push({ pathname: "/travel/restaurant/[id]" as never, params: { id: item.id } })} />) : <Empty icon="history" title="ยังไม่มีร้านที่ดูล่าสุด" text="ร้านที่คุณเปิดดูจาก Food Hub จะแสดงในส่วนนี้" />}</ScrollView></ScreenContainer>;
}

function RestaurantRow({ name, image, meta, onOpen, onToggle }: { name: string; image: string; meta: string; onOpen: () => void; onToggle?: () => void }) {
  return <Pressable onPress={onOpen} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><Image source={{ uri: image }} style={styles.image} /><View style={styles.copy}><Text style={styles.name}>{name}</Text><Text style={styles.meta}>{meta}</Text></View>{onToggle ? <Pressable onPress={onToggle} style={styles.heart}><MaterialIcons name="favorite" size={19} color={HOBEE.colors.error} /></Pressable> : <MaterialIcons name="chevron-right" size={22} color={HOBEE.colors.muted} />}</Pressable>;
}
function Empty({ icon, title, text }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; text: string }) { return <View style={styles.empty}><MaterialIcons name={icon} size={27} color={HOBEE.colors.goldDark} /><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyText}>{text}</Text></View>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 18, paddingVertical: 10 }, headerAction: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: "#F2F0EB" }, headerTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, content: { gap: 10, padding: 18 }, sectionTitle: { marginTop: 5, color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, row: { flexDirection: "row", alignItems: "center", gap: 11, borderRadius: 17, backgroundColor: HOBEE.colors.surface, padding: 10, ...HOBEE.elevation.card }, image: { width: 55, height: 55, borderRadius: 13, backgroundColor: "#E8E4DD" }, copy: { flex: 1 }, name: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, meta: { marginTop: 4, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700" }, heart: { padding: 6 }, empty: { alignItems: "center", gap: 5, borderRadius: 18, backgroundColor: HOBEE.atmosphere.warmCream, padding: 19 }, emptyTitle: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, emptyText: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "600", textAlign: "center" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
