import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useDeferredValue, useMemo, useState } from "react";
import { FlatList, Image, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { goBackOr } from "@/lib/back-navigation";
import { foodRestaurantMatches } from "@/lib/food-experience";
import { getFoodTimeSlot, type RestaurantListing } from "@/lib/restaurant-data";
export default function FoodSearchScreen() { const [query, setQuery] = useState(""); const deferred = useDeferredValue(query); const restaurants = useMemo(() => foodRestaurantMatches(deferred, getFoodTimeSlot(), [], "all"), [deferred]); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => goBackOr(router, "/travel/food")} style={styles.headerAction}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><View style={styles.search}><MaterialIcons name="search" size={19} color={HOBEE.colors.muted} /><TextInput autoFocus value={query} onChangeText={setQuery} placeholder="ค้นหาร้าน เมนู หรืออาหาร" placeholderTextColor="#9A958D" style={styles.input} /><Pressable onPress={() => setQuery("")}><MaterialIcons name="close" size={18} color={HOBEE.colors.muted} /></Pressable></View></View><FlatList data={restaurants} keyExtractor={(item) => item.id} ListHeaderComponent={<Text style={styles.resultTitle}>{query ? `ผลลัพธ์ ${restaurants.length} ร้าน` : "ค้นพบร้านอาหาร"}</Text>} renderItem={({ item }) => <SearchRow item={item} />} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="search-off" size={31} color={HOBEE.colors.goldDark} /><Text style={styles.emptyTitle}>ไม่พบร้านที่ตรงกัน</Text><Text style={styles.emptyText}>ลองค้นด้วยชื่อร้าน ชื่อเมนู หรือหมวดอาหาร</Text></View>} contentContainerStyle={styles.content} /></ScreenContainer>; }
function SearchRow({ item }: { item: RestaurantListing }) { return <Pressable onPress={() => router.push({ pathname: "/travel/restaurant/[id]" as never, params: { id: item.id } })} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><Image source={{ uri: item.coverImage }} style={styles.image} /><View style={styles.copy}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.district} · ★ {item.rating.toFixed(1)}</Text><Text numberOfLines={1} style={styles.menuHint}>{item.menuCategories.flatMap((category) => category.items).slice(0, 2).map((menu) => menu.name).join(" · ")}</Text></View><MaterialIcons name="chevron-right" size={22} color={HOBEE.colors.muted} /></Pressable>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 8, borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 18, paddingVertical: 10 }, headerAction: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: "#F2F0EB" }, search: { flex: 1, flexDirection: "row", alignItems: "center", gap: 8, borderRadius: 15, backgroundColor: "#F2F0EB", paddingHorizontal: 11, paddingVertical: 9 }, input: { flex: 1, color: HOBEE.colors.ink, fontSize: 13, fontWeight: "700" }, content: { gap: 9, padding: 18 }, resultTitle: { marginBottom: 4, color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, row: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 17, backgroundColor: HOBEE.colors.surface, padding: 10, ...HOBEE.elevation.card }, image: { width: 58, height: 58, borderRadius: 13, backgroundColor: "#E8E4DD" }, copy: { flex: 1 }, name: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, meta: { marginTop: 3, color: HOBEE.colors.travelTeal, fontSize: 10, fontWeight: "800" }, menuHint: { marginTop: 4, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "600" }, empty: { alignItems: "center", gap: 6, paddingTop: 55 }, emptyTitle: { color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900" }, emptyText: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
