import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";

import { AdminCard, AdminCardTitle, AdminPortalShell, type AdminWorkspace } from "@/components/admin/admin-portal-ui";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { useAdmin } from "@/hooks/use-admin";
import { useToast } from "@/contexts/toast-context";
import { listManageableAfterSalesCases, reviewAfterSalesCase, type AfterSalesCase } from "@/lib/after-sales";

const filters = ["all", "submitted", "under_review", "need_more_info", "approved", "in_progress", "resolved", "closed"];
function navigate(workspace: AdminWorkspace) { if (workspace === "overview") router.push("/admin"); else if (workspace === "orders") router.push("/admin/orders"); else if (workspace === "after_sales") router.replace("/admin/after-sales" as never); else if (workspace === "role_approvals") router.push("/admin/role-approvals" as never); else if (workspace === "products" || workspace === "inventory") router.push("/admin/products" as never); else if (workspace === "travel") router.push("/admin/travel" as never); else if (workspace === "sellers") router.push("/admin/stores" as never); }

export default function AdminAfterSalesScreen() {
  const { allowed, loading: authLoading } = useAdmin(); const { showToast } = useToast(); const [filter, setFilter] = useState("submitted"); const [cases, setCases] = useState<AfterSalesCase[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null);
  const load = useCallback(async () => { if (!allowed) { setLoading(false); return; } setLoading(true); try { setCases(await listManageableAfterSalesCases(filter)); } catch (cause) { showToast(cause instanceof Error ? cause.message : "ไม่สามารถโหลดเคสหลังการขายได้", "error"); } finally { setLoading(false); } }, [allowed, filter, showToast]);
  useEffect(() => { void load(); }, [load]);
  const decide = (item: AfterSalesCase, status: string) => Alert.alert("ยืนยันการอัปเดตเคส", `เปลี่ยน ${item.case_number} เป็น ${status.replaceAll("_", " ")} ใช่หรือไม่?`, [{ text: "ยกเลิก", style: "cancel" }, { text: "ยืนยัน", onPress: () => { void (async () => { setSaving(item.id); try { await reviewAfterSalesCase(item.id, status); showToast("บันทึกสถานะเคสและแจ้งลูกค้าแล้ว"); await load(); } catch (cause) { showToast(cause instanceof Error ? cause.message : "ไม่สามารถอัปเดตเคสได้", "error"); } finally { setSaving(null); } })(); } }]);
  if (authLoading || loading) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="items-center justify-center"><ActivityIndicator size="large" color={HOBEE.colors.goldDark} /></ScreenContainer>;
  if (!allowed) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="items-center justify-center"><Text style={styles.denied}>บัญชีนี้ไม่มีสิทธิ์เข้าถึง HOBEE Admin Portal</Text></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F7F8F6]"><AdminPortalShell active="after_sales" title="เคสหลังการขาย" subtitle="ตรวจคำร้อง คืนสินค้า เปลี่ยนสินค้า และการคืนเงินอย่างมี audit trail" onNavigate={navigate} onRefresh={load}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map((value) => <Pressable key={value} onPress={() => setFilter(value)} style={[styles.filter, filter === value && styles.filterActive]}><Text style={[styles.filterText, filter === value && styles.filterTextActive]}>{value.replaceAll("_", " ")}</Text></Pressable>)}</ScrollView><AdminCard style={styles.tableCard}><AdminCardTitle title={`คำร้อง · ${cases.length}`} action="รีเฟรช" onAction={() => void load()} /><ScrollView horizontal showsHorizontalScrollIndicator={false}><View style={styles.table}><View style={[styles.row, styles.head]}><Text style={[styles.headText, styles.number]}>เลขเคส</Text><Text style={[styles.headText, styles.issue]}>ปัญหา</Text><Text style={[styles.headText, styles.resolution]}>แนวทาง</Text><Text style={[styles.headText, styles.status]}>สถานะ</Text><Text style={styles.action}>ดำเนินการ</Text></View>{cases.map((item) => <View key={item.id} style={styles.row}><View style={styles.number}><Text style={styles.caseNumber}>{item.case_number}</Text><Text style={styles.caseDate}>{new Date(item.updated_at).toLocaleDateString("th-TH")}</Text></View><View style={styles.issue}><Text style={styles.issueText}>{item.case_type.replaceAll("_", " ")}</Text><Text numberOfLines={2} style={styles.description}>{item.description}</Text></View><Text style={[styles.cell, styles.resolution]}>{item.requested_resolution.replaceAll("_", " ")}</Text><Text style={[styles.statusPill, styles.status]}>{item.status.replaceAll("_", " ")}</Text><View style={styles.action}><Pressable onPress={() => router.push(`/claims/${item.id}` as never)} style={styles.open}><Text style={styles.openText}>ดูเคส</Text></Pressable>{["submitted", "under_review", "need_more_info"].includes(item.status) ? <Pressable disabled={saving === item.id} onPress={() => decide(item, item.status === "submitted" ? "under_review" : "in_progress")} style={styles.advance}><MaterialIcons name="arrow-forward" size={14} color="#FFFFFF" /></Pressable> : null}</View></View>)}</View></ScrollView>{!cases.length ? <View style={styles.empty}><MaterialIcons name="support-agent" size={34} color="#B9BFBB" /><Text style={styles.emptyTitle}>ไม่มีเคสในสถานะนี้</Text><Text style={styles.emptyCopy}>เมื่อมีคำร้องที่คุณมีสิทธิ์จัดการ ระบบจะแสดงรายการที่นี่</Text></View> : null}</AdminCard></AdminPortalShell></ScreenContainer>;
}
const styles = StyleSheet.create({ denied: { color: HOBEE.colors.muted, fontSize: 13, fontWeight: "800" }, filters: { gap: 7, paddingBottom: 14 }, filter: { borderRadius: 9, borderWidth: 1, borderColor: "#E2E5E1", backgroundColor: "#FFFFFF", paddingHorizontal: 11, paddingVertical: 8 }, filterActive: { borderColor: HOBEE.colors.goldDark, backgroundColor: HOBEE.colors.darkCard }, filterText: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "800", textTransform: "capitalize" }, filterTextActive: { color: "#FFFFFF" }, tableCard: { padding: 0, overflow: "hidden" }, table: { minWidth: 960 }, row: { flexDirection: "row", alignItems: "center", minHeight: 74, borderTopWidth: 1, borderTopColor: "#EFF1EF", paddingHorizontal: 17 }, head: { minHeight: 43, borderTopWidth: 0, backgroundColor: "#FAFBFA" }, headText: { color: "#858C87", fontSize: 9, fontWeight: "900" }, number: { width: 170 }, issue: { width: 290 }, resolution: { width: 160 }, status: { width: 140 }, action: { width: 150, flexDirection: "row", gap: 7 }, caseNumber: { color: HOBEE.colors.goldDark, fontSize: 11, fontWeight: "900" }, caseDate: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 9 }, issueText: { color: HOBEE.colors.ink, fontSize: 11, fontWeight: "900", textTransform: "capitalize" }, description: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 10, lineHeight: 14 }, cell: { color: HOBEE.colors.ink, fontSize: 11, fontWeight: "800", textTransform: "capitalize" }, statusPill: { alignSelf: "flex-start", overflow: "hidden", borderRadius: 8, backgroundColor: "#F0F2F0", color: "#66706A", paddingHorizontal: 8, paddingVertical: 5, fontSize: 9, fontWeight: "900", textTransform: "capitalize" }, open: { borderRadius: 8, borderWidth: 1, borderColor: "#D9E2DC", paddingHorizontal: 9, paddingVertical: 8 }, openText: { color: HOBEE.colors.botanical, fontSize: 9, fontWeight: "900" }, advance: { width: 31, height: 31, alignItems: "center", justifyContent: "center", borderRadius: 8, backgroundColor: HOBEE.colors.goldDark }, empty: { minHeight: 210, alignItems: "center", justifyContent: "center", gap: 6 }, emptyTitle: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, emptyCopy: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600" } });
