import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";

import { PrimaryButton } from "@/components/hobee/primary-button";
import { ScreenContainer } from "@/components/screen-container";
import { useAdmin } from "@/hooks/use-admin";
import { formatThaiBaht } from "@/lib/hobee-data";
import { orderStatusLabel } from "@/lib/orders";

export default function AdminDashboardScreen() {
  const { allowed, loading, products, orders, error, refresh } = useAdmin();
  if (loading) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="items-center justify-center"><ActivityIndicator color="#C98716" size="large" /></ScreenContainer>;
  if (!allowed) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="items-center justify-center px-6"><View className="items-center rounded-3xl border border-border bg-surface p-7"><MaterialIcons name="admin-panel-settings" size={38} color="#C98716" /><Text className="mt-4 text-xl font-black text-foreground">สำหรับผู้ดูแลระบบ</Text><Text className="mt-2 text-center text-sm leading-5 text-muted">บัญชีนี้ยังไม่มี role admin จึงไม่สามารถเข้าถึงข้อมูลหลังบ้านได้</Text><PrimaryButton label="กลับหน้าบัญชี" icon="arrow-back" onPress={() => router.back()} style={styles.button} /></View></ScreenContainer>;
  const lowStock = products.filter((product) => product.stock_quantity <= 5).length;
  const pendingOrders = orders.filter((order) => ["pending", "confirmed", "processing"].includes(order.status)).length;
  return <ScreenContainer className="px-5" safeAreaClassName="pt-3"><View className="mb-5 flex-row items-center justify-between"><View className="flex-row items-center gap-3"><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#17352A" /></Pressable><View><Text className="text-2xl font-black text-foreground">HOBEE Admin</Text><Text className="mt-0.5 text-sm text-muted">สินค้า สต็อก และคำสั่งซื้อ</Text></View></View><Pressable onPress={() => void refresh()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="refresh" size={20} color="#17352A" /></Pressable></View><View className="mb-5 flex-row gap-3"><Metric value={products.length} label="สินค้า" icon="inventory-2" /><Metric value={lowStock} label="ใกล้หมด" icon="warning-amber" /><Metric value={pendingOrders} label="ต้องจัดการ" icon="local-shipping" /></View><FlatList data={products} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={<View className="mb-3 flex-row items-center justify-between"><Text className="text-base font-black text-foreground">สินค้า</Text><Pressable onPress={() => router.push("/admin/orders")}><Text className="text-sm font-bold text-primary">ดูคำสั่งซื้อ</Text></Pressable></View>} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/admin/product/[id]", params: { id: item.id } })} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View className="flex-1"><Text numberOfLines={1} className="font-black text-foreground">{item.name}</Text><Text className="mt-1 text-xs text-muted">{item.shops?.name ?? "HOBEE"} · {item.sku ?? "ไม่มี SKU"}</Text><View className="mt-3 flex-row gap-2"><Text className="rounded-full bg-[#F5EBCF] px-2 py-1 text-xs font-bold text-[#B96E0A]">สต็อก {item.stock_quantity}</Text><Text className="rounded-full bg-[#EAF5EE] px-2 py-1 text-xs font-bold text-success">{item.status}</Text></View></View><View className="items-end"><Text className="font-black text-foreground">{formatThaiBaht(item.price)}</Text><MaterialIcons name="chevron-right" size={22} color="#8A978E" /></View></Pressable>} ListEmptyComponent={<Text className="text-sm text-muted">{error ?? "ไม่พบข้อมูลสินค้า"}</Text>} /></ScreenContainer>;
}

function Metric({ value, label, icon }: { value: number; label: string; icon: "inventory-2" | "warning-amber" | "local-shipping" }) { return <View className="flex-1 rounded-2xl border border-border bg-surface p-3"><MaterialIcons name={icon} size={21} color="#C98716" /><Text className="mt-3 text-2xl font-black text-foreground">{value}</Text><Text className="mt-0.5 text-xs text-muted">{label}</Text></View>; }
const styles = StyleSheet.create({ list: { paddingBottom: 28 }, back: { height: 42, width: 42, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#E8E0D0", borderRadius: 21, backgroundColor: "#FFFFFF" }, card: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 10, borderWidth: 1, borderColor: "#E8E0D0", borderRadius: 16, backgroundColor: "#FFFFFF", padding: 14 }, button: { marginTop: 20 }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });

