import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, type Href } from "expo-router";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { COMMUNITY_PEOPLE, COMMUNITY_POSTS } from "@/lib/community-hub";

const CURRENT = COMMUNITY_PEOPLE[0];
const NAV_ITEMS = [
  { title: "ผู้ติดตามและกำลังติดตาม", subtitle: "ดูความเชื่อมโยงของคุณใน Community", icon: "group", route: "/community/profile/network" },
  { title: "เนื้อหาที่บันทึก", subtitle: "Stories และรายการ Community ที่คุณบันทึกไว้", icon: "bookmark-border", route: "/community/search" },
  { title: "ความเป็นส่วนตัวและความปลอดภัย", subtitle: "จัดการ visibility, block และการรายงาน", icon: "shield", route: "/community/profile/privacy" },
  { title: "การแจ้งเตือน", subtitle: "ใช้ Notification Center กลางของ HOBEE", icon: "notifications-none", route: "/my-hobee/notifications" },
];

export default function CommunityProfileScreen() { return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.circle}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>โปรไฟล์ Community</Text><Pressable onPress={() => router.push("/community/profile/privacy" as Href)} style={styles.circle}><MaterialIcons name="settings" size={20} color={HOBEE.colors.ink} /></Pressable></View><View style={styles.hero}><Image source={{ uri: CURRENT.avatar }} style={styles.avatar} /><Text style={styles.name}>{CURRENT.name}</Text><Text style={styles.role}>{CURRENT.role} · Community Member</Text><Text style={styles.bio}>{CURRENT.bio}</Text><View style={styles.stats}><Stat label="Stories" value="จาก source ที่อนุญาต" /><Stat label="กิจกรรม" value="ดูใน My Activities" /><Stat label="ชมรม" value="สถานะจาก membership" /></View><Pressable style={styles.edit}><MaterialIcons name="edit" size={17} color={HOBEE.colors.ink} /><Text style={styles.editText}>แก้ไขข้อมูล Community</Text></Pressable></View><Text style={styles.sectionTitle}>Community ของคุณ</Text><View style={styles.list}>{NAV_ITEMS.map((item) => <Pressable key={item.title} onPress={() => router.push(item.route as Href)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.rowIcon}><MaterialIcons name={item.icon as keyof typeof MaterialIcons.glyphMap} size={20} color={HOBEE.colors.botanical} /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{item.title}</Text><Text style={styles.rowSubtitle}>{item.subtitle}</Text></View><MaterialIcons name="chevron-right" size={21} color={HOBEE.colors.muted} /></Pressable>)}</View><View style={styles.footer}><MaterialIcons name="info-outline" size={17} color={HOBEE.colors.muted} /><Text style={styles.footerText}>โปรไฟล์นี้เป็น presentation ของ Community. Follower count, privacy policy และ block state จะ persist เมื่อ Community backend พร้อม</Text></View><Text style={styles.hidden}>{COMMUNITY_POSTS.length}</Text></ScrollView></ScreenContainer>; }
function Stat({ label, value }: { label: string; value: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 42 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: HOBEE.space.page }, circle: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, headerTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, hero: { alignItems: "center", gap: 7, marginHorizontal: HOBEE.space.page, borderRadius: HOBEE.radius.hero, backgroundColor: HOBEE.atmosphere.warmCream, padding: 22 }, avatar: { width: 88, height: 88, borderRadius: 44, borderWidth: 3, borderColor: HOBEE.colors.surface }, name: { color: HOBEE.colors.ink, fontSize: 23, fontWeight: "900", marginTop: 4 }, role: { color: HOBEE.colors.botanical, fontSize: 12, fontWeight: "900" }, bio: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 18, textAlign: "center" }, stats: { flexDirection: "row", width: "100%", marginTop: 7 }, stat: { flex: 1, alignItems: "center", gap: 4 }, statValue: { color: HOBEE.colors.ink, fontSize: 9, fontWeight: "900", textAlign: "center" }, statLabel: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700" }, edit: { flexDirection: "row", alignItems: "center", gap: 7, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.gold, marginTop: 6, paddingHorizontal: 15, paddingVertical: 9 }, editText: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "900" }, sectionTitle: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900", marginHorizontal: HOBEE.space.page, marginTop: 5 }, list: { gap: 9, paddingHorizontal: HOBEE.space.page }, row: { flexDirection: "row", alignItems: "center", gap: 11, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.colors.surface, padding: 13, ...HOBEE.elevation.surface }, rowIcon: { width: 40, height: 40, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: HOBEE.atmosphere.botanicalMist }, rowCopy: { flex: 1, gap: 3 }, rowTitle: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, rowSubtitle: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "600", lineHeight: 15 }, footer: { flexDirection: "row", gap: 7, marginHorizontal: HOBEE.space.page }, footerText: { flex: 1, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", lineHeight: 15 }, hidden: { color: "transparent", height: 0 }, pressed: { opacity: 0.8, transform: [{ scale: HOBEE.motion.cardPressScale }] } });
