import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { COMMUNITY_PEOPLE } from "@/lib/community-hub";

export default function CommunityNetworkScreen() { const [following, setFollowing] = useState(() => new Set(COMMUNITY_PEOPLE.filter((item) => item.followState === "following").map((item) => item.id))); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.title}>เครือข่ายของคุณ</Text><View style={styles.back} /></View><Text style={styles.subtitle}>สถานะ follow เป็น local presentation จนกว่าจะมี Community relationship source</Text>{COMMUNITY_PEOPLE.map((person) => { const isFollowing = following.has(person.id); return <View key={person.id} style={styles.row}><Image source={{ uri: person.avatar }} style={styles.avatar} /><View style={styles.copy}><Text style={styles.name}>{person.name}</Text><Text style={styles.meta}>{person.role} · {person.interests.join(" · ")}</Text></View><Pressable onPress={() => setFollowing((current) => { const next = new Set(current); if (next.has(person.id)) next.delete(person.id); else next.add(person.id); return next; })} style={[styles.follow, isFollowing && styles.following]}><Text style={styles.followText}>{isFollowing ? "ติดตามแล้ว" : "ติดตาม"}</Text></Pressable></View>})}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { gap: 10, padding: HOBEE.space.page, paddingBottom: 42 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 4 }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, title: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, subtitle: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700", lineHeight: 16, marginBottom: 4 }, row: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.colors.surface, padding: 11, ...HOBEE.elevation.surface }, avatar: { width: 46, height: 46, borderRadius: 23 }, copy: { flex: 1, gap: 3 }, name: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, meta: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700" }, follow: { borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.gold, paddingHorizontal: 10, paddingVertical: 8 }, following: { backgroundColor: HOBEE.atmosphere.botanicalMist }, followText: { color: HOBEE.colors.ink, fontSize: 10, fontWeight: "900" } });
