import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";

export default function CommunityPrivacyScreen() { const [discoverable, setDiscoverable] = useState(true); const [showProvince, setShowProvince] = useState(false); const [allowMessages, setAllowMessages] = useState(false); const rows = [{ label: "ค้นหาโปรไฟล์ของฉันได้", value: discoverable, set: setDiscoverable }, { label: "แสดงจังหวัดในโปรไฟล์", value: showProvince, set: setShowProvince }, { label: "รับการติดต่อจากสมาชิก", value: allowMessages, set: setAllowMessages }]; return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.title}>ความเป็นส่วนตัว</Text><View style={styles.back} /></View><Text style={styles.subtitle}>การตั้งค่านี้เป็น UI preview และจะเชื่อม Community privacy policy เมื่อ backend พร้อม</Text><View style={styles.card}>{rows.map((row) => <View key={row.label} style={styles.row}><Text style={styles.rowText}>{row.label}</Text><Switch value={row.value} onValueChange={row.set} trackColor={{ false: HOBEE.colors.border, true: HOBEE.colors.gold }} thumbColor={HOBEE.colors.surface} /></View>)}</View><Text style={styles.section}>ความปลอดภัย</Text><View style={styles.card}><SafetyRow icon="block" title="บัญชีที่บล็อก" detail="รายการบล็อกจะแสดงจาก source ที่ได้รับอนุญาต" /><SafetyRow icon="outlined-flag" title="รายงานเนื้อหา" detail="รายงานจะส่งเข้าสู่ moderation queue เมื่อเปิดระบบจริง" /><SafetyRow icon="policy" title="Community Guidelines" detail="อ่านแนวทางการเข้าร่วมอย่างปลอดภัย" /></View></ScrollView></ScreenContainer>; }
function SafetyRow({ icon, title, detail }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; detail: string }) { return <View style={styles.safety}><MaterialIcons name={icon} size={20} color={HOBEE.colors.goldDark} /><View style={styles.safetyCopy}><Text style={styles.safetyTitle}>{title}</Text><Text style={styles.safetyDetail}>{detail}</Text></View><MaterialIcons name="chevron-right" size={20} color={HOBEE.colors.muted} /></View>; }
const styles = StyleSheet.create({ content: { gap: 14, padding: HOBEE.space.page, paddingBottom: 42 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, title: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, subtitle: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700", lineHeight: 16 }, card: { borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.colors.surface, ...HOBEE.elevation.surface }, row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 14, borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border }, rowText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "800" }, section: { color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900", marginTop: 4 }, safety: { flexDirection: "row", alignItems: "center", gap: 10, padding: 13, borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border }, safetyCopy: { flex: 1, gap: 3 }, safetyTitle: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, safetyDetail: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", lineHeight: 15 } });
