import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { goBackOr } from "@/lib/back-navigation";

export default function LocalStoreReviewScreen() { const { reference } = useLocalSearchParams<{ reference?: string }>(); const [rating, setRating] = useState(0); const [text, setText] = useState(""); const [sent, setSent] = useState(false); return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-background"><View style={styles.root}><View style={styles.top}><Pressable onPress={() => goBackOr(router, `/stores/orders/${reference ?? "LOCAL-PREVIEW"}`)} style={styles.back}><MaterialIcons name="arrow-back" size={21} color={HOBEE.colors.ink} /></Pressable><Text style={styles.title}>รีวิวร้าน</Text></View><ScrollView contentContainerStyle={styles.content}>{sent ? <View style={styles.sent}><View style={styles.sentIcon}><MaterialIcons name="check" size={32} color={HOBEE.colors.surface} /></View><Text style={styles.sentTitle}>บันทึก Review Preview แล้ว</Text><Text style={styles.sentText}>รีวิวจริงจะส่งเข้าระบบ moderation เมื่อ Store Order และ review integration พร้อม</Text><Pressable onPress={() => router.replace("/stores" as never)} style={styles.done}><Text style={styles.doneText}>กลับหน้าร้านค้า</Text></Pressable></View> : <><Text style={styles.headline}>ประสบการณ์กับร้านเป็นอย่างไร?</Text><Text style={styles.subhead}>UI นี้จะแสดงเมื่อคำสั่งซื้อเสร็จสิ้นและผู้ใช้มีสิทธิ์รีวิว</Text><View style={styles.stars}>{[1, 2, 3, 4, 5].map((star) => <Pressable key={star} onPress={() => setRating(star)}><MaterialIcons name={star <= rating ? "star" : "star-border"} size={37} color={star <= rating ? HOBEE.colors.goldDark : HOBEE.colors.border} /></Pressable>)}</View><TextInput value={text} onChangeText={setText} multiline placeholder="เขียนรีวิวของคุณ (Preview)" placeholderTextColor={HOBEE.colors.muted} style={styles.input} /><View style={styles.tags}>{["รสชาติดี", "บริการดี", "บรรยากาศดี", "คุ้มค่า"].map((tag) => <View key={tag} style={styles.tag}><Text style={styles.tagText}>{tag}</Text></View>)}</View><Pressable disabled={!rating} onPress={() => setSent(true)} style={[styles.submit, !rating && styles.submitDisabled]}><Text style={styles.submitText}>ส่ง Review Preview</Text></Pressable></>}</ScrollView></View></ScreenContainer>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: HOBEE.atmosphere.canvas }, top: { flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 11 }, back: { alignItems: "center", justifyContent: "center", width: 37, height: 37, borderRadius: 19, backgroundColor: HOBEE.atmosphere.warmCream }, title: { color: HOBEE.colors.ink, fontSize: 19, fontWeight: "900" }, content: { gap: 16, padding: HOBEE.space.page }, headline: { color: HOBEE.colors.ink, fontSize: 22, fontWeight: "900", textAlign: "center", marginTop: 20 }, subhead: { color: HOBEE.colors.muted, fontSize: 12, lineHeight: 18, fontWeight: "600", textAlign: "center" }, stars: { flexDirection: "row", justifyContent: "center", gap: 7, marginVertical: 10 }, input: { minHeight: 115, borderWidth: 1, borderColor: HOBEE.colors.border, borderRadius: 15, backgroundColor: HOBEE.colors.surface, color: HOBEE.colors.ink, fontSize: 13, fontWeight: "600", padding: 12, textAlignVertical: "top", outlineStyle: "none" as any }, tags: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 8 }, tag: { borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.atmosphere.botanicalMist, paddingHorizontal: 11, paddingVertical: 7 }, tagText: { color: HOBEE.colors.botanical, fontSize: 10, fontWeight: "800" }, submit: { alignItems: "center", borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.goldDark, paddingVertical: 13 }, submitDisabled: { opacity: 0.4 }, submitText: { color: HOBEE.colors.surface, fontSize: 13, fontWeight: "900" }, sent: { alignItems: "center", gap: 12, marginTop: 55 }, sentIcon: { alignItems: "center", justifyContent: "center", width: 64, height: 64, borderRadius: 32, backgroundColor: HOBEE.colors.botanical }, sentTitle: { color: HOBEE.colors.ink, fontSize: 20, fontWeight: "900" }, sentText: { color: HOBEE.colors.muted, fontSize: 12, lineHeight: 18, fontWeight: "600", textAlign: "center" }, done: { marginTop: 8, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.goldDark, paddingHorizontal: 18, paddingVertical: 12 }, doneText: { color: HOBEE.colors.surface, fontSize: 12, fontWeight: "900" } });
