import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { goBackOr } from "@/lib/back-navigation";
import { calculateFoodCart, foodMenuOptions, foodRestaurantMenu, type FoodFulfilment } from "@/lib/food-experience";
import { restaurantListings } from "@/lib/restaurant-data";
import { useFoodCart } from "../../../../contexts/food-cart-context";

export default function FoodReviewOrderScreen() {
  const { id, fulfilment: inputFulfilment, note } = useLocalSearchParams<{ id: string; fulfilment?: FoodFulfilment; note?: string }>(); const { entries, clear } = useFoodCart(); const restaurant = restaurantListings.find((entry) => entry.id === id); const fulfilment = inputFulfilment ?? "pickup";
  if (!restaurant) return <ScreenContainer><View style={styles.center}><Text>ไม่พบร้านอาหาร</Text></View></ScreenContainer>;
  const menu = foodRestaurantMenu(restaurant); const quote = calculateFoodCart(menu, entries.map((entry) => ({ itemId: entry.itemId, quantity: entry.quantity, selectedOptions: foodMenuOptions(menu.find((item) => item.id === entry.itemId) ?? menu[0]!).filter((option) => entry.optionIds.includes(option.id)) })), fulfilment);
  const confirm = () => { clear(); router.replace({ pathname: "/travel/food/orders/[reference]" as never, params: { reference: `HB-FOOD-PREVIEW-${restaurant.id}` } }); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => goBackOr(router, "/travel/food/cart")} style={styles.headerAction}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>Review Order</Text><View style={styles.headerAction}><MaterialIcons name="receipt-long" size={20} color={HOBEE.colors.travelTeal} /></View></View><ScrollView contentContainerStyle={styles.content}><View style={styles.stepRow}><Text style={styles.stepText}>1 Cart</Text><MaterialIcons name="chevron-right" size={16} color={HOBEE.colors.muted} /><Text style={[styles.stepText, styles.stepActive]}>2 Review</Text><MaterialIcons name="chevron-right" size={16} color={HOBEE.colors.muted} /><Text style={styles.stepText}>3 Confirm</Text></View><View style={styles.card}><Text style={styles.cardLabel}>RESTAURANT</Text><Text style={styles.restaurantName}>{restaurant.name}</Text><Text style={styles.info}>{fulfilment === "dine_in" ? "ทานที่ร้าน" : fulfilment === "pickup" ? "Pickup" : "Delivery"} · เวลารับอาหารจะแสดงเมื่อร้านยืนยัน</Text></View><View style={styles.card}><Text style={styles.cardLabel}>ORDER ITEMS</Text>{quote.lines.map((line) => <View key={line.item.id} style={styles.line}><Text style={styles.lineName}>{line.quantity}× {line.item.name}</Text><Text style={styles.linePrice}>฿{line.lineTotal.toLocaleString("th-TH")}</Text></View>)}</View>{note ? <View style={styles.card}><Text style={styles.cardLabel}>NOTE TO RESTAURANT</Text><Text style={styles.info}>{note}</Text></View> : null}<View style={styles.card}><Text style={styles.cardLabel}>PAYMENT</Text><Text style={styles.info}>ยังไม่สร้างธุรกรรม การชำระเงินจริงจะใช้ Payment flow เดิมหลัง Food Order API พร้อม</Text></View><View style={styles.totalCard}><Text style={styles.totalLabel}>ยอดรวมอาหาร</Text><Text style={styles.total}>฿{quote.total.toLocaleString("th-TH")}</Text><Text style={styles.totalHint}>ค่าบริการ ค่าส่ง และส่วนลดจะคำนวณจาก source จริง</Text></View></ScrollView><View style={styles.footer}><Pressable onPress={confirm} style={({ pressed }) => [styles.confirm, pressed && styles.pressed]}><Text style={styles.confirmText}>ยืนยัน Order Preview</Text><MaterialIcons name="arrow-forward" size={18} color={HOBEE.colors.ink} /></Pressable></View></ScreenContainer>;
}
const styles = StyleSheet.create({ center: { flex: 1, alignItems: "center", justifyContent: "center" }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 18, paddingVertical: 10 }, headerAction: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: "#F2F0EB" }, headerTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, content: { gap: 11, padding: 18, paddingBottom: 104 }, stepRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4, paddingBottom: 4 }, stepText: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "800" }, stepActive: { color: HOBEE.colors.travelTeal }, card: { gap: 8, borderRadius: 18, backgroundColor: HOBEE.colors.surface, padding: 14, ...HOBEE.elevation.card }, cardLabel: { color: HOBEE.colors.goldDark, fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, restaurantName: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, info: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600", lineHeight: 16 }, line: { flexDirection: "row", justifyContent: "space-between", gap: 10, borderTopWidth: 1, borderTopColor: HOBEE.colors.border, paddingTop: 10 }, lineName: { flex: 1, color: HOBEE.colors.ink, fontSize: 12, fontWeight: "800" }, linePrice: { color: HOBEE.colors.travelTeal, fontSize: 12, fontWeight: "900" }, totalCard: { gap: 3, borderRadius: 18, backgroundColor: HOBEE.atmosphere.warmCream, padding: 15 }, totalLabel: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "800" }, total: { color: HOBEE.colors.ink, fontSize: 23, fontWeight: "900" }, totalHint: { color: HOBEE.colors.goldDark, fontSize: 10, fontWeight: "700" }, footer: { position: "absolute", bottom: 0, left: 0, right: 0, borderTopWidth: 1, borderTopColor: HOBEE.colors.border, backgroundColor: "rgba(255,255,255,0.98)", paddingHorizontal: 18, paddingTop: 10, paddingBottom: 18 }, confirm: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, borderRadius: 15, backgroundColor: HOBEE.colors.gold, paddingVertical: 14 }, confirmText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
