import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams, type Href } from "expo-router";
import { useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AppStatusState } from "@/components/hobee/error-screens";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { COMMUNITY_CLUBS, getCommunityActivity } from "@/lib/community-hub";

export default function CommunityActivityDetailScreen() { const { id } = useLocalSearchParams<{ id?: string }>(); const activity = getCommunityActivity(id); const [joined, setJoined] = useState(activity?.joinState === "joined"); if (!activity) return <ScreenContainer><AppStatusState title="ไม่พบกิจกรรมนี้" description="กลับไปเลือกกิจกรรมจาก Community อีกครั้ง" actionLabel="ดูกิจกรรม" onAction={() => router.replace("/community/activities" as Href)} /></ScreenContainer>; const club = COMMUNITY_CLUBS.find((item) => item.id === activity.relatedClubId); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.imageWrap}><Image source={{ uri: activity.image }} style={styles.image} /><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable></View><View style={styles.body}><Text style={styles.date}>{activity.startsAt.slice(0, 10)}</Text><Text style={styles.title}>{activity.title}</Text><Text style={styles.description}>กิจกรรมโดย {activity.organizer} สำหรับผู้สนใจ {activity.category.toLowerCase()} ในชุมชน HOBEE</Text><View style={styles.facts}><Fact icon="place" label={activity.location} /><Fact icon="groups" label={activity.capacityLabel} /><Fact icon="category" label={activity.category} /></View>{club ? <Pressable onPress={() => router.push(`/community/clubs/${club.id}` as Href)} style={styles.clubRow}><MaterialIcons name="groups" size={18} color={HOBEE.colors.botanical} /><View style={styles.clubCopy}><Text style={styles.clubTitle}>จัดโดย {club.name}</Text><Text style={styles.clubText}>ดูชมรมและกิจกรรมอื่น</Text></View><MaterialIcons name="chevron-right" size={20} color={HOBEE.colors.muted} /></Pressable> : null}<View style={styles.calendar}><MaterialIcons name="calendar-month" size={19} color={HOBEE.colors.goldDark} /><Text style={styles.calendarText}>เพิ่มลงปฏิทินจะแสดงเมื่อ calendar integration พร้อม</Text></View><View style={styles.boundary}><MaterialIcons name="info-outline" size={17} color={HOBEE.colors.muted} /><Text style={styles.boundaryText}>จำนวนที่นั่งและสถานะ join เป็น presentation state ไม่ใช่ข้อมูลรับสมัครจริง</Text></View><Pressable onPress={() => setJoined((current) => !current)} style={[styles.join, joined && styles.joined]}><Text style={styles.joinText}>{joined ? "เข้าร่วมแล้ว" : activity.joinState === "waitlist" ? "เข้าคิวรอ" : "เข้าร่วมกิจกรรม"}</Text><MaterialIcons name={joined ? "check" : "event-available"} size={18} color={HOBEE.colors.ink} /></Pressable></View></ScrollView></ScreenContainer>; }
function Fact({ icon, label }: { icon: keyof typeof MaterialIcons.glyphMap; label: string }) { return <View style={styles.fact}><MaterialIcons name={icon} size={17} color={HOBEE.colors.botanical} /><Text style={styles.factText}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 42 }, imageWrap: { height: 250 }, image: { width: "100%", height: "100%", backgroundColor: HOBEE.atmosphere.skyMist }, back: { position: "absolute", top: 14, left: HOBEE.space.page, width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: "rgba(255,255,255,0.92)" }, body: { gap: 12, marginTop: -22, borderTopLeftRadius: HOBEE.radius.hero, borderTopRightRadius: HOBEE.radius.hero, backgroundColor: HOBEE.colors.canvas, padding: HOBEE.space.page }, date: { color: HOBEE.colors.goldDark, fontSize: 11, fontWeight: "900" }, title: { color: HOBEE.colors.ink, fontSize: 25, fontWeight: "900", lineHeight: 31 }, description: { color: HOBEE.colors.muted, fontSize: 13, fontWeight: "600", lineHeight: 20 }, facts: { gap: 8, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.colors.surface, padding: 13, ...HOBEE.elevation.surface }, fact: { flexDirection: "row", alignItems: "center", gap: 8 }, factText: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "700" }, clubRow: { flexDirection: "row", alignItems: "center", gap: 9, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.atmosphere.botanicalMist, padding: 12 }, clubCopy: { flex: 1 }, clubTitle: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "900" }, clubText: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", marginTop: 3 }, calendar: { flexDirection: "row", alignItems: "center", gap: 8, borderRadius: HOBEE.radius.medium, backgroundColor: HOBEE.atmosphere.warmCream, padding: 11 }, calendarText: { flex: 1, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700", lineHeight: 16 }, boundary: { flexDirection: "row", gap: 7 }, boundaryText: { flex: 1, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", lineHeight: 15 }, join: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.gold, paddingVertical: 13 }, joined: { backgroundColor: HOBEE.atmosphere.botanicalMist }, joinText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" } });
