import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { COMMUNITY_CLUBS, COMMUNITY_PROVINCES } from "@/lib/community-hub";

export default function CommunityCreateActivityScreen() { const [title, setTitle] = useState(""); const [clubId, setClubId] = useState(COMMUNITY_CLUBS[0]?.id ?? ""); const [province, setProvince] = useState(COMMUNITY_PROVINCES[0].id); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="close" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.title}>สร้างกิจกรรม</Text><View style={styles.back} /></View><ScrollView contentContainerStyle={styles.content}><TextInput value={title} onChangeText={setTitle} placeholder="ชื่อกิจกรรม" placeholderTextColor={HOBEE.colors.muted} style={styles.input} /><TextInput placeholder="อธิบายกิจกรรมและสิ่งที่ผู้เข้าร่วมควรทราบ" placeholderTextColor={HOBEE.colors.muted} multiline textAlignVertical="top" style={[styles.input, styles.description]} /><Text style={styles.label}>ชมรมที่เกี่ยวข้อง</Text><View style={styles.chips}>{COMMUNITY_CLUBS.map((club) => <Pressable key={club.id} onPress={() => setClubId(club.id)} style={[styles.chip, clubId === club.id && styles.chipActive]}><Text style={styles.chipText}>{club.name}</Text></Pressable>)}</View><Text style={styles.label}>พื้นที่</Text><View style={styles.chips}>{COMMUNITY_PROVINCES.slice(0, 5).map((item) => <Pressable key={item.id} onPress={() => setProvince(item.id)} style={[styles.chip, province === item.id && styles.chipActive]}><Text style={styles.chipText}>{item.label}</Text></Pressable>)}</View><View style={styles.notice}><MaterialIcons name="info-outline" size={17} color={HOBEE.colors.goldDark} /><Text style={styles.noticeText}>การสร้างกิจกรรมเป็น preview จนกว่าจะมี capacity, attendance และ event backend ที่ตรวจสิทธิ์ได้</Text></View><Pressable style={styles.primary}><Text style={styles.primaryText}>บันทึกเป็นตัวอย่าง</Text><MaterialIcons name="arrow-forward" size={18} color={HOBEE.colors.ink} /></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: HOBEE.space.page }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, title: { color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, content: { gap: 13, padding: HOBEE.space.page, paddingBottom: 42 }, input: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "700", borderRadius: HOBEE.radius.medium, backgroundColor: HOBEE.colors.surface, padding: 14, ...HOBEE.elevation.surface }, description: { minHeight: 130 }, label: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900", marginTop: 3 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 10, paddingVertical: 8 }, chipActive: { backgroundColor: HOBEE.colors.gold }, chipText: { color: HOBEE.colors.ink, fontSize: 11, fontWeight: "800" }, notice: { flexDirection: "row", gap: 7, borderRadius: HOBEE.radius.medium, backgroundColor: HOBEE.atmosphere.skyMist, padding: 11 }, noticeText: { flex: 1, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700", lineHeight: 16 }, primary: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.gold, paddingVertical: 13 }, primaryText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" } });
