import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, type Href } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { CommunityActivityCard } from "@/components/hobee/community-ui";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { COMMUNITY_ACTIVITIES } from "@/lib/community-hub";

export default function CommunityActivitiesScreen() { return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><View style={styles.copy}><Text style={styles.eyebrow}>HOBEE COMMUNITY</Text><Text style={styles.title}>กิจกรรมของชุมชน</Text></View><Pressable onPress={() => router.push("/community/activities/create" as Href)} style={styles.create}><MaterialIcons name="add" size={20} color={HOBEE.colors.ink} /></Pressable></View><FlatList data={COMMUNITY_ACTIVITIES} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} renderItem={({ item }) => <CommunityActivityCard activity={item} onPress={() => router.push(`/community/activities/${item.id}` as Href)} />} ListHeaderComponent={<View style={styles.actions}><Pressable onPress={() => router.push("/community/my-activities" as Href)} style={styles.action}><MaterialIcons name="event-available" size={20} color={HOBEE.colors.botanical} /><Text style={styles.actionText}>กิจกรรมของฉัน</Text></Pressable><Pressable onPress={() => router.push("/community/clubs" as Href)} style={styles.action}><MaterialIcons name="groups" size={20} color={HOBEE.colors.botanical} /><Text style={styles.actionText}>จากชมรม</Text></Pressable></View>} /></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 11, padding: HOBEE.space.page }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, copy: { flex: 1 }, eyebrow: { color: HOBEE.colors.goldDark, fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, title: { color: HOBEE.colors.ink, fontSize: 20, fontWeight: "900", marginTop: 2 }, create: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.gold }, content: { paddingHorizontal: HOBEE.space.page, paddingBottom: 42 }, actions: { flexDirection: "row", gap: 8, marginBottom: 14 }, action: { flex: 1, alignItems: "center", gap: 6, borderRadius: HOBEE.radius.medium, backgroundColor: HOBEE.atmosphere.botanicalMist, padding: 12 }, actionText: { color: HOBEE.colors.ink, fontSize: 11, fontWeight: "900" } });
