import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AppStatusState } from "@/components/hobee/error-screens";
import { ScreenContainer } from "@/components/screen-container";
import { resolveTravelBooking, travelBookingStateLabel } from "@/lib/travel-booking-presentation";
import { goBackOr } from "@/lib/back-navigation";
import { useTravelCatalog } from "@/lib/travel-catalog";

export default function TravelBookingDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { listings } = useTravelCatalog(); const resolved = useMemo(() => resolveTravelBooking(id, listings), [id, listings]);
  if (!resolved) return <ScreenContainer className="items-center justify-center"><AppStatusState icon="search-off" tone="rose" title="ไม่พบรายการทริป" description="กลับไปเลือก booking presentation อีกครั้ง" actionLabel="ทริปของฉัน" onAction={() => router.replace("/travel/my-trips" as never)} /></ScreenContainer>;
  const { booking, listing } = resolved; const canReview = booking.state === "completed";
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => goBackOr(router, "/travel/my-trips")} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>รายละเอียดทริป</Text><View style={styles.back} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Image source={{ uri: listing.images[0] }} style={styles.image} /><View style={styles.summary}><Text style={styles.state}>{travelBookingStateLabel(booking.state)}</Text><Text style={styles.title}>{listing.title}</Text><Text style={styles.location}>{listing.location}</Text><Info icon="event" label="วันเดินทาง" value={booking.dateLabel} /><Info icon="groups" label="ผู้เดินทาง" value={booking.travelersLabel} /><Info icon="payments" label="การชำระเงิน" value={booking.paymentLabel} /><Info icon="storefront" label="ผู้ดำเนินการ" value={booking.operatorLabel} /></View><View style={styles.boundary}><MaterialIcons name="info-outline" size={20} color={HOBEE.colors.travelTeal} /><Text style={styles.boundaryText}>Cancellation, refund และการติดต่อ operator เป็น presentation boundary จนกว่า booking state และ communication policy จาก backend พร้อม</Text></View>{canReview ? <Pressable onPress={() => router.push({ pathname: "/travel/review/[id]", params: { id: booking.id } } as never)} style={({ pressed }) => [styles.primary, pressed && styles.pressed]}><Text style={styles.primaryText}>เขียนรีวิวทริป</Text><MaterialIcons name="rate-review" size={19} color={HOBEE.colors.ink} /></Pressable> : <View style={styles.pending}><MaterialIcons name="schedule" size={19} color={HOBEE.colors.goldDark} /><Text style={styles.pendingText}>จะเปิดการรีวิวเมื่อสถานะทริปเสร็จแล้ว</Text></View>}<Pressable onPress={() => router.push("/support" as never)} style={({ pressed }) => [styles.secondary, pressed && styles.pressed]}><MaterialIcons name="support-agent" size={19} color={HOBEE.colors.travelTeal} /><Text style={styles.secondaryText}>ขอความช่วยเหลือเกี่ยวกับทริป</Text></Pressable></ScrollView></ScreenContainer>;
}
function Info({ icon, label, value }: { icon: keyof typeof MaterialIcons.glyphMap; label: string; value: string }) { return <View style={styles.info}><MaterialIcons name={icon} size={17} color={HOBEE.colors.travelTeal} /><View style={styles.flex}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View></View>; }
const styles = StyleSheet.create({ flex: { flex: 1 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", height: 62, paddingHorizontal: 18 }, back: { alignItems: "center", justifyContent: "center", width: 38, height: 38, borderRadius: 19, backgroundColor: HOBEE.colors.surface }, headerTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, content: { padding: 18, paddingBottom: 40 }, image: { width: "100%", height: 210, borderRadius: 22, backgroundColor: HOBEE.atmosphere.warmCream }, summary: { gap: 12, marginTop: -18, borderRadius: 22, backgroundColor: HOBEE.colors.surface, padding: 17, ...HOBEE.elevation.surface }, state: { color: HOBEE.colors.travelTeal, fontSize: 10, fontWeight: "900" }, title: { marginTop: -5, color: HOBEE.colors.ink, fontSize: 20, lineHeight: 26, fontWeight: "900" }, location: { marginTop: -7, color: HOBEE.colors.muted, fontSize: 12, fontWeight: "700" }, info: { flexDirection: "row", alignItems: "flex-start", gap: 9, borderTopWidth: 1, borderTopColor: "#F0EDE9", paddingTop: 10 }, infoLabel: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700" }, infoValue: { marginTop: 2, color: HOBEE.colors.ink, fontSize: 11, lineHeight: 15, fontWeight: "800" }, boundary: { flexDirection: "row", alignItems: "flex-start", gap: 9, marginTop: 14, borderRadius: 16, backgroundColor: HOBEE.atmosphere.botanicalMist, padding: 12 }, boundaryText: { flex: 1, color: HOBEE.colors.ink, fontSize: 10, lineHeight: 15, fontWeight: "700" }, primary: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, marginTop: 16, borderRadius: 16, backgroundColor: HOBEE.colors.gold, paddingVertical: 13 }, primaryText: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "900" }, pending: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 16, borderRadius: 15, backgroundColor: HOBEE.atmosphere.warmCream, padding: 12 }, pendingText: { color: HOBEE.colors.ink, fontSize: 10, fontWeight: "800" }, secondary: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, marginTop: 10, borderRadius: 16, borderWidth: 1, borderColor: "#B9E1D6", backgroundColor: HOBEE.colors.surface, paddingVertical: 12 }, secondaryText: { color: HOBEE.colors.travelTeal, fontSize: 12, fontWeight: "900" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
