import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { LEARNING_MEMBERSHIP_PLANS } from "@/lib/learning-platform";

export default function LearningMembershipScreen() { return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#0C0D0D]" safeAreaClassName="bg-[#0C0D0D]"><View style={styles.screen}><View style={styles.header}><Pressable onPress={() => router.canGoBack() ? router.back() : router.replace("/learn")} style={styles.iconButton}><MaterialIcons name="arrow-back" size={23} color="#F7F4ED" /></Pressable><Text style={styles.headerTitle}>HOBEE Learning Membership</Text><View style={styles.iconButton} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.hero}><Text style={styles.eyebrow}>LEARNING MEMBERSHIP</Text><Text style={styles.title}>เรียนรู้ต่อเนื่องในจังหวะของคุณ</Text><Text style={styles.copy}>สิทธิ์สมาชิกเป็น presentation เพื่ออธิบายประสบการณ์การเข้าถึงคอร์สและ Live class ก่อนเปิด billing catalogue จริง</Text></View>{LEARNING_MEMBERSHIP_PLANS.map((plan) => <View key={plan.id} style={styles.plan}><View style={styles.planTop}><View><Text style={styles.planTitle}>{plan.title}</Text><Text style={styles.planBilling}>{plan.billingLabel}</Text></View>{plan.savingsLabel ? <View style={styles.badge}><Text style={styles.badgeText}>สิทธิพิเศษ</Text></View> : null}</View><Text style={styles.price}>{plan.price === null ? "ราคาแสดงเมื่อเปิด billing catalogue" : `฿${plan.price}`}</Text><View style={styles.benefits}>{plan.benefits.map((benefit) => <View key={benefit} style={styles.benefit}><MaterialIcons name="check-circle" size={16} color="#92D0A2" /><Text style={styles.benefitText}>{benefit}</Text></View>)}</View><Pressable onPress={() => router.push("/learning/catalogue?access=subscription" as never)} style={({ pressed }) => [styles.action, pressed && styles.pressed]}><Text style={styles.actionText}>ดูคอร์สสำหรับสมาชิก</Text><MaterialIcons name="arrow-forward" size={17} color="#19160E" /></Pressable></View>)}<View style={styles.boundary}><MaterialIcons name="info-outline" size={18} color="#E2BA48" /><Text style={styles.boundaryText}>การสมัคร ชำระเงิน ต่ออายุ และสิทธิ์สมาชิกจริงจะเชื่อมกับ backend และ payment provider ใน phase ถัดไป</Text></View></ScrollView></View></ScreenContainer>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#0C0D0D" }, header: { height: 60, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 15, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#2A2B2A" }, iconButton: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#181A19" }, headerTitle: { color: "#F6F3EC", fontSize: 14, fontWeight: "900" }, content: { gap: 14, padding: 18, paddingBottom: 42 }, hero: { gap: 8, borderRadius: 17, backgroundColor: "#242013", padding: 17 }, eyebrow: { color: "#E2BA48", fontSize: 9, fontWeight: "900", letterSpacing: 1.2 }, title: { color: "#F7F3E9", fontSize: 22, fontWeight: "900", lineHeight: 28 }, copy: { color: "#C5C0B3", fontSize: 11, fontWeight: "600", lineHeight: 17 }, plan: { gap: 12, borderRadius: 17, borderWidth: 1, borderColor: "#3D3A2D", backgroundColor: "#181A19", padding: 15 }, planTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" }, planTitle: { color: "#F4F1E9", fontSize: 15, fontWeight: "900" }, planBilling: { color: "#9C9A94", fontSize: 10, fontWeight: "700", marginTop: 4 }, badge: { borderRadius: 8, backgroundColor: "#39301A", paddingHorizontal: 8, paddingVertical: 5 }, badgeText: { color: "#E7C459", fontSize: 9, fontWeight: "900" }, price: { color: "#D5D1C8", fontSize: 11, fontWeight: "700" }, benefits: { gap: 8 }, benefit: { flexDirection: "row", gap: 8, alignItems: "center" }, benefitText: { color: "#DAD7CF", fontSize: 11, fontWeight: "700" }, action: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, borderRadius: 11, backgroundColor: "#E0B747", paddingVertical: 11 }, actionText: { color: "#19160E", fontSize: 12, fontWeight: "900" }, boundary: { flexDirection: "row", alignItems: "flex-start", gap: 9, borderRadius: 13, backgroundColor: "#161715", padding: 13 }, boundaryText: { flex: 1, color: "#9E9B94", fontSize: 10, fontWeight: "600", lineHeight: 15 }, pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] } });
