import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { MaterialIcons } from "@expo/vector-icons";

import { BackHeader, OrderTimeline, StatusChip } from "@/components/hobee/commerce-ui";
import { HOBEE } from "@/components/hobee/design-tokens";
import { PrimaryButton } from "@/components/hobee/primary-button";
import { ScreenContainer } from "@/components/screen-container";
import { useToast } from "@/contexts/toast-context";
import { addAfterSalesMessage, getMyAfterSalesCase, submitReturnTracking, type AfterSalesCaseDetail } from "@/lib/after-sales";
import { formatThaiBaht } from "@/lib/hobee-data";

const label = (value: string) => value.replaceAll("_", " ");
export default function CaseDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { showToast } = useToast();
  const [record, setRecord] = useState<AfterSalesCaseDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState(""); const [carrier, setCarrier] = useState(""); const [tracking, setTracking] = useState(""); const [saving, setSaving] = useState(false);
  const refresh = () => void getMyAfterSalesCase(id).then(setRecord).catch((cause) => setError(cause instanceof Error ? cause.message : "ไม่สามารถอ่านคำร้องได้")).finally(() => setLoading(false));
  useEffect(refresh, [id]);
  const canAddReturnTracking = useMemo(() => record?.requested_resolution === "return_and_refund" && ["approved", "in_progress"].includes(record.status) && !record.returnShipment?.tracking_number, [record]);
  const sendMessage = async () => { if (!message.trim()) return; setSaving(true); try { await addAfterSalesMessage(id, message); setMessage(""); refresh(); } catch (cause) { showToast(cause instanceof Error ? cause.message : "ไม่สามารถส่งข้อความได้", "error"); } finally { setSaving(false); } };
  const saveTracking = async () => { if (!carrier.trim() || !tracking.trim()) { showToast("กรุณากรอกผู้ให้บริการและเลขติดตาม", "info"); return; } setSaving(true); try { await submitReturnTracking({ caseId: id, carrier, trackingNumber: tracking }); showToast("ส่งเลขติดตามการคืนสินค้าแล้ว"); refresh(); } catch (cause) { showToast(cause instanceof Error ? cause.message : "ไม่สามารถบันทึกเลขติดตามได้", "error"); } finally { setSaving(false); } };
  if (loading) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="items-center justify-center"><ActivityIndicator size="large" color={HOBEE.colors.gold} /></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]" className="px-5" safeAreaClassName="pt-3"><BackHeader title="รายละเอียดคำร้อง" subtitle={record?.case_number ?? "After-sales"} onBack={() => router.back()} />{error || !record ? <View style={styles.error}><Text style={styles.errorText}>{error ?? "ไม่พบคำร้อง"}</Text></View> : <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.hero}><View><Text style={styles.heroType}>{label(record.case_type)}</Text><Text style={styles.heroResolution}>ต้องการ: {label(record.requested_resolution)}</Text></View><StatusChip status={record.status} label={label(record.status)} /></View>
    <Section title="สรุปปัญหา"><Text style={styles.description}>{record.description}</Text>{record.decision_note ? <View style={styles.note}><MaterialIcons name="verified-user" size={19} color={HOBEE.colors.botanical} /><Text style={styles.noteText}>{record.decision_note}</Text></View> : null}</Section>
    <Section title="ไทม์ไลน์คำร้อง"><OrderTimeline steps={record.events.map((event, index) => ({ label: label(event.event_type), value: event.description || new Date(event.created_at).toLocaleString("th-TH"), active: true, last: index === record.events.length - 1 }))} /></Section>
    {record.refund ? <Section title="การคืนเงิน"><View style={styles.card}><Text style={styles.cardLabel}>ยอดที่อนุมัติ/ดำเนินการ</Text><Text style={styles.amount}>{formatThaiBaht(record.refund.amount)}</Text><Text style={styles.cardCopy}>สถานะ: {label(record.refund.status)}{record.refund.completed_at ? ` · ${new Date(record.refund.completed_at).toLocaleString("th-TH")}` : ""}</Text></View></Section> : null}
    {record.returnShipment ? <Section title="การคืนสินค้า"><TrackingCard title="พัสดุส่งคืน" carrier={record.returnShipment.carrier} tracking={record.returnShipment.tracking_number} url={record.returnShipment.tracking_url} status={record.returnShipment.status} /></Section> : null}
    {record.replacementShipment ? <Section title="สินค้าทดแทน"><TrackingCard title="พัสดุสินค้าทดแทน" carrier={record.replacementShipment.provider} tracking={record.replacementShipment.tracking_number} url={record.replacementShipment.tracking_url} status={record.replacementShipment.status} /></Section> : null}
    {canAddReturnTracking ? <Section title="ส่งเลขติดตามการคืนสินค้า"><View style={styles.form}><TextInput value={carrier} onChangeText={setCarrier} placeholder="ผู้ให้บริการขนส่ง" placeholderTextColor={HOBEE.colors.muted} style={styles.input} /><TextInput value={tracking} onChangeText={setTracking} placeholder="เลขติดตามพัสดุ" placeholderTextColor={HOBEE.colors.muted} style={styles.input} /><PrimaryButton label="บันทึกเลขติดตาม" icon="local-shipping" loading={saving} onPress={() => void saveTracking()} /></View></Section> : null}
    <Section title="ข้อความ"><View style={styles.messages}>{record.messages.length ? record.messages.map((item) => <View key={item.id} style={styles.message}><Text style={styles.messageMeta}>{item.visibility === "customer" ? "คุณ" : "ทีม HOBEE"} · {new Date(item.created_at).toLocaleString("th-TH")}</Text><Text style={styles.messageBody}>{item.body}</Text></View>) : <Text style={styles.emptyText}>ยังไม่มีข้อความ</Text>}</View><TextInput value={message} onChangeText={setMessage} placeholder="พิมพ์ข้อความเพิ่มเติม" placeholderTextColor={HOBEE.colors.muted} multiline style={styles.messageInput} /><Pressable onPress={() => void sendMessage()} disabled={saving || !message.trim()} style={({ pressed }) => [styles.send, (!message.trim() || saving) && styles.disabled, pressed && styles.pressed]}><Text style={styles.sendText}>ส่งข้อความ</Text></Pressable></Section>
    {record.evidence.length ? <Section title="หลักฐานที่แนบ"><View style={styles.evidence}>{record.evidence.map((item) => <View key={item.id} style={styles.evidenceRow}><MaterialIcons name={item.media_type === "video" ? "videocam" : "image"} size={20} color={HOBEE.colors.botanical} /><Text numberOfLines={1} style={styles.evidenceName}>{item.file_name}</Text></View>)}</View></Section> : null}
  </ScrollView>}</ScreenContainer>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.title}>{title}</Text>{children}</View>; }
function TrackingCard({ title, carrier, tracking, url, status }: { title: string; carrier: string | null; tracking: string | null; url: string | null; status: string }) { return <Pressable disabled={!url} onPress={() => url && void Linking.openURL(url)} style={({ pressed }) => [styles.card, pressed && url && styles.pressed]}><Text style={styles.cardLabel}>{title}</Text><Text style={styles.tracking}>{carrier || "ผู้ให้บริการ"} · {tracking || "รอเลขติดตาม"}</Text><Text style={styles.cardCopy}>สถานะ: {label(status)}</Text></Pressable>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30 }, hero: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", borderRadius: 24, backgroundColor: HOBEE.colors.nav, padding: 18 }, heroType: { color: "#FFFFFF", fontSize: 19, fontWeight: "900", textTransform: "capitalize" }, heroResolution: { marginTop: 4, color: "#D8D4CF", fontSize: 12, fontWeight: "700" }, section: { marginTop: 23 }, title: { marginBottom: 10, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, description: { color: HOBEE.colors.ink, fontSize: 14, lineHeight: 21 }, note: { flexDirection: "row", gap: 9, marginTop: 12, borderRadius: 16, backgroundColor: "#E2F7EE", padding: 12 }, noteText: { flex: 1, color: HOBEE.colors.botanical, fontSize: 13, lineHeight: 19, fontWeight: "700" }, card: { borderRadius: 20, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 14 }, cardLabel: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "700" }, amount: { marginTop: 5, color: HOBEE.colors.ink, fontSize: 25, fontWeight: "900" }, tracking: { marginTop: 5, color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900" }, cardCopy: { marginTop: 5, color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600" }, form: { gap: 9, borderRadius: 20, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 14 }, input: { height: 48, borderRadius: 14, borderWidth: 1, borderColor: HOBEE.colors.border, color: HOBEE.colors.ink, paddingHorizontal: 12, fontSize: 14 }, messages: { gap: 8 }, message: { borderRadius: 17, backgroundColor: HOBEE.colors.surface, padding: 12 }, messageMeta: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700" }, messageBody: { marginTop: 5, color: HOBEE.colors.ink, fontSize: 14, lineHeight: 20 }, emptyText: { color: HOBEE.colors.muted, fontSize: 13 }, messageInput: { minHeight: 76, marginTop: 10, borderRadius: 17, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, color: HOBEE.colors.ink, padding: 12, textAlignVertical: "top" }, send: { alignItems: "center", marginTop: 8, borderRadius: 15, backgroundColor: HOBEE.colors.gold, paddingVertical: 13 }, sendText: { color: HOBEE.colors.ink, fontWeight: "900" }, evidence: { gap: 7 }, evidenceRow: { flexDirection: "row", alignItems: "center", gap: 9, borderRadius: 15, backgroundColor: HOBEE.colors.surface, padding: 12 }, evidenceName: { flex: 1, color: HOBEE.colors.ink, fontSize: 13, fontWeight: "700" }, error: { borderRadius: 22, backgroundColor: "#FFE8E4", padding: 16 }, errorText: { color: "#B65045", fontWeight: "900" }, disabled: { opacity: 0.45 }, pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] } });
