import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { MaterialIcons } from "@expo/vector-icons";
import { BackHeader, StatusChip } from "@/components/hobee/commerce-ui";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { listMyAfterSalesCases, type AfterSalesCase } from "@/lib/after-sales";

export default function MyCasesScreen() {
  const [cases, setCases] = useState<AfterSalesCase[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const refresh = () => void listMyAfterSalesCases().then(setCases).catch((cause) => setError(cause instanceof Error ? cause.message : "ไม่สามารถอ่านคำร้องได้")).finally(() => setLoading(false));
  useEffect(refresh, []);
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]" className="px-5" safeAreaClassName="pt-3"><BackHeader title="คำร้องของฉัน" subtitle="ติดตามสถานะหลังการขาย" onBack={() => router.back()} right={<Pressable onPress={refresh} style={styles.refresh}><MaterialIcons name="refresh" size={20} color={HOBEE.colors.botanical} /></Pressable>} />{loading ? <View style={styles.center}><ActivityIndicator size="large" color={HOBEE.colors.gold} /></View> : <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{error ? <Text style={styles.error}>{error}</Text> : null}{cases.length ? cases.map((item) => <Pressable key={item.id} onPress={() => router.push(`/claims/${item.id}` as never)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.row}><Text style={styles.number}>{item.case_number}</Text><StatusChip status={item.status} label={item.status.replaceAll("_", " ")} /></View><Text style={styles.type}>{item.case_type.replaceAll("_", " ")}</Text><Text numberOfLines={2} style={styles.description}>{item.description}</Text><Text style={styles.date}>อัปเดต {new Date(item.updated_at).toLocaleString("th-TH")}</Text></Pressable>) : <View style={styles.empty}><MaterialIcons name="assignment-turned-in" size={32} color={HOBEE.colors.botanical} /><Text style={styles.emptyTitle}>ยังไม่มีคำร้อง</Text><Text style={styles.emptyCopy}>หากมีปัญหากับคำสั่งซื้อ ให้เปิดจากหน้ารายละเอียดคำสั่งซื้อ</Text></View>}</ScrollView>}</ScreenContainer>;
}
const styles = StyleSheet.create({ center: { flex: 1, alignItems: "center", justifyContent: "center" }, content: { paddingBottom: 28 }, refresh: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, card: { marginTop: 10, borderRadius: 22, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 15 }, row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, number: { color: HOBEE.colors.botanical, fontSize: 12, fontWeight: "900" }, type: { marginTop: 11, color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900", textTransform: "capitalize" }, description: { marginTop: 5, color: HOBEE.colors.muted, fontSize: 13, lineHeight: 19 }, date: { marginTop: 11, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600" }, error: { color: "#B65045", marginBottom: 10, fontWeight: "800" }, empty: { alignItems: "center", borderRadius: 24, borderWidth: 1, borderStyle: "dashed", borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 28 }, emptyTitle: { marginTop: 10, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, emptyCopy: { marginTop: 5, color: HOBEE.colors.muted, textAlign: "center", lineHeight: 19 }, pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] } });
