import * as ImagePicker from "expo-image-picker";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { MaterialIcons } from "@expo/vector-icons";
import { BackHeader } from "@/components/hobee/commerce-ui";
import { HOBEE } from "@/components/hobee/design-tokens";
import { PrimaryButton } from "@/components/hobee/primary-button";
import { ScreenContainer } from "@/components/screen-container";
import { useToast } from "@/contexts/toast-context";
import { submitAfterSalesCase, uploadAfterSalesEvidence } from "@/lib/after-sales";

const resolutions = ["refund", "partial_refund", "replacement", "reship_missing_item", "return_and_refund"] as const;
const labels: Record<string, string> = { refund: "ขอคืนเงิน", partial_refund: "คืนเงินบางส่วน", replacement: "ขอเปลี่ยนสินค้า", reship_missing_item: "ขอส่งสินค้าเพิ่ม", return_and_refund: "คืนสินค้าและรับเงินคืน" };
export default function NewClaimScreen() {
  const { orderId, itemId, type } = useLocalSearchParams<{ orderId: string; itemId: string; type: string }>(); const { showToast } = useToast();
  const [resolution, setResolution] = useState<(typeof resolutions)[number]>(type === "missing_item" ? "reship_missing_item" : type === "return_request" ? "return_and_refund" : "replacement"); const [description, setDescription] = useState(""); const [asset, setAsset] = useState<ImagePicker.ImagePickerAsset | null>(null); const [submitting, setSubmitting] = useState(false);
  const pickEvidence = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.All, allowsEditing: false, quality: 0.8 }); if (!result.canceled) setAsset(result.assets[0]); };
  const submit = async () => { if (description.trim().length < 8) { showToast("กรุณาอธิบายปัญหาอย่างน้อย 8 ตัวอักษร", "info"); return; } setSubmitting(true); try { const caseId = await submitAfterSalesCase({ orderId, orderItemId: itemId, caseType: type, description, requestedResolution: resolution }); if (asset) await uploadAfterSalesEvidence({ caseId, uri: asset.uri, mediaType: asset.type === "video" ? "video" : "image", fileName: asset.fileName ?? `evidence-${Date.now()}`, mimeType: asset.mimeType, fileSizeBytes: asset.fileSize }); showToast("ส่งคำร้องแล้ว เราจะแจ้งผลให้ทราบ"); router.replace(`/claims/${caseId}` as never); } catch (cause) { showToast(cause instanceof Error ? cause.message : "ไม่สามารถส่งคำร้องได้", "error"); } finally { setSubmitting(false); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]" className="px-5" safeAreaClassName="pt-3"><BackHeader title="แจ้งปัญหาคำสั่งซื้อ" subtitle="กรอกข้อมูลเพื่อให้ช่วยเหลือได้เร็วขึ้น" onBack={() => router.back()} /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.title}>แนวทางการช่วยเหลือ</Text><View style={styles.chips}>{resolutions.map((item) => <Pressable key={item} onPress={() => setResolution(item)} style={[styles.chip, resolution === item && styles.chipActive]}><Text style={[styles.chipText, resolution === item && styles.chipTextActive]}>{labels[item]}</Text></Pressable>)}</View><Text style={styles.title}>รายละเอียดปัญหา</Text><TextInput value={description} onChangeText={setDescription} multiline maxLength={2000} placeholder="เช่น สินค้ารั่วซึมเมื่อเปิดกล่อง และต้องการเปลี่ยนสินค้า" placeholderTextColor={HOBEE.colors.muted} style={styles.input} /><Text style={styles.title}>หลักฐาน (ไม่บังคับ)</Text><Pressable onPress={() => void pickEvidence()} style={({ pressed }) => [styles.evidence, pressed && styles.pressed]}>{asset?.type === "image" ? <Image source={{ uri: asset.uri }} style={styles.preview} /> : <><MaterialIcons name="add-a-photo" size={28} color={HOBEE.colors.botanical} /><Text style={styles.evidenceTitle}>{asset ? asset.fileName ?? "เลือกหลักฐานแล้ว" : "เพิ่มรูปภาพหรือวิดีโอ"}</Text><Text style={styles.evidenceCopy}>อัปโหลดเข้าพื้นที่ส่วนตัวของคำร้องนี้เท่านั้น</Text></>}</Pressable><PrimaryButton label="ส่งคำร้อง" icon="send" loading={submitting} onPress={() => void submit()} style={styles.submit} /></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 32 }, title: { marginTop: 18, marginBottom: 9, color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { borderRadius: 16, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 12, paddingVertical: 10 }, chipActive: { borderColor: HOBEE.colors.botanical, backgroundColor: "#E2F7EE" }, chipText: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "800" }, chipTextActive: { color: HOBEE.colors.botanical }, input: { minHeight: 144, borderRadius: 20, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, color: HOBEE.colors.ink, padding: 14, fontSize: 14, lineHeight: 20, textAlignVertical: "top" }, evidence: { minHeight: 142, alignItems: "center", justifyContent: "center", borderRadius: 22, borderWidth: 1, borderStyle: "dashed", borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 14, overflow: "hidden" }, preview: { width: "100%", height: 172, borderRadius: 15 }, evidenceTitle: { marginTop: 8, color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" }, evidenceCopy: { marginTop: 4, color: HOBEE.colors.muted, fontSize: 11, textAlign: "center" }, submit: { marginTop: 24 }, pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] } });
