import { useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { useSupabaseAuth } from "@/contexts/supabase-auth-context";
import { useToast } from "@/contexts/toast-context";
import { detectAuthIdentifier, mapAuthError } from "@/lib/auth-credentials";

export default function ForgotPasswordScreen() {
  const [email, setEmail] = useState(""); const [sending, setSending] = useState(false); const [sent, setSent] = useState(false);
  const { configured, requestPasswordReset } = useSupabaseAuth(); const { showToast } = useToast();
  const send = async () => { if (detectAuthIdentifier(email) !== "email") { showToast("กรุณากรอกอีเมลที่ถูกต้อง", "error"); return; } setSending(true); try { await requestPasswordReset(email); setSent(true); showToast("ส่งลิงก์ตั้งรหัสผ่านใหม่แล้ว", "success"); } catch (error) { showToast(mapAuthError(error), "error"); } finally { setSending(false); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#FFFDFC]" className="px-6"><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color="#214D2D" /></Pressable><View style={styles.content}><View style={styles.icon}><MaterialIcons name="lock-reset" size={34} color="#D38B19" /></View><Text style={styles.title}>ตั้งรหัสผ่านใหม่</Text><Text style={styles.sub}>กรอกอีเมลที่ใช้สมัคร HOBEE เราจะส่งลิงก์สำหรับตั้งรหัสผ่านใหม่ให้คุณ</Text>{sent ? <View style={styles.success}><MaterialIcons name="mark-email-read" size={24} color="#257347" /><Text style={styles.successText}>ส่งลิงก์แล้ว กรุณาตรวจสอบกล่องจดหมายและเปิดลิงก์บนอุปกรณ์นี้</Text></View> : <><Text style={styles.label}>อีเมล</Text><TextInput value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoCorrect={false} placeholder="name@example.com" placeholderTextColor="#A8AEA2" style={styles.input} editable={configured && !sending} /><Pressable disabled={!configured || sending} onPress={() => void send()} style={[styles.button, (!configured || sending) && styles.disabled]}><Text style={styles.buttonText}>{sending ? "กำลังส่ง..." : "ส่งลิงก์ตั้งรหัสผ่านใหม่"}</Text></Pressable></>}<Pressable onPress={() => router.replace("/auth")} style={styles.secondary}><Text style={styles.secondaryText}>กลับไปเข้าสู่ระบบ</Text></Pressable></View></KeyboardAvoidingView></ScreenContainer>;
}
const styles = StyleSheet.create({ flex:{flex:1}, back:{width:44,height:44,borderRadius:22,alignItems:"center",justifyContent:"center",backgroundColor:"#FFF",borderWidth:1,borderColor:"#ECE5D8"}, content:{flex:1,justifyContent:"center",paddingBottom:74}, icon:{width:74,height:74,borderRadius:37,alignItems:"center",justifyContent:"center",backgroundColor:"#FFF3D6"}, title:{fontSize:30,fontWeight:"900",color:"#214D2D",marginTop:23}, sub:{fontSize:16,lineHeight:24,color:"#6A746A",marginTop:10,marginBottom:28}, label:{fontSize:16,fontWeight:"800",color:"#2A302B",marginBottom:8}, input:{height:57,borderRadius:16,borderWidth:1,borderColor:"#E7E4DC",backgroundColor:"#FFF",paddingHorizontal:16,fontSize:16,color:"#1D3526"}, button:{height:56,borderRadius:28,alignItems:"center",justifyContent:"center",backgroundColor:"#214D2D",marginTop:18}, buttonText:{color:"#FFF",fontSize:16,fontWeight:"900"}, secondary:{alignSelf:"center",padding:18,marginTop:10}, secondaryText:{color:"#CF891C",fontWeight:"900"}, success:{borderRadius:18,backgroundColor:"#F0F8F1",padding:18,flexDirection:"row",gap:12,alignItems:"flex-start"}, successText:{flex:1,color:"#315132",fontSize:14,lineHeight:21,fontWeight:"700"}, disabled:{opacity:0.55} });
