import { useEffect, useState } from "react";
import { KeyboardAvoidingView, Linking, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { useSupabaseAuth } from "@/contexts/supabase-auth-context";
import { useToast } from "@/contexts/toast-context";
import { isPasswordValid, mapAuthError } from "@/lib/auth-credentials";

export default function ResetPasswordScreen() {
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [ready, setReady] = useState(false); const [saving, setSaving] = useState(false);
  const { completePasswordRecovery, updatePassword } = useSupabaseAuth(); const { showToast } = useToast();
  useEffect(() => { const check = async (url: string | null) => { if (!url) return; try { setReady(await completePasswordRecovery(url)); } catch (error) { showToast(mapAuthError(error), "error"); } }; void Linking.getInitialURL().then(check); const subscription = Linking.addEventListener("url", ({ url }) => void check(url)); return () => subscription.remove(); }, [completePasswordRecovery, showToast]);
  const save = async () => { if (!isPasswordValid(password)) { showToast("รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร", "error"); return; } if (password !== confirm) { showToast("รหัสผ่านทั้งสองช่องไม่ตรงกัน", "error"); return; } setSaving(true); try { await updatePassword(password); showToast("ตั้งรหัสผ่านใหม่สำเร็จ", "success"); router.replace("/auth"); } catch (error) { showToast(mapAuthError(error), "error"); } finally { setSaving(false); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#FFFDFC]" className="px-6"><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><View style={styles.content}><View style={styles.icon}><MaterialIcons name="lock-open" size={34} color="#D38B19" /></View><Text style={styles.title}>ตั้งรหัสผ่านใหม่</Text><Text style={styles.sub}>{ready ? "ตั้งรหัสผ่านใหม่เพื่อกลับเข้าสู่ HOBEE" : "เปิดลิงก์ตั้งรหัสผ่านใหม่จากอีเมลบนอุปกรณ์นี้เพื่อดำเนินการต่อ"}</Text>{ready ? <><Text style={styles.label}>รหัสผ่านใหม่</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry autoCapitalize="none" placeholder="อย่างน้อย 6 ตัวอักษร" placeholderTextColor="#A8AEA2" style={styles.input} /><Text style={styles.label}>ยืนยันรหัสผ่านใหม่</Text><TextInput value={confirm} onChangeText={setConfirm} secureTextEntry autoCapitalize="none" placeholder="กรอกรหัสผ่านอีกครั้ง" placeholderTextColor="#A8AEA2" style={styles.input} /><Pressable disabled={saving} onPress={() => void save()} style={[styles.button, saving && styles.disabled]}><Text style={styles.buttonText}>{saving ? "กำลังบันทึก..." : "บันทึกรหัสผ่านใหม่"}</Text></Pressable></> : <Pressable onPress={() => router.replace("/auth/forgot-password")} style={styles.button}><Text style={styles.buttonText}>ขอรับลิงก์ใหม่</Text></Pressable>}</View></KeyboardAvoidingView></ScreenContainer>;
}
const styles = StyleSheet.create({ flex:{flex:1}, content:{flex:1,justifyContent:"center",paddingBottom:74}, icon:{width:74,height:74,borderRadius:37,alignItems:"center",justifyContent:"center",backgroundColor:"#FFF3D6"}, title:{fontSize:30,fontWeight:"900",color:"#214D2D",marginTop:23}, sub:{fontSize:16,lineHeight:24,color:"#6A746A",marginTop:10,marginBottom:28}, label:{fontSize:16,fontWeight:"800",color:"#2A302B",marginBottom:8,marginTop:12}, input:{height:57,borderRadius:16,borderWidth:1,borderColor:"#E7E4DC",backgroundColor:"#FFF",paddingHorizontal:16,fontSize:16,color:"#1D3526"}, button:{height:56,borderRadius:28,alignItems:"center",justifyContent:"center",backgroundColor:"#214D2D",marginTop:20}, buttonText:{color:"#FFF",fontSize:16,fontWeight:"900"}, disabled:{opacity:0.55} });
