import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { HOBEE } from "@/components/hobee/design-tokens";
import { BackHeader, PointsCard } from "@/components/hobee/commerce-ui";
import { EmptyState } from "@/components/hobee/shared-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useSupabaseAuth } from "@/contexts/supabase-auth-context";
import { formatThaiBaht } from "@/lib/hobee-data";
import { loadRewards, type LoyaltyTransaction, type UserCoupon } from "@/lib/loyalty";

type PointsFilter = "all" | "earn" | "redeem";
type CouponFilter = "active" | "used";
export default function RewardsScreen() {
  const { user } = useSupabaseAuth(); const [points, setPoints] = useState(0); const [coupons, setCoupons] = useState<UserCoupon[]>([]); const [transactions, setTransactions] = useState<LoyaltyTransaction[]>([]); const [loading, setLoading] = useState(Boolean(user)); const [pointsFilter, setPointsFilter] = useState<PointsFilter>("all"); const [couponFilter, setCouponFilter] = useState<CouponFilter>("active");
  const refresh = async () => { if (!user) return; setLoading(true); try { const data = await loadRewards(user.id); setPoints(data.points); setCoupons(data.coupons); setTransactions(data.transactions); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, [user]);
  const visibleTransactions = useMemo(() => transactions.filter((item) => pointsFilter === "all" || item.type === pointsFilter), [transactions, pointsFilter]); const visibleCoupons = useMemo(() => coupons.filter((item) => couponFilter === "used" ? Boolean(item.used_at) : !item.used_at), [coupons, couponFilter]);
  if (!user) return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]" className="items-center justify-center px-6"><EmptyState title="สิทธิพิเศษสำหรับสมาชิก" description="เข้าสู่ระบบเพื่อสะสมคะแนนและรับคูปอง HOBEE" onAction={() => router.push("/auth")} actionLabel="เข้าสู่ระบบ" /></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]" className="px-5" safeAreaClassName="pt-3"><BackHeader title="HOBEE Rewards" subtitle="คะแนน ประวัติ และสิทธิพิเศษของคุณ" onBack={() => router.back()} /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>{loading ? <ActivityIndicator color={HOBEE.colors.gold} style={styles.loader} /> : <><PointsCard points={points} /><Section title="ประวัติคะแนน"><Segment options={["all", "earn", "redeem"]} labels={["ทั้งหมด", "ได้รับ", "ใช้คะแนน"]} value={pointsFilter} onChange={(value) => setPointsFilter(value as PointsFilter)} />{visibleTransactions.length ? visibleTransactions.map((transaction) => <TransactionRow key={transaction.id} transaction={transaction} />) : <EmptyState title="ยังไม่มีประวัติคะแนน" description="เมื่อได้รับหรือใช้คะแนน รายการจริงจากระบบจะแสดงที่นี่" />}</Section><Section title="คูปองของฉัน"><Segment options={["active", "used"]} labels={["ใช้ได้", "ใช้แล้ว"]} value={couponFilter} onChange={(value) => setCouponFilter(value as CouponFilter)} />{visibleCoupons.length ? visibleCoupons.map((coupon) => <CouponCard key={`${coupon.id}-${coupon.claimed_at}`} coupon={coupon} />) : <EmptyState title={couponFilter === "active" ? "ยังไม่มีคูปองที่ใช้ได้" : "ยังไม่มีคูปองที่ใช้แล้ว"} description="ข้อมูลคูปองจากระบบจะแสดงที่นี่" />}</Section></>}</ScrollView></ScreenContainer>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.title}>{title}</Text>{children}</View>; }
function Segment({ options, labels, value, onChange }: { options: string[]; labels: string[]; value: string; onChange: (value: string) => void }) { return <View style={styles.segment}>{options.map((option, index) => <Pressable key={option} onPress={() => onChange(option)} style={[styles.segmentButton, option === value && styles.segmentActive]}><Text style={[styles.segmentText, option === value && styles.segmentTextActive]}>{labels[index]}</Text></Pressable>)}</View>; }
function TransactionRow({ transaction }: { transaction: LoyaltyTransaction }) { const positive = transaction.points > 0; return <View style={styles.transaction}><View style={[styles.sign, { backgroundColor: positive ? "#E2F7EE" : "#FFF1C8" }]}><Text style={{ color: positive ? HOBEE.colors.botanical : HOBEE.colors.goldDark, fontWeight: "900" }}>{positive ? "+" : "−"}</Text></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{transaction.type === "earn" ? "ได้รับคะแนน" : transaction.type === "redeem" ? "ใช้คะแนน" : transaction.type === "expire" ? "คะแนนหมดอายุ" : "ปรับคะแนน"}</Text><Text style={styles.rowDetail}>{transaction.note ?? "รายการคะแนน HOBEE"}</Text></View><Text style={[styles.points, { color: positive ? HOBEE.colors.botanical : HOBEE.colors.goldDark }]}>{positive ? "+" : ""}{transaction.points}</Text></View>; }
function CouponCard({ coupon }: { coupon: UserCoupon }) { const discount = coupon.discount_type === "percentage" ? `ลด ${coupon.discount_value}%` : `ลด ${formatThaiBaht(coupon.discount_value)}`; return <View style={[styles.coupon, coupon.used_at && styles.used]}><Text style={styles.code}>{coupon.code} · {discount}</Text><Text style={styles.rowTitle}>{coupon.name}</Text><Text style={styles.rowDetail}>{coupon.used_at ? `ใช้แล้ว ${new Date(coupon.used_at).toLocaleDateString("th-TH")}` : `ขั้นต่ำ ${formatThaiBaht(coupon.minimum_subtotal)}`}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30 }, loader: { marginTop: 32 }, section: { marginTop: 24 }, title: { marginBottom: 10, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, segment: { alignSelf: "flex-start", flexDirection: "row", gap: 4, marginBottom: 10, padding: 4, borderRadius: 14, backgroundColor: "#EDEAE5" }, segmentButton: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 10 }, segmentActive: { backgroundColor: HOBEE.colors.nav }, segmentText: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "800" }, segmentTextActive: { color: "#FFF" }, transaction: { flexDirection: "row", alignItems: "center", gap: 11, marginTop: 9, padding: 13, borderRadius: 18, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface }, sign: { width: 34, height: 34, alignItems: "center", justifyContent: "center", borderRadius: 12 }, rowTitle: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" }, rowDetail: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600" }, points: { fontSize: 16, fontWeight: "900" }, coupon: { marginTop: 9, padding: 15, borderRadius: 19, borderWidth: 1, borderColor: HOBEE.colors.gold, backgroundColor: "#FFF9ED" }, used: { borderColor: HOBEE.colors.border, backgroundColor: "#F3F1ED", opacity: 0.75 }, code: { marginBottom: 8, color: HOBEE.colors.goldDark, fontSize: 12, fontWeight: "900" } });
