import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useEffect, useState } from "react";

import { HOBEE } from "@/components/hobee/design-tokens";
import { BackHeader, PointsCard } from "@/components/hobee/commerce-ui";
import { EmptyState } from "@/components/hobee/shared-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useSupabaseAuth } from "@/contexts/supabase-auth-context";
import { formatThaiBaht } from "@/lib/hobee-data";
import { loadRewards, type UserCoupon } from "@/lib/loyalty";

export default function RewardsScreen() { const { user } = useSupabaseAuth(); const [points, setPoints] = useState(0); const [coupons, setCoupons] = useState<UserCoupon[]>([]); const [loading, setLoading] = useState(Boolean(user)); useEffect(() => { if (!user) return; void loadRewards(user.id).then((data) => { setPoints(data.points); setCoupons(data.coupons); }).finally(() => setLoading(false)); }, [user]); if (!user) return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]" className="items-center justify-center px-6"><EmptyState title="สิทธิพิเศษสำหรับสมาชิก" description="เข้าสู่ระบบเพื่อสะสมคะแนนและรับคูปอง HOBEE" onAction={() => router.push("/auth")} actionLabel="เข้าสู่ระบบ" /></ScreenContainer>; return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]" className="px-5" safeAreaClassName="pt-3"><BackHeader title="HOBEE Rewards" subtitle="คะแนนและสิทธิพิเศษของคุณ" onBack={() => router.back()} /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><PointsCard points={points} /><View style={styles.filter}><Text style={styles.filterLabel}>สิทธิพิเศษของฉัน</Text><View style={styles.filterPill}><Text style={styles.filterText}>คูปองที่ใช้ได้</Text></View></View>{loading ? <ActivityIndicator color={HOBEE.colors.gold} style={styles.loader} /> : coupons.length ? coupons.map((coupon) => <CouponCard key={coupon.id} coupon={coupon} />) : <EmptyState title="ยังไม่มีคูปองที่ใช้ได้" description="คูปองและข้อเสนอจะปรากฏที่นี่เมื่อได้รับสิทธิ์" />}</ScrollView></ScreenContainer>; }
function CouponCard({ coupon }: { coupon: UserCoupon }) { const discount = coupon.discount_type === "percentage" ? `ลด ${coupon.discount_value}%` : `ลด ${formatThaiBaht(coupon.discount_value)}`; return <View style={styles.coupon}><View style={styles.couponTop}><Text style={styles.couponCode}>{coupon.code}</Text><Text style={styles.couponDiscount}>{discount}</Text></View><Text style={styles.couponName}>{coupon.name}</Text><Text style={styles.couponDetail}>ขั้นต่ำ {formatThaiBaht(coupon.minimum_subtotal)} {coupon.ends_at ? `· ใช้ได้ถึง ${new Date(coupon.ends_at).toLocaleDateString("th-TH")}` : ""}</Text></View>; }
const styles = StyleSheet.create({ content: { gap: 13, paddingBottom: 30 }, filter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 13 }, filterLabel: { color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, filterPill: { borderRadius: 14, backgroundColor: "#E2F7EE", paddingHorizontal: 10, paddingVertical: 7 }, filterText: { color: HOBEE.colors.botanical, fontSize: 11, fontWeight: "900" }, loader: { marginTop: 28 }, coupon: { borderRadius: 22, borderWidth: 1, borderColor: HOBEE.colors.gold, backgroundColor: "#FFF9ED", padding: 16 }, couponTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, couponCode: { color: HOBEE.colors.goldDark, fontSize: 12, fontWeight: "900", letterSpacing: 1 }, couponDiscount: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, couponName: { marginTop: 13, color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, couponDetail: { marginTop: 5, color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600" } });
