import { useEffect, useState } from "react";
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";

import { ScreenContainer } from "@/components/screen-container";
import { formatThaiBaht } from "@/lib/hobee-data";
import { getMyOrder, listOrderShipments, orderStatusLabel, paymentStatusLabel, type HobeeOrder, type Shipment } from "@/lib/orders";

const shipmentStatus: Record<string, string> = { label_created: "สร้างใบจัดส่งแล้ว", pickup_scheduled: "นัดรับพัสดุแล้ว", in_transit: "อยู่ระหว่างจัดส่ง", out_for_delivery: "กำลังนำจ่าย", delivered: "ส่งสำเร็จ", failed: "จัดส่งไม่สำเร็จ", returned: "ตีกลับผู้ส่ง" };

export default function OrderDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [order, setOrder] = useState<HobeeOrder | null>(null); const [shipments, setShipments] = useState<Shipment[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([getMyOrder(id), listOrderShipments(id)]).then(([nextOrder, nextShipments]) => { setOrder(nextOrder); setShipments(nextShipments); }).catch((cause) => setError(cause instanceof Error ? cause.message : "ไม่สามารถอ่านคำสั่งซื้อได้")); }, [id]);
  if (!order && !error) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="items-center justify-center"><ActivityIndicator color="#C98716" size="large" /></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5" safeAreaClassName="pt-3"><View className="mb-5 flex-row items-center gap-3"><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color="#17352A" /></Pressable><View><Text className="text-2xl font-black text-foreground">รายละเอียดคำสั่งซื้อ</Text><Text className="mt-0.5 text-sm text-muted">{order?.order_number ?? "ไม่พบคำสั่งซื้อ"}</Text></View></View>{error ? <View className="rounded-2xl border border-error bg-[#FFF0EE] p-5"><Text className="font-black text-error">{error}</Text></View> : <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View className="rounded-2xl bg-[#17352A] p-5"><Text className="text-sm text-white/70">ยอดคำสั่งซื้อ</Text><Text className="mt-1 text-3xl font-black text-white">{formatThaiBaht(order!.total)}</Text><Text className="mt-2 text-sm text-white/70">{new Date(order!.created_at).toLocaleString("th-TH")}</Text></View><Text className="mt-6 text-base font-black text-foreground">สถานะคำสั่งซื้อ</Text><View className="mt-3 rounded-2xl border border-border bg-surface p-4"><Timeline label="ชำระเงิน" value={paymentStatusLabel(order!.payment_status)} active={order!.payment_status === "paid"} /><Timeline label="คำสั่งซื้อ" value={orderStatusLabel(order!.status)} active={order!.status !== "pending"} /><Timeline label="การจัดส่ง" value={order!.status === "shipped" || order!.status === "delivered" ? orderStatusLabel(order!.status) : "รอผู้ขายจัดส่ง"} active={["shipped", "delivered"].includes(order!.status)} /></View><Text className="mt-6 text-base font-black text-foreground">ติดตามพัสดุ</Text>{shipments.length ? shipments.map((shipment) => <View key={shipment.id} className="mt-3 rounded-2xl border border-border bg-surface p-4"><View className="flex-row items-center gap-3"><View className="h-10 w-10 items-center justify-center rounded-xl bg-[#F5EBCF]"><MaterialIcons name="local-shipping" size={22} color="#C98716" /></View><View className="flex-1"><Text className="font-black text-foreground">{shipment.provider.toUpperCase()}</Text><Text className="mt-0.5 text-sm text-muted">{shipmentStatus[shipment.status] ?? shipment.status}</Text></View></View><View className="mt-4 flex-row items-center justify-between rounded-xl bg-background px-3 py-2.5"><Text className="font-bold text-foreground">{shipment.tracking_number}</Text>{shipment.tracking_url ? <Pressable onPress={() => void Linking.openURL(shipment.tracking_url!)} style={({ pressed }) => pressed && styles.pressed}><Text className="text-sm font-black text-primary">ติดตาม</Text></Pressable> : null}</View></View>) : <View className="mt-3 rounded-2xl border border-dashed border-border bg-surface p-5"><Text className="text-sm text-muted">ผู้ขายจะเพิ่มเลขติดตามพัสดุหลังส่งสินค้า</Text></View>}</ScrollView>}</ScreenContainer>;
}

function Timeline({ label, value, active }: { label: string; value: string; active: boolean }) { return <View className="flex-row gap-3 border-b border-border py-3 last:border-b-0"><View className={`mt-0.5 h-5 w-5 items-center justify-center rounded-full ${active ? "bg-success" : "bg-[#E8E0D0]"}`}><MaterialIcons name={active ? "check" : "circle"} size={12} color="#FFFFFF" /></View><View><Text className="font-bold text-foreground">{label}</Text><Text className="mt-0.5 text-sm text-muted">{value}</Text></View></View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 28 }, back: { height: 42, width: 42, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#E8E0D0", borderRadius: 21, backgroundColor: "#FFFFFF" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
