import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";

import { HOBEE } from "@/components/hobee/design-tokens";
import { BackHeader, InfoRow, OrderTimeline, StatusChip, SummaryRow } from "@/components/hobee/commerce-ui";
import { ScreenContainer } from "@/components/screen-container";
import { formatThaiBaht } from "@/lib/hobee-data";
import { getMyOrder, listOrderShipments, orderStatusLabel, paymentStatusLabel, type HobeeOrder, type Shipment } from "@/lib/orders";

const shipmentStatus: Record<string, string> = { label_created: "สร้างใบจัดส่งแล้ว", pickup_scheduled: "นัดรับพัสดุแล้ว", in_transit: "อยู่ระหว่างจัดส่ง", out_for_delivery: "กำลังนำจ่าย", delivered: "ส่งสำเร็จ", failed: "จัดส่งไม่สำเร็จ", returned: "ตีกลับผู้ส่ง" };

export default function OrderDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [order, setOrder] = useState<HobeeOrder | null>(null); const [shipments, setShipments] = useState<Shipment[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([getMyOrder(id), listOrderShipments(id)]).then(([nextOrder, nextShipments]) => { setOrder(nextOrder); setShipments(nextShipments); }).catch((cause) => setError(cause instanceof Error ? cause.message : "ไม่สามารถอ่านคำสั่งซื้อได้")); }, [id]);
  if (!order && !error) return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="items-center justify-center"><ActivityIndicator color={HOBEE.colors.gold} size="large" /></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F8F7F5]" className="px-5" safeAreaClassName="pt-3"><BackHeader title="รายละเอียดคำสั่งซื้อ" subtitle={order?.order_number ?? "ไม่พบคำสั่งซื้อ"} onBack={() => router.back()} />{error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text></View> : <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.hero}><View><Text style={styles.heroLabel}>ยอดคำสั่งซื้อ</Text><Text style={styles.heroTotal}>{formatThaiBaht(order!.total)}</Text><Text style={styles.heroDate}>{new Date(order!.created_at).toLocaleString("th-TH")}</Text></View><StatusChip status={order!.status} label={orderStatusLabel(order!.status)} /></View><Section title="สถานะคำสั่งซื้อ"><OrderTimeline steps={[{ label: "สร้างคำสั่งซื้อ", value: "รับคำสั่งซื้อแล้ว", active: true }, { label: "การชำระเงิน", value: paymentStatusLabel(order!.payment_status), active: order!.payment_status === "paid" }, { label: "กำลังเตรียมสินค้า", value: order!.status === "processing" ? orderStatusLabel(order!.status) : "รอการดำเนินการ", active: ["processing", "shipped", "delivered"].includes(order!.status) }, { label: "การจัดส่ง", value: ["shipped", "delivered"].includes(order!.status) ? orderStatusLabel(order!.status) : "รอผู้ขายจัดส่ง", active: ["shipped", "delivered"].includes(order!.status), last: true }]} /></Section><Section title="ติดตามพัสดุ">{shipments.length ? shipments.map((shipment) => <View key={shipment.id} style={styles.shipment}><InfoRow icon="local-shipping" label={shipment.provider.toUpperCase()} value={shipmentStatus[shipment.status] ?? shipment.status} /><View style={styles.tracking}><Text style={styles.trackingNumber}>{shipment.tracking_number}</Text>{shipment.tracking_url ? <Pressable onPress={() => void Linking.openURL(shipment.tracking_url!)}><Text style={styles.trackingAction}>ติดตามพัสดุ</Text></Pressable> : null}</View></View>) : <View style={styles.emptyShipment}><Text style={styles.emptyShipmentText}>ผู้ขายจะเพิ่มเลขติดตามพัสดุหลังส่งสินค้า</Text></View>}</Section><Section title="สรุปการชำระเงิน"><View style={styles.summary}><SummaryRow label="ยอดคำสั่งซื้อ" value={formatThaiBaht(order!.total)} emphasis /><SummaryRow label="สถานะการชำระเงิน" value={paymentStatusLabel(order!.payment_status)} /></View></Section></ScrollView>}</ScreenContainer>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 30 }, hero: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", borderRadius: 24, backgroundColor: HOBEE.colors.nav, padding: 19 }, heroLabel: { color: "#D8D4CF", fontSize: 12, fontWeight: "700" }, heroTotal: { marginTop: 5, color: "#FFFFFF", fontSize: 29, fontWeight: "900" }, heroDate: { marginTop: 6, color: "#D8D4CF", fontSize: 11, fontWeight: "600" }, section: { marginTop: 24 }, sectionTitle: { marginBottom: 10, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, shipment: { marginTop: 10, borderRadius: 22, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 14 }, tracking: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 14, borderRadius: 14, backgroundColor: HOBEE.colors.canvas, paddingHorizontal: 12, paddingVertical: 10 }, trackingNumber: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, trackingAction: { color: HOBEE.colors.botanical, fontSize: 13, fontWeight: "900" }, emptyShipment: { borderRadius: 21, borderWidth: 1, borderStyle: "dashed", borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 16 }, emptyShipmentText: { color: HOBEE.colors.muted, fontSize: 13 }, summary: { borderRadius: 22, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 16 }, error: { borderRadius: 22, backgroundColor: "#FFE8E4", padding: 16 }, errorText: { color: "#B65045", fontWeight: "900" } });
