export type BackRule = { title: string; fallback: string };

const ROUTE_RULES: Record<string, BackRule> = {
  cart: { title: "ตะกร้าสินค้า", fallback: "/(tabs)/shop" }, checkout: { title: "ชำระเงิน", fallback: "/cart" }, "checkout/address": { title: "ที่อยู่จัดส่ง", fallback: "/checkout" }, favorites: { title: "สินค้าที่ชื่นชอบ", fallback: "/(tabs)/account" }, rewards: { title: "รางวัลของฉัน", fallback: "/(tabs)/account" },
  "product/[id]": { title: "รายละเอียดสินค้า", fallback: "/(tabs)/shop" }, "story/[id]": { title: "เรื่องราว HOBEE", fallback: "/(tabs)/discover" }, "travel/[id]": { title: "รายละเอียดทริป", fallback: "/travel" }, "travel/local-life": { title: "Local Life", fallback: "/travel" }, "travel/my-province": { title: "จังหวัดของฉัน", fallback: "/travel" }, "travel/restaurants": { title: "ร้านอาหาร", fallback: "/travel" }, "travel/trip-builder": { title: "วางแผนทริป", fallback: "/travel" }, "travel/book/[id]": { title: "จองทริป", fallback: "/travel" }, "travel/voucher/[id]": { title: "Booking Preview", fallback: "/travel/my-trips" }, "travel/my-trips": { title: "ทริปของฉัน", fallback: "/travel" }, "travel/bookings/[id]": { title: "รายละเอียดทริป", fallback: "/travel/my-trips" }, "travel/review/[id]": { title: "รีวิวทริป", fallback: "/travel/my-trips" }, "travel/visitor": { title: "International Visitor", fallback: "/travel" }, "travel/search": { title: "ค้นหาทริป", fallback: "/travel" }, "travel/safety": { title: "Travel Safety", fallback: "/travel" }, "travel/food/index": { title: "ร้านอาหาร", fallback: "/travel" }, "travel/food/cart": { title: "Food Cart", fallback: "/travel/food" }, "travel/food/orders": { title: "Food Orders", fallback: "/travel/food" }, "travel/food/reservations": { title: "My Reservations", fallback: "/travel/food" }, "travel/food/saved": { title: "Saved Food", fallback: "/travel/food" }, "travel/food/map": { title: "Restaurant Map", fallback: "/travel/food" }, "travel/food/search": { title: "ค้นหาร้านอาหาร", fallback: "/travel/food" }, "travel/food/collections": { title: "Food Collections", fallback: "/travel/food" }, "travel/food/safety": { title: "Food Safety", fallback: "/travel/food" }, "restaurant-merchant/index": { title: "Restaurant Merchant", fallback: "/my-hobee" },
  "learning/[id]": { title: "รายละเอียดบทเรียน", fallback: "/(tabs)/learn" }, "learning/my-learning": { title: "การเรียนรู้ของฉัน", fallback: "/(tabs)/learn" }, "learning/catalogue": { title: "คอร์สทั้งหมด", fallback: "/(tabs)/learn" }, "learning/search": { title: "ค้นหาการเรียนรู้", fallback: "/(tabs)/learn" }, "learning/category/[id]": { title: "หมวดการเรียนรู้", fallback: "/learning/catalogue" }, "learning/membership": { title: "Learning Membership", fallback: "/(tabs)/learn" }, "learning/teacher/[id]": { title: "ผู้สอน", fallback: "/(tabs)/learn" }, "learning/events": { title: "กิจกรรมการเรียนรู้", fallback: "/(tabs)/learn" }, "learning/events/[id]": { title: "รายละเอียดกิจกรรม", fallback: "/learning/events" }, "learning/events/booking/[id]": { title: "Event Booking", fallback: "/learning/events" }, "learning/events/success/[id]": { title: "Booking Success", fallback: "/learning/events" }, "learning/events/ticket/[id]": { title: "Event Ticket", fallback: "/learning/events" }, "learning/calendar": { title: "Learning Calendar", fallback: "/(tabs)/learn" }, "learning/live/[id]": { title: "Live Class", fallback: "/learning/events" }, "learning/sessions/[id]": { title: "1-on-1 Session", fallback: "/(tabs)/learn" }, "orders/index": { title: "คำสั่งซื้อ", fallback: "/(tabs)/account" }, "orders/[id]": { title: "รายละเอียดคำสั่งซื้อ", fallback: "/orders" }, "payment/[orderId]": { title: "ชำระเงิน", fallback: "/orders" },
  "stores/index": { title: "ร้านค้า", fallback: "/(tabs)" }, "stores/[id]": { title: "รายละเอียดร้าน", fallback: "/stores" }, "stores/[id]/preorder": { title: "สั่งล่วงหน้า", fallback: "/stores" }, "stores/saved": { title: "ร้านที่บันทึก", fallback: "/stores" }, "stores/orders/[reference]": { title: "สถานะคำสั่งร้านค้า", fallback: "/stores" }, "stores/orders/[reference]/review": { title: "รีวิวร้าน", fallback: "/stores" },
  "admin/index": { title: "HOBEE Admin", fallback: "/(tabs)/account" }, "admin/products": { title: "จัดการสินค้า", fallback: "/admin" }, "admin/orders": { title: "จัดการคำสั่งซื้อ", fallback: "/admin" }, "admin/stores": { title: "ร้านค้า / Seller", fallback: "/admin" }, "admin/travel": { title: "จัดการทริปและที่พัก", fallback: "/admin" },
};

export function shouldShowBackHeader(routeName: string) { return !["(tabs)", "auth", "oauth/callback", "auth/callback", "payment/callback", "travel", "travel/index"].includes(routeName) && !routeName.startsWith("my-hobee"); }
export function getBackRule(routeName: string): BackRule { return ROUTE_RULES[routeName] ?? { title: "HOBEE", fallback: "/(tabs)" }; }

type RouterWithBack = { canGoBack?: () => boolean; back: () => void; replace: (...args: any[]) => void };
export function goBackOr(router: RouterWithBack, fallback: string) { if (router.canGoBack?.()) router.back(); else router.replace(fallback); }
