import { hobeeStories } from "./hobee-data";

export type CommunityProvinceId = "narathiwat" | "pattani" | "yala" | "songkhla" | "satun" | "phuket" | "other";
export type CommunityFilter = "all" | "story" | "club" | "activity" | "job" | "trip";
export type CommunityEntityType = "STORY" | "CLUB" | "ACTIVITY" | "JOB" | "TRIP" | "CREATOR" | "ANNOUNCEMENT" | "STORE" | "RESTAURANT" | "DESTINATION" | "COURSE" | "EVENT";
export type CommunityMembershipState = "not_joined" | "joined" | "pending" | "private" | "admin" | "moderator" | "suspended";
export type CommunityVisibility = "public" | "followers" | "group" | "draft";
export type CommunityReportReason = "spam" | "scam" | "harassment" | "hate_abuse" | "inappropriate" | "false_information" | "illegal_activity" | "other";

export type CommunityReference = { type: CommunityEntityType; id: string; label: string; route: string };
export type CommunityPerson = { id: string; name: string; role: string; province: CommunityProvinceId; interests: string[]; avatar: string; kind: "creator" | "member" | "expert"; followState: "not_following" | "following"; bio: string; reference?: CommunityReference };
export type CommunityClub = { id: string; name: string; province: CommunityProvinceId; category: string; image: string; icon: string; description: string; rules: string[]; membershipState: CommunityMembershipState; activityLabel: string; memberLabel: string; tabs: readonly ["feed", "activities", "members", "about"]; tags: string[]; private: boolean };
export type CommunityActivity = { id: string; title: string; category: string; province: CommunityProvinceId; image: string; organizer: string; startsAt: string; endsAt: string; location: string; distanceLabel: string; capacityLabel: string; accessState: "free" | "paid"; joinState: "not_joined" | "joined" | "waitlist"; requirements: string[]; whatToBring: string[]; relatedClubId?: string; reference?: CommunityReference };
export type CommunityJob = { id: string; title: string; organization: string; province: CommunityProvinceId; location: string; jobType: "part_time" | "full_time" | "freelance" | "contract" | "daily" | "internship"; compensationLabel: string; postedLabel: string; closingLabel: string; tags: string[]; appliedState: "not_applied" | "applied" | "reviewing" | "interview" | "offered" | "rejected" | "withdrawn"; description: string; responsibilities: string[]; requirements: string[]; benefits: string[]; contactLabel: string };
export type CommunityTrip = { id: string; title: string; creatorId: string; province: CommunityProvinceId; cover: string; durationLabel: string; budgetLabel: string; tags: string[]; route: string; copyRoute: string };
export type CommunityStory = { id: string; title: string; excerpt: string; cover: string; province: CommunityProvinceId; category: string; dateLabel: string; readTime: string; authorId: string; tags: string[]; route: string; references: CommunityReference[]; source: "hobee_story" | "community_presentation" };
export type CommunityPost = { id: string; type: Extract<CommunityEntityType, "STORY" | "CLUB" | "ACTIVITY" | "JOB" | "TRIP" | "CREATOR" | "ANNOUNCEMENT">; authorId: string; title: string; body: string; image?: string; province: CommunityProvinceId; timeLabel: string; related?: CommunityReference; saveState: boolean; reactionCountLabel: string; commentCountLabel: string; reportState: "available" | "reported" | "removed" };
export type CommunityRecommendation = { id: string; entityType: CommunityEntityType; title: string; subtitle: string; image: string; route: string; badge: string; province: CommunityProvinceId };

export const COMMUNITY_PROVINCES: ReadonlyArray<{ id: CommunityProvinceId; label: string }> = [
  { id: "narathiwat", label: "นราธิวาส" }, { id: "pattani", label: "ปัตตานี" }, { id: "yala", label: "ยะลา" }, { id: "songkhla", label: "สงขลา" }, { id: "satun", label: "สตูล" }, { id: "phuket", label: "ภูเก็ต" }, { id: "other", label: "จังหวัดอื่น" },
];
export const COMMUNITY_FILTERS: ReadonlyArray<{ id: CommunityFilter; label: string; icon: string }> = [
  { id: "all", label: "ทั้งหมด", icon: "apps" }, { id: "story", label: "เรื่องราว", icon: "article" }, { id: "club", label: "ชมรม", icon: "groups" }, { id: "activity", label: "กิจกรรม", icon: "event" }, { id: "job", label: "งาน", icon: "work-outline" }, { id: "trip", label: "ทริป", icon: "luggage" },
];
export const COMMUNITY_QUICK_INTENTS = [
  { label: "อ่านเรื่องดี ๆ", icon: "auto-stories", route: "/community/stories" }, { label: "หาเพื่อน", icon: "person-search", route: "/community/people" }, { label: "เข้าชมรม", icon: "groups", route: "/community/clubs" }, { label: "หากิจกรรม", icon: "event", route: "/community/activities" }, { label: "หางาน", icon: "work-outline", route: "/community/jobs" }, { label: "สมัครงาน", icon: "assignment-ind", route: "/community/jobs" }, { label: "แชร์ทริป", icon: "share", route: "/community/trips" }, { label: "ชุมชนในจังหวัด", icon: "location-city", route: "/community/province/narathiwat" },
] as const;
export const COMMUNITY_TOPICS = ["#ของดีนราธิวาส", "#ฟุตบอล", "#วิ่ง", "#เที่ยวใต้", "#กาแฟ", "#เกษตร", "#ถ่ายภาพ"] as const;

export const COMMUNITY_PEOPLE: CommunityPerson[] = [
  { id: "creator-nisa", name: "นีซา เล่าเรื่องใต้", role: "Creator", province: "narathiwat", interests: ["Local Story", "Food", "Photography"], avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=85", kind: "creator", followState: "not_following", bio: "เล่าเรื่องคนและของดีในพื้นที่ ผ่านภาพและบทสนทนา" },
  { id: "guide-hakim", name: "ฮากิม นักเล่าเส้นทาง", role: "Local Expert", province: "yala", interests: ["Travel", "Camping", "History"], avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=85", kind: "expert", followState: "not_following", bio: "ชวนเดินทางอย่างเข้าใจผู้คนและพื้นที่" },
  { id: "teacher-nur", name: "ครูนูร อับดุลเลาะ", role: "Teacher", province: "pattani", interests: ["Learning", "Community", "Youth"], avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=85", kind: "expert", followState: "following", bio: "ออกแบบการเรียนรู้ที่ต่อยอดเป็นโอกาสของชุมชน", reference: { type: "COURSE", id: "course-local-story", label: "Learning กับ HOBEE", route: "/learning/catalogue" } },
];
export const COMMUNITY_CLUBS: CommunityClub[] = [
  { id: "club-lens-south", name: "Lens of the South", province: "narathiwat", category: "Photography", image: "https://images.unsplash.com/photo-1452780212940-6f5c0d14d848?auto=format&fit=crop&w=900&q=85", icon: "photo-camera", description: "พื้นที่ของคนรักภาพและเรื่องเล่าในชายแดนใต้", rules: ["เคารพเจ้าของเรื่องราว", "ขออนุญาตก่อนถ่ายบุคคล", "แชร์เครดิตภาพเสมอ"], membershipState: "not_joined", activityLabel: "มีกิจกรรมภาพถ่ายที่กำลังเปิดให้ดู", memberLabel: "จำนวนสมาชิกจะแสดงเมื่อ source พร้อม", tabs: ["feed", "activities", "members", "about"], tags: ["Photography", "Local Story"], private: false },
  { id: "club-run-local", name: "HOBEE Run & Health", province: "songkhla", category: "Health / Run", image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=85", icon: "directions-run", description: "วิ่งด้วยกันอย่างปลอดภัยและรู้จักเมืองมากขึ้น", rules: ["ดูแลความปลอดภัย", "ไม่ทิ้งขยะ", "เคารพระดับความพร้อมของเพื่อน"], membershipState: "pending", activityLabel: "กำลังรอผลคำขอเข้าร่วมแบบ presentation", memberLabel: "จำนวนสมาชิกจะแสดงเมื่อ source พร้อม", tabs: ["feed", "activities", "members", "about"], tags: ["Health", "Run"], private: true },
  { id: "club-coffee-kitchen", name: "Coffee & Local Kitchen", province: "satun", category: "Coffee / Cooking", image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=85", icon: "local-cafe", description: "คุยกาแฟ อาหาร และผู้ผลิตรายเล็กในพื้นที่", rules: ["แบ่งปันอย่างสร้างสรรค์", "ไม่โฆษณาหลอกลวง"], membershipState: "joined", activityLabel: "มีเรื่องเล่ากาแฟและ workshop ล่าสุด", memberLabel: "สถานะสมาชิก: เข้าร่วมแล้ว", tabs: ["feed", "activities", "members", "about"], tags: ["Coffee", "Food"], private: false },
];
export const COMMUNITY_ACTIVITIES: CommunityActivity[] = [
  { id: "activity-photo-walk", title: "Photo Walk: ตลาดเก่าและผู้คน", category: "Photography", province: "narathiwat", image: "https://images.unsplash.com/photo-1470214304380-aadaedcfff1b?auto=format&fit=crop&w=900&q=85", organizer: "Lens of the South", startsAt: "2026-09-06T08:00:00+07:00", endsAt: "2026-09-06T11:30:00+07:00", location: "จุดนัดหมายจะแสดงในรายละเอียดกิจกรรม", distanceLabel: "ระยะทางจะแสดงเมื่อ location พร้อม", capacityLabel: "จำนวนผู้เข้าร่วมจะแสดงเมื่อ backend พร้อม", accessState: "free", joinState: "not_joined", requirements: ["กล้องหรือโทรศัพท์", "เคารพชุมชนและความเป็นส่วนตัว"], whatToBring: ["น้ำดื่ม", "อุปกรณ์บันทึกภาพ"], relatedClubId: "club-lens-south" },
  { id: "activity-run-sunset", title: "Sunset Community Run", category: "Health", province: "songkhla", image: "https://images.unsplash.com/photo-1552674605-469f6f14b2ce?auto=format&fit=crop&w=900&q=85", organizer: "HOBEE Run & Health", startsAt: "2026-09-12T17:30:00+07:00", endsAt: "2026-09-12T19:00:00+07:00", location: "เส้นทางการวิ่งจะแสดงเมื่อ event source พร้อม", distanceLabel: "ระยะทางจะแสดงเมื่อ location พร้อม", capacityLabel: "สถานะผู้เข้าร่วมแบบ presentation", accessState: "free", joinState: "waitlist", requirements: ["ตรวจสุขภาพตนเองก่อนร่วม"], whatToBring: ["รองเท้าวิ่ง", "น้ำดื่ม"], relatedClubId: "club-run-local" },
];
export const COMMUNITY_JOBS: CommunityJob[] = [
  { id: "job-local-content", title: "Local Content Assistant", organization: "HOBEE Community Partner", province: "narathiwat", location: "งานในพื้นที่ / รูปแบบยืดหยุ่น", jobType: "freelance", compensationLabel: "ค่าตอบแทนจริงจะแสดงเมื่อผู้ประกาศเปิดเผย", postedLabel: "ประกาศแบบ presentation", closingLabel: "กำหนดปิดรับจะแสดงเมื่อ job source พร้อม", tags: ["Content", "Photography", "Local"], appliedState: "not_applied", description: "ช่วยบันทึกเรื่องราวและกิจกรรมที่เป็นประโยชน์ต่อชุมชน", responsibilities: ["ประสานกิจกรรม", "รวบรวมสื่อที่ได้รับอนุญาต"], requirements: ["สื่อสารภาษาไทยได้ดี", "คุ้นเคยกับพื้นที่"], benefits: ["ต่อยอด portfolio", "ได้ทำงานกับชุมชน"], contactLabel: "ช่องทางติดต่อจะแสดงเมื่อ job backend พร้อม" },
  { id: "job-barista-local", title: "Barista / Community Host", organization: "Local Coffee Partner", province: "satun", location: "สตูล", jobType: "part_time", compensationLabel: "ค่าตอบแทนจริงจะแสดงเมื่อผู้ประกาศเปิดเผย", postedLabel: "ประกาศแบบ presentation", closingLabel: "กำหนดปิดรับจะแสดงเมื่อ job source พร้อม", tags: ["Coffee", "Service", "Part-time"], appliedState: "reviewing", description: "ดูแลประสบการณ์ลูกค้าและกิจกรรมกาแฟในชุมชน", responsibilities: ["ชงกาแฟ", "ต้อนรับผู้ร่วมกิจกรรม"], requirements: ["สนใจงานบริการ", "เรียนรู้ได้"], benefits: ["ฝึกทักษะบริการ"], contactLabel: "ช่องทางติดต่อจะแสดงเมื่อ job backend พร้อม" },
];
export const COMMUNITY_TRIPS: CommunityTrip[] = [
  { id: "trip-community-coast", title: "เส้นทางชุมชนริมฝั่ง", creatorId: "guide-hakim", province: "satun", cover: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85", durationLabel: "ระยะเวลาใน Trip Builder เดิม", budgetLabel: "งบประมาณประมาณการจาก Trip Builder", tags: ["Coast", "Community", "Local Food"], route: "/travel/trip-builder", copyRoute: "/travel/trip-builder" },
];
export const COMMUNITY_STORIES: CommunityStory[] = hobeeStories.map((story, index) => ({ id: story.id, title: story.title, excerpt: story.description, cover: story.image, province: (["narathiwat", "pattani", "satun"] as CommunityProvinceId[])[index % 3], category: story.label, dateLabel: "วันที่เผยแพร่จะแสดงเมื่อ story source พร้อม", readTime: story.readTime, authorId: COMMUNITY_PEOPLE[index % COMMUNITY_PEOPLE.length].id, tags: ["#ของดีท้องถิ่น", "#ชุมชน"], route: `/story/${story.id}`, references: index === 0 ? [{ type: "STORE", id: "local-store", label: "Local Store", route: "/stores" }] : index === 1 ? [{ type: "RESTAURANT", id: "food", label: "Food Experience", route: "/travel/food" }] : [{ type: "TRIP", id: "trip-builder", label: "Travel Trip Builder", route: "/travel/trip-builder" }], source: "hobee_story" }));
export const COMMUNITY_POSTS: CommunityPost[] = [
  { id: "post-story-1", type: "STORY", authorId: "creator-nisa", title: COMMUNITY_STORIES[0].title, body: COMMUNITY_STORIES[0].excerpt, image: COMMUNITY_STORIES[0].cover, province: "narathiwat", timeLabel: "เวลาที่เผยแพร่จะแสดงเมื่อ source พร้อม", related: COMMUNITY_STORIES[0].references[0], saveState: false, reactionCountLabel: "ปฏิกิริยาจะแสดงเมื่อ backend พร้อม", commentCountLabel: "ความคิดเห็นจะแสดงเมื่อ backend พร้อม", reportState: "available" },
  { id: "post-activity-1", type: "ACTIVITY", authorId: "guide-hakim", title: COMMUNITY_ACTIVITIES[0].title, body: "ชวนเรียนรู้เมืองผ่านกิจกรรมที่เคารพผู้คนและพื้นที่", image: COMMUNITY_ACTIVITIES[0].image, province: "narathiwat", timeLabel: "กิจกรรมที่กำลังเปิดให้ดู", related: { type: "ACTIVITY", id: "activity-photo-walk", label: "ดูกิจกรรม", route: "/community/activities/activity-photo-walk" }, saveState: false, reactionCountLabel: "ปฏิกิริยาจะแสดงเมื่อ backend พร้อม", commentCountLabel: "ความคิดเห็นจะแสดงเมื่อ backend พร้อม", reportState: "available" },
];
export const COMMUNITY_RECOMMENDATIONS: CommunityRecommendation[] = [
  ...COMMUNITY_STORIES.slice(0, 2).map((story) => ({ id: `rec-${story.id}`, entityType: "STORY" as const, title: story.title, subtitle: story.excerpt, image: story.cover, route: story.route, badge: "เรื่องราว", province: story.province })),
  { id: "rec-club-lens", entityType: "CLUB", title: COMMUNITY_CLUBS[0].name, subtitle: COMMUNITY_CLUBS[0].description, image: COMMUNITY_CLUBS[0].image, route: "/community/clubs/club-lens-south", badge: "ชมรม", province: "narathiwat" },
  { id: "rec-activity-photo", entityType: "ACTIVITY", title: COMMUNITY_ACTIVITIES[0].title, subtitle: COMMUNITY_ACTIVITIES[0].category, image: COMMUNITY_ACTIVITIES[0].image, route: "/community/activities/activity-photo-walk", badge: "กิจกรรม", province: "narathiwat" },
  { id: "rec-job-content", entityType: "JOB", title: COMMUNITY_JOBS[0].title, subtitle: COMMUNITY_JOBS[0].organization, image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85", route: "/community/jobs/job-local-content", badge: "โอกาส", province: "narathiwat" },
  { id: "rec-trip-coast", entityType: "TRIP", title: COMMUNITY_TRIPS[0].title, subtitle: COMMUNITY_TRIPS[0].durationLabel, image: COMMUNITY_TRIPS[0].cover, route: COMMUNITY_TRIPS[0].route, badge: "ทริปชุมชน", province: "satun" },
];
export const COMMUNITY_REPORT_REASONS: ReadonlyArray<{ id: CommunityReportReason; label: string }> = [
  { id: "spam", label: "สแปม" }, { id: "scam", label: "หลอกลวง" }, { id: "harassment", label: "คุกคาม" }, { id: "hate_abuse", label: "เกลียดชังหรือใช้ความรุนแรง" }, { id: "inappropriate", label: "เนื้อหาไม่เหมาะสม" }, { id: "false_information", label: "ข้อมูลไม่ถูกต้อง" }, { id: "illegal_activity", label: "กิจกรรมผิดกฎหมาย" }, { id: "other", label: "อื่น ๆ" },
];

export function findCommunitySearchResults(query: string) { const normalized = query.trim().toLowerCase(); const pool = [...COMMUNITY_RECOMMENDATIONS, ...COMMUNITY_PEOPLE.map((person) => ({ id: person.id, entityType: "CREATOR" as const, title: person.name, subtitle: person.role, image: person.avatar, route: `/community/people/${person.id}`, badge: person.kind === "creator" ? "Creator" : "คนในพื้นที่", province: person.province }))]; return normalized ? pool.filter((item) => `${item.title} ${item.subtitle} ${item.badge}`.toLowerCase().includes(normalized)) : pool; }
export function getCommunityClub(id?: string) { return COMMUNITY_CLUBS.find((club) => club.id === id); }
export function getCommunityActivity(id?: string) { return COMMUNITY_ACTIVITIES.find((activity) => activity.id === id); }
export function getCommunityJob(id?: string) { return COMMUNITY_JOBS.find((job) => job.id === id); }
export function getCommunityPerson(id?: string) { return COMMUNITY_PEOPLE.find((person) => person.id === id); }
export function getCommunityProvinceLabel(id: CommunityProvinceId) { return COMMUNITY_PROVINCES.find((province) => province.id === id)?.label ?? "จังหวัดอื่น"; }
