import { getOpeningState, getStoreById, type LocalStore } from "./local-stores";
import { foodTimeSlots, getFoodTimeSlot, restaurantListings, type FoodTimeSlot, type RestaurantListing, type RestaurantMenuItem } from "./restaurant-data";

export type FoodDataMode = "presentation" | "live";
export type FoodCategoryId = "all" | "local" | "halal" | "cafe" | "dessert" | "seafood" | "thai" | "southern" | "chinese" | "japanese" | "street" | "family" | "fine" | "healthy" | "vegetarian";
export type FoodQuickFilterId = "open" | "nearby" | "reservation" | "preorder" | "pickup" | "delivery" | "halal" | "parking" | "family" | "wifi";
export type FoodSortId = "nearby" | "rating" | "popular" | "price" | "recommended";
export type FoodFulfilment = "dine_in" | "pickup" | "delivery";
export type FoodOrderState = "placed" | "accepted" | "preparing" | "ready_for_pickup" | "picked_up" | "out_for_delivery" | "delivered" | "completed" | "cancelled";
export type ReservationState = "pending" | "confirmed" | "seated" | "completed" | "cancelled";
export type QueueState = "joined" | "near" | "checked_in" | "seated" | "cancelled";

export type FoodCategory = { id: FoodCategoryId; label: string; icon: string; tone: string };
export type FoodQuickFilter = { id: FoodQuickFilterId; label: string; icon: string };
export type FoodMealExperience = { slot: FoodTimeSlot; headline: string; subtitle: string; quickChips: string[]; collectionLabel: string };
export type RestaurantCapability = { id: FoodFulfilment | "reservation" | "queue"; label: string; enabled: boolean; dataMode: FoodDataMode };
export type RestaurantExperience = { restaurantId: string; localStoreId?: string; cuisine: string[]; priceRange: string; capabilities: RestaurantCapability[]; amenities: string[]; badges: Array<{ label: string; verified: boolean; dataMode: FoodDataMode }>; signatureDishes: string[]; dataMode: FoodDataMode };
export type FoodMenuOption = { id: string; label: string; priceDelta: number; group: string };
export type FoodCartLine = { itemId: string; quantity: number; selectedOptions: FoodMenuOption[]; note?: string };
export type FoodCartQuote = { lines: Array<{ item: RestaurantMenuItem; quantity: number; optionTotal: number; lineTotal: number }>; subtotal: number; serviceFee: number | null; deliveryFee: number | null; discount: number | null; total: number; dataMode: FoodDataMode };
export type FoodReservationPreview = { id: string; restaurantId: string; state: ReservationState; date: string; time: string; guests: number; seatingPreference?: string; dataMode: FoodDataMode };
export type FoodQueuePreview = { id: string; restaurantId: string; state: QueueState; number: string; peopleAhead: number | null; estimatedWaitMinutes: number | null; dataMode: FoodDataMode };
export type FoodOrderPreview = { id: string; restaurantId: string; fulfilment: FoodFulfilment; state: FoodOrderState; scheduledAt?: string; dataMode: FoodDataMode };
export type FoodCollection = { id: string; title: string; subtitle: string; category: FoodCategoryId; image: string; dataMode: FoodDataMode };
export type FoodMerchantModule = { id: "menu" | "availability" | "reservations" | "queue" | "orders" | "reviews" | "staff" | "analytics"; title: string; icon: string; dataMode: FoodDataMode; backendStatus: "presentation" | "backend_pending" };

export const FOOD_CATEGORIES: FoodCategory[] = [
  { id: "all", label: "ทั้งหมด", icon: "apps", tone: "#FFF5DF" }, { id: "local", label: "อาหารท้องถิ่น", icon: "restaurant", tone: "#FDE8D8" }, { id: "halal", label: "Halal", icon: "verified", tone: "#E4F3E9" }, { id: "cafe", label: "คาเฟ่", icon: "local-cafe", tone: "#F5E9DD" }, { id: "dessert", label: "ของหวาน", icon: "cake", tone: "#FBE7EE" }, { id: "seafood", label: "ซีฟู้ด", icon: "set-meal", tone: "#E1F0F5" }, { id: "thai", label: "อาหารไทย", icon: "rice-bowl", tone: "#FBEAD6" }, { id: "southern", label: "อาหารใต้", icon: "local-fire-department", tone: "#FFE3D5" }, { id: "chinese", label: "อาหารจีน", icon: "ramen-dining", tone: "#F3E8D8" }, { id: "japanese", label: "อาหารญี่ปุ่น", icon: "set-meal", tone: "#E6F0F8" }, { id: "street", label: "Street Food", icon: "storefront", tone: "#FFF1CA" }, { id: "family", label: "Family", icon: "family-restroom", tone: "#E7F2EF" }, { id: "fine", label: "Fine Dining", icon: "wine-bar", tone: "#EEE8F5" }, { id: "healthy", label: "Healthy", icon: "spa", tone: "#E8F5E7" }, { id: "vegetarian", label: "Vegetarian", icon: "eco", tone: "#E5F4E8" },
];

export const FOOD_QUICK_FILTERS: FoodQuickFilter[] = [
  { id: "open", label: "เปิดอยู่ตอนนี้", icon: "schedule" }, { id: "nearby", label: "ใกล้ฉัน", icon: "near-me" }, { id: "reservation", label: "จองโต๊ะได้", icon: "event-seat" }, { id: "preorder", label: "สั่งล่วงหน้า", icon: "restaurant-menu" }, { id: "pickup", label: "Pickup", icon: "takeout-dining" }, { id: "delivery", label: "Delivery", icon: "delivery-dining" }, { id: "halal", label: "Halal", icon: "verified" }, { id: "parking", label: "Parking", icon: "local-parking" }, { id: "family", label: "Family Friendly", icon: "family-restroom" }, { id: "wifi", label: "Wi-Fi", icon: "wifi" },
];

export const FOOD_MEAL_EXPERIENCES: FoodMealExperience[] = [
  { slot: "morning", headline: "เช้านี้เริ่มด้วยอะไรดี?", subtitle: "กาแฟ เบเกอรี และมื้อเช้าท้องถิ่นใกล้คุณ", quickChips: ["Breakfast", "Coffee", "Bakery"], collectionLabel: "มื้อเช้าวิถีท้องถิ่น" }, { slot: "lunch", headline: "มื้อเที่ยงนี้กินอะไรดี?", subtitle: "ร้านอร่อย เสิร์ฟไว และอาหารท้องถิ่นสำหรับช่วงพัก", quickChips: ["Quick Lunch", "Local Food", "Office Lunch"], collectionLabel: "ร้านน่ากินช่วงเที่ยง" }, { slot: "afternoon", headline: "บ่ายนี้พักกับของอร่อย", subtitle: "ชาชัก ขนม และคาเฟ่สำหรับช่วงเวลาสบาย ๆ", quickChips: ["Tea", "Dessert", "Cafe"], collectionLabel: "คาเฟ่และของหวาน" }, { slot: "evening", headline: "มื้อเย็นนี้เจออะไรดี?", subtitle: "อาหารครอบครัว ซีฟู้ด และอาหารใต้ที่ยังเปิดอยู่", quickChips: ["Family Dinner", "Seafood", "Grill"], collectionLabel: "มื้อเย็นน่ารวมตัว" }, { slot: "late_night", headline: "หิวดึก กินอะไรดี?", subtitle: "อาหารมื้อดึก Street Food และของหวานสำหรับค่ำคืน", quickChips: ["Late Night", "Street Food", "Dessert"], collectionLabel: "ของกินเปิดดึก" },
];

export const FOOD_COLLECTIONS: FoodCollection[] = [
  { id: "narathiwat-tastes", title: "ของอร่อยนราธิวาส", subtitle: "รสชาติชุมชนและครัวท้องถิ่น", category: "local", image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=85&w=800", dataMode: "presentation" }, { id: "betong-picks", title: "ร้านเด็ดเบตง", subtitle: "ชาชัก โรตี และมื้อสบาย ๆ", category: "cafe", image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=85&w=800", dataMode: "presentation" }, { id: "halal-guide", title: "Halal Food Guide", subtitle: "ข้อมูลป้าย Halal แสดงตาม contract ของร้าน", category: "halal", image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=85&w=800", dataMode: "presentation" },
];

export const FOOD_MERCHANT_MODULES: FoodMerchantModule[] = [
  { id: "orders", title: "Food Orders", icon: "receipt-long", dataMode: "presentation", backendStatus: "backend_pending" }, { id: "reservations", title: "Reservations", icon: "event-seat", dataMode: "presentation", backendStatus: "backend_pending" }, { id: "queue", title: "Queue", icon: "format-list-numbered", dataMode: "presentation", backendStatus: "backend_pending" }, { id: "menu", title: "Menu", icon: "restaurant-menu", dataMode: "presentation", backendStatus: "presentation" }, { id: "availability", title: "Availability", icon: "toggle-on", dataMode: "presentation", backendStatus: "presentation" }, { id: "reviews", title: "Reviews", icon: "reviews", dataMode: "presentation", backendStatus: "presentation" }, { id: "staff", title: "Staff", icon: "groups", dataMode: "presentation", backendStatus: "backend_pending" }, { id: "analytics", title: "Analytics", icon: "insights", dataMode: "presentation", backendStatus: "backend_pending" },
];

const EXPERIENCE_BY_RESTAURANT: Record<string, RestaurantExperience> = {
  "restaurant-wang": { restaurantId: "restaurant-wang", localStoreId: "local-narathiwat-khao-yam", cuisine: ["อาหารใต้", "อาหารท้องถิ่น"], priceRange: "฿", capabilities: [{ id: "dine_in", label: "ทานที่ร้าน", enabled: true, dataMode: "presentation" }, { id: "pickup", label: "Pickup", enabled: true, dataMode: "presentation" }, { id: "delivery", label: "Delivery", enabled: false, dataMode: "presentation" }, { id: "reservation", label: "จองโต๊ะ", enabled: true, dataMode: "presentation" }, { id: "queue", label: "เข้าคิว", enabled: true, dataMode: "presentation" }], amenities: ["Parking", "Family Friendly"], badges: [{ label: "Halal", verified: true, dataMode: "presentation" }, { label: "Local Food", verified: false, dataMode: "presentation" }], signatureDishes: ["ข้าวยำปักษ์ใต้ทรงเครื่อง", "ชาชักเย็นฟองนุ่ม"], dataMode: "presentation" },
  "restaurant-betong": { restaurantId: "restaurant-betong", localStoreId: "local-yala-tea", cuisine: ["คาเฟ่", "อาหารใต้"], priceRange: "฿", capabilities: [{ id: "dine_in", label: "ทานที่ร้าน", enabled: true, dataMode: "presentation" }, { id: "pickup", label: "Pickup", enabled: true, dataMode: "presentation" }, { id: "delivery", label: "Delivery", enabled: true, dataMode: "presentation" }, { id: "reservation", label: "จองโต๊ะ", enabled: false, dataMode: "presentation" }, { id: "queue", label: "เข้าคิว", enabled: true, dataMode: "presentation" }], amenities: ["Wi-Fi"], badges: [{ label: "Halal", verified: true, dataMode: "presentation" }, { label: "Late Night", verified: false, dataMode: "presentation" }], signatureDishes: ["ชาชักเย็นฟองนุ่ม", "โรตีกรอบนม"], dataMode: "presentation" },
};

export function getFoodMealExperience(slot = getFoodTimeSlot()) { return FOOD_MEAL_EXPERIENCES.find((entry) => entry.slot === slot)!; }
export function getRestaurantExperience(restaurantId?: string) { return restaurantId ? EXPERIENCE_BY_RESTAURANT[restaurantId] : undefined; }
export function getRestaurantLocalStore(restaurantId?: string): LocalStore | undefined { const localStoreId = getRestaurantExperience(restaurantId)?.localStoreId; return localStoreId ? getStoreById(localStoreId) : undefined; }
export function restaurantCapabilities(restaurantId?: string) { return getRestaurantExperience(restaurantId)?.capabilities ?? []; }
export function foodMenuOptions(item: RestaurantMenuItem): FoodMenuOption[] { return item.customizationOptions?.flatMap((option) => option.choices.map((choice) => ({ id: `${item.id}:${option.optionName}:${choice.label}`, label: choice.label, priceDelta: choice.extraPrice, group: option.optionName }))) ?? []; }
export function calculateFoodCart(menu: RestaurantMenuItem[], lines: FoodCartLine[], fulfilment: FoodFulfilment): FoodCartQuote { const resolved = lines.filter((line) => line.quantity > 0).map((line) => { const item = menu.find((entry) => entry.id === line.itemId); if (!item) throw new Error("Food menu item not found"); const optionTotal = line.selectedOptions.reduce((sum, option) => sum + option.priceDelta, 0); return { item, quantity: line.quantity, optionTotal, lineTotal: (item.price + optionTotal) * line.quantity }; }); const subtotal = resolved.reduce((sum, line) => sum + line.lineTotal, 0); return { lines: resolved, subtotal, serviceFee: null, deliveryFee: fulfilment === "delivery" ? null : 0, discount: null, total: subtotal, dataMode: "presentation" }; }
export function foodOrderStateLabel(state: FoodOrderState) { return ({ placed: "รับคำสั่งซื้อแล้ว", accepted: "ร้านรับออเดอร์แล้ว", preparing: "กำลังเตรียมอาหาร", ready_for_pickup: "พร้อมรับอาหาร", picked_up: "รับอาหารแล้ว", out_for_delivery: "กำลังจัดส่ง", delivered: "จัดส่งแล้ว", completed: "เสร็จสิ้น", cancelled: "ยกเลิกแล้ว" } as const)[state]; }
export function foodRestaurantMatches(query: string, slot = getFoodTimeSlot(), filters: FoodQuickFilterId[] = [], category: FoodCategoryId = "all") { const normalized = query.trim().toLowerCase(); return restaurantListings.filter((restaurant) => { const experience = getRestaurantExperience(restaurant.id); const opening = getRestaurantLocalStore(restaurant.id) ? getOpeningState(getRestaurantLocalStore(restaurant.id)!) : { isOpen: restaurant.isOpenNow }; const text = `${restaurant.name} ${restaurant.district} ${experience?.cuisine.join(" ") ?? ""}`.toLowerCase(); return (!normalized || text.includes(normalized)) && restaurant.timeSlotsAvailable.includes(slot) && (category === "all" || (category === "halal" && restaurant.isHalalCertified) || experience?.cuisine.some((entry) => entry.toLowerCase().includes(FOOD_CATEGORIES.find((item) => item.id === category)?.label.toLowerCase() ?? "__"))) && (!filters.includes("open") || opening.isOpen) && (!filters.includes("preorder") || restaurant.preorderSupported) && (!filters.includes("halal") || restaurant.isHalalCertified) && (!filters.includes("parking") || restaurant.parkingFriendly) && (!filters.includes("family") || restaurant.familySetAvailable) && (!filters.includes("pickup") || experience?.capabilities.some((item) => item.id === "pickup" && item.enabled)) && (!filters.includes("delivery") || experience?.capabilities.some((item) => item.id === "delivery" && item.enabled)) && (!filters.includes("reservation") || experience?.capabilities.some((item) => item.id === "reservation" && item.enabled)); }); }
export function foodRestaurantMenu(restaurant: RestaurantListing) { return restaurant.menuCategories.flatMap((category) => category.items); }
export const FOOD_TIME_SLOTS = foodTimeSlots;
