import { learningCourses, type LearningCourse } from "./learning-data";

export type LearningAccessType = "free" | "paid" | "subscription" | "seminar" | "live" | "one_on_one";
export type LearningAccessState = "free" | "preview" | "purchase_required" | "subscription_required" | "enrolled" | "completed" | "locked" | "unavailable";
export type LearningEventKind = "seminar" | "workshop" | "event";
export type LearningEventStatus = "upcoming" | "completed" | "cancelled";
export type LiveClassState = "upcoming" | "starting_soon" | "live_now" | "ended" | "replay";
export type LearningCategoryId = "business" | "marketing" | "sales" | "finance" | "leadership" | "technology" | "ai" | "design" | "creator" | "community" | "agriculture" | "food" | "travel" | "language" | "personal" | "other";

export type LearningCategory = { id: LearningCategoryId; label: string; icon: string; tone: string };
export type LearningTeacher = { id: string; name: string; title: string; expertise: string[]; bio: string; avatar: string; cover: string; rating: number; reviewsCount: number; followers: number | null; courseIds: string[]; liveClassIds: string[]; eventIds: string[]; supportsOneOnOne: boolean; dataMode: "presentation" };
export type LearningCourseMetadata = { courseId: string; subtitle: string; accessType: LearningAccessType; accessState: LearningAccessState; price: number | null; compareAtPrice: number | null; promotionLabel?: string; language: string; updatedLabel: string; learnerCount: number | null; teacherId: string; outcomes: string[]; requirements: string[]; audience: string[]; tags: string[]; relatedCourseIds: string[]; freePreviewEpisodeIds: string[]; sectionTitles: string[]; dataMode: "presentation" };
export type LearningBookmark = { id: string; courseId: string; lessonId?: string; timestampSeconds?: number; label: string; createdAt: string };
export type LearningNote = { id: string; courseId: string; lessonId: string; timestampSeconds: number; body: string; createdAt: string; updatedAt: string };
export type LearningCertificate = { id: string; courseId: string; issuedAt: string; certificateNumber: string; dataMode: "presentation" };
export type LearningMembershipPlan = { id: "monthly" | "annual"; title: string; billingLabel: string; price: number | null; savingsLabel?: string; includedCourseIds: string[]; benefits: string[]; current?: boolean; dataMode: "presentation" };
export type LearningEvent = { id: string; kind: LearningEventKind; title: string; subtitle: string; hero: string; teacherId: string; startsAt: string; endsAt: string; mode: "online" | "offline"; venue: string; capacity: number | null; price: number | null; accessState: LearningAccessState; agenda: string[]; ticketTypes: string[]; status: LearningEventStatus; dataMode: "presentation" };
export type LearningLiveClass = { id: string; title: string; subtitle: string; teacherId: string; startsAt: string; durationMinutes: number; learnerCount: number | null; state: LiveClassState; replayAvailable: boolean; resources: string[]; dataMode: "presentation" };
export type LearningOneOnOneService = { id: string; teacherId: string; title: string; durationMinutes: number; price: number | null; topics: string[]; languages: string[]; availabilityLabel: string; dataMode: "presentation" };
export type LearningOneOnOneSession = { id: string; serviceId: string; teacherId: string; startsAt: string; status: "upcoming" | "completed" | "cancelled"; learningGoal: string; dataMode: "presentation" };
export type LearningQuiz = { id: string; courseId: string; title: string; questionCount: number; passingScore: number; dataMode: "presentation" };
export type LearningAssignment = { id: string; courseId: string; title: string; description: string; deadlineLabel: string; status: "pending" | "submitted" | "reviewed"; feedback?: string; dataMode: "presentation" };
export type TeacherLearnerBridge = { teacherId: string; courseIds: string[]; learnerProgressSource: "local_progress" | "backend_pending"; enrollmentSource: "presentation" | "backend_pending"; publishingSource: "presentation" | "backend_pending" };

export const LEARNING_CATEGORIES: LearningCategory[] = [
  { id: "business", label: "Business", icon: "business-center", tone: "#F6E5C6" }, { id: "marketing", label: "Marketing", icon: "campaign", tone: "#FBE0D2" }, { id: "sales", label: "Sales", icon: "point-of-sale", tone: "#E3F1E8" }, { id: "finance", label: "Finance", icon: "account-balance-wallet", tone: "#E5ECF6" }, { id: "leadership", label: "Leadership", icon: "groups", tone: "#EEE5F4" }, { id: "technology", label: "Technology", icon: "memory", tone: "#E1F1F3" }, { id: "ai", label: "AI", icon: "auto-awesome", tone: "#FFF0BF" }, { id: "design", label: "Design", icon: "palette", tone: "#F8E3EC" }, { id: "creator", label: "Creator", icon: "photo-camera", tone: "#FBE8D0" }, { id: "community", label: "Community", icon: "diversity-3", tone: "#E2F1E7" }, { id: "agriculture", label: "Agriculture", icon: "agriculture", tone: "#E5F0D7" }, { id: "food", label: "Food", icon: "restaurant", tone: "#FBE4D4" }, { id: "travel", label: "Travel", icon: "luggage", tone: "#E0EFF2" }, { id: "language", label: "Language", icon: "translate", tone: "#EEE8D8" }, { id: "personal", label: "Personal Growth", icon: "self-improvement", tone: "#E7EEE2" }, { id: "other", label: "Other", icon: "more-horiz", tone: "#ECEAE6" },
];

export const LEARNING_TEACHERS: LearningTeacher[] = [
  { id: "teacher-hobee-academy", name: "HOBEE Academy", title: "Growth & Community Business", expertise: ["Digital Marketing", "Community Business"], bio: "ทีมผู้สอนจาก HOBEE ที่รวบรวมบทเรียนสำหรับผู้ประกอบการและชุมชน", avatar: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=280&q=85", cover: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85", rating: 4.9, reviewsCount: 128, followers: null, courseIds: ["meta-ads-mastery"], liveClassIds: ["live-growth-01"], eventIds: ["event-growth-01"], supportsOneOnOne: false, dataMode: "presentation" },
  { id: "teacher-sofiya", name: "ซอฟียา มะลิ", title: "Food Content Creator", expertise: ["Creator", "Food Storytelling"], bio: "ผู้สอนด้านการเล่าเรื่องอาหารท้องถิ่นและคอนเทนต์ที่เชื่อมชุมชนกับผู้ชม", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=280&q=85", cover: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1200&q=85", rating: 4.8, reviewsCount: 86, followers: null, courseIds: ["halal-food-storytelling"], liveClassIds: ["live-food-01"], eventIds: ["event-food-01"], supportsOneOnOne: true, dataMode: "presentation" },
  { id: "teacher-abdullah", name: "อับดุลเลาะห์ สาและ", title: "SME Finance Coach", expertise: ["Finance", "Small Business"], bio: "โค้ชการเงินสำหรับร้านชุมชนที่ต้องการจัดการต้นทุนและเงินหมุนเวียนอย่างยั่งยืน", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=280&q=85", cover: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=85", rating: 4.7, reviewsCount: 54, followers: null, courseIds: ["community-shop-finance"], liveClassIds: [], eventIds: [], supportsOneOnOne: true, dataMode: "presentation" },
  { id: "teacher-ustaz", name: "อุสตาซ อับดุลรอซัก", title: "Halal Business Educator", expertise: ["Halal Wisdom", "Ethics"], bio: "ผู้สอนด้านจริยธรรมและความรับผิดชอบในการดำเนินธุรกิจฮาลาล", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=280&q=85", cover: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=1200&q=85", rating: 4.9, reviewsCount: 71, followers: null, courseIds: ["halal-business-ethics"], liveClassIds: [], eventIds: [], supportsOneOnOne: false, dataMode: "presentation" },
  { id: "teacher-ameena", name: "ครูอามีนะห์", title: "Arabic for Tourism", expertise: ["Language", "Tourism Service"], bio: "ผู้สอนภาษาอาหรับเชิงการบริการสำหรับร้านอาหาร โรงแรม และการท่องเที่ยว", avatar: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=280&q=85", cover: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=1200&q=85", rating: 4.6, reviewsCount: 39, followers: null, courseIds: ["arabic-for-service"], liveClassIds: [], eventIds: [], supportsOneOnOne: true, dataMode: "presentation" },
];

export const COURSE_METADATA: LearningCourseMetadata[] = [
  { courseId: "meta-ads-mastery", subtitle: "เริ่มต้นวางแผนแคมเปญที่วัดผลได้", accessType: "free", accessState: "enrolled", price: 0, compareAtPrice: null, language: "ไทย", updatedLabel: "อัปเดตบทเรียนล่าสุด", learnerCount: null, teacherId: "teacher-hobee-academy", outcomes: ["ตั้งเป้าหมายแคมเปญ", "อ่านผลลัพธ์เบื้องต้น", "วางแผนกลุ่มเป้าหมาย"], requirements: ["มีบัญชี Meta สำหรับฝึกปฏิบัติ"], audience: ["เจ้าของธุรกิจ", "ผู้เริ่มต้นทำโฆษณา"], tags: ["marketing", "business"], relatedCourseIds: ["halal-food-storytelling", "community-shop-finance"], freePreviewEpisodeIds: ["meta-ads-01"], sectionTitles: ["พื้นฐานการโฆษณา", "ตั้งค่าและวัดผล"], dataMode: "presentation" },
  { courseId: "halal-food-storytelling", subtitle: "ทำให้อาหารท้องถิ่นมีเรื่องเล่าที่คนจดจำ", accessType: "paid", accessState: "purchase_required", price: null, compareAtPrice: null, promotionLabel: "ราคาและโปรโมชั่นจะแสดงเมื่อเปิด catalogue จริง", language: "ไทย", updatedLabel: "อัปเดตคอร์สล่าสุด", learnerCount: null, teacherId: "teacher-sofiya", outcomes: ["หาเรื่องเล่าของเมนู", "ถ่ายภาพด้วยมือถือ", "เขียนแคปชัน"], requirements: ["โทรศัพท์ที่มีกล้อง"], audience: ["Creator", "ร้านอาหารชุมชน"], tags: ["food", "creator"], relatedCourseIds: ["meta-ads-mastery"], freePreviewEpisodeIds: ["food-story-01"], sectionTitles: ["เรื่องเล่าจากอาหาร", "การถ่ายและการสื่อสาร"], dataMode: "presentation" },
  { courseId: "community-shop-finance", subtitle: "จัดเงินร้านให้เห็นต้นทุนและทางเติบโต", accessType: "subscription", accessState: "subscription_required", price: null, compareAtPrice: null, language: "ไทย", updatedLabel: "เนื้อหาสำหรับสมาชิก", learnerCount: null, teacherId: "teacher-abdullah", outcomes: ["แยกเงินธุรกิจ", "คำนวณต้นทุน", "วางเงินหมุนเวียน"], requirements: ["เตรียมข้อมูลรายรับรายจ่าย"], audience: ["ร้านชุมชน", "ผู้ประกอบการรายย่อย"], tags: ["finance", "business"], relatedCourseIds: ["meta-ads-mastery"], freePreviewEpisodeIds: ["finance-01"], sectionTitles: ["เงินธุรกิจ", "ต้นทุนและกระแสเงินสด"], dataMode: "presentation" },
  { courseId: "halal-business-ethics", subtitle: "สร้างความไว้วางใจผ่านจริยธรรมที่ใช้ได้จริง", accessType: "seminar", accessState: "preview", price: null, compareAtPrice: null, language: "ไทย", updatedLabel: "Seminar replay presentation", learnerCount: null, teacherId: "teacher-ustaz", outcomes: ["สื่อสารอย่างรับผิดชอบ", "วางหลักคิดธุรกิจฮาลาล"], requirements: [], audience: ["ผู้ประกอบการ", "ผู้สนใจธุรกิจฮาลาล"], tags: ["community", "personal"], relatedCourseIds: ["community-shop-finance"], freePreviewEpisodeIds: ["ethics-01"], sectionTitles: ["ความไว้วางใจ", "การสื่อสาร"], dataMode: "presentation" },
  { courseId: "arabic-for-service", subtitle: "สื่อสารอย่างมั่นใจสำหรับงานบริการ", accessType: "one_on_one", accessState: "preview", price: null, compareAtPrice: null, language: "ไทย / อาหรับ", updatedLabel: "มี session 1-on-1 แบบ presentation", learnerCount: null, teacherId: "teacher-ameena", outcomes: ["ทักทายผู้รับบริการ", "ใช้คำศัพท์อาหาร"], requirements: [], audience: ["โรงแรม", "ร้านอาหาร", "ไกด์"], tags: ["language", "travel"], relatedCourseIds: ["halal-food-storytelling"], freePreviewEpisodeIds: ["arabic-01"], sectionTitles: ["การต้อนรับ", "คำศัพท์งานบริการ"], dataMode: "presentation" },
];

export const LEARNING_MEMBERSHIP_PLANS: LearningMembershipPlan[] = [
  { id: "monthly", title: "HOBEE Learning Monthly", billingLabel: "รายเดือน", price: null, includedCourseIds: ["community-shop-finance"], benefits: ["คอร์สสำหรับสมาชิก", "Live class แบบคัดสรร", "Member badge"], dataMode: "presentation" }, { id: "annual", title: "HOBEE Learning Annual", billingLabel: "รายปี", price: null, savingsLabel: "สิทธิประโยชน์และราคาจะแสดงเมื่อเปิด billing catalogue", includedCourseIds: ["community-shop-finance"], benefits: ["สิทธิสมาชิกแบบรายปี", "Live class แบบคัดสรร", "Member badge"], dataMode: "presentation" },
];

export const LEARNING_EVENTS: LearningEvent[] = [
  { id: "event-growth-01", kind: "seminar", title: "Growth for Local Business", subtitle: "Seminar สำหรับธุรกิจชุมชน", hero: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=85", teacherId: "teacher-hobee-academy", startsAt: "2026-09-15T09:00:00+07:00", endsAt: "2026-09-15T12:00:00+07:00", mode: "online", venue: "Online session", capacity: null, price: null, accessState: "free", agenda: ["Growth planning", "Community case study", "Q&A"], ticketTypes: ["General"], status: "upcoming", dataMode: "presentation" }, { id: "event-food-01", kind: "workshop", title: "เล่าเรื่องอาหารด้วยมือถือ", subtitle: "Workshop สำหรับร้านชุมชน", hero: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85", teacherId: "teacher-sofiya", startsAt: "2026-10-04T13:00:00+07:00", endsAt: "2026-10-04T16:00:00+07:00", mode: "offline", venue: "สถานที่จะแสดงเมื่อเปิด event inventory", capacity: null, price: null, accessState: "purchase_required", agenda: ["Mobile food photo", "Storytelling", "Caption clinic"], ticketTypes: ["Workshop ticket"], status: "upcoming", dataMode: "presentation" },
];

export const LEARNING_LIVE_CLASSES: LearningLiveClass[] = [
  { id: "live-growth-01", title: "ถามตอบ Meta Ads สำหรับร้านเล็ก", subtitle: "Live Q&A", teacherId: "teacher-hobee-academy", startsAt: "2026-09-20T19:00:00+07:00", durationMinutes: 60, learnerCount: null, state: "upcoming", replayAvailable: false, resources: ["Worksheet presentation"], dataMode: "presentation" }, { id: "live-food-01", title: "Food Content Clinic", subtitle: "วิเคราะห์คอนเทนต์ร้านอาหาร", teacherId: "teacher-sofiya", startsAt: "2026-08-20T19:00:00+07:00", durationMinutes: 45, learnerCount: null, state: "replay", replayAvailable: true, resources: ["Checklist presentation"], dataMode: "presentation" },
];

export const LEARNING_ONE_ON_ONE_SERVICES: LearningOneOnOneService[] = [
  { id: "session-food-story", teacherId: "teacher-sofiya", title: "Food Storytelling Review", durationMinutes: 45, price: null, topics: ["Content plan", "ภาพอาหาร", "Caption"], languages: ["ไทย"], availabilityLabel: "ตารางจริงจะเชื่อมกับ availability provider ภายหลัง", dataMode: "presentation" }, { id: "session-shop-finance", teacherId: "teacher-abdullah", title: "SME Finance Clinic", durationMinutes: 45, price: null, topics: ["ต้นทุน", "เงินหมุนเวียน", "บัญชีร้าน"], languages: ["ไทย"], availabilityLabel: "ตารางจริงจะเชื่อมกับ availability provider ภายหลัง", dataMode: "presentation" }, { id: "session-arabic-service", teacherId: "teacher-ameena", title: "Arabic Service Practice", durationMinutes: 30, price: null, topics: ["การต้อนรับ", "คำศัพท์บริการ"], languages: ["ไทย", "อาหรับ"], availabilityLabel: "ตารางจริงจะเชื่อมกับ availability provider ภายหลัง", dataMode: "presentation" },
];

export const LEARNING_QUIZZES: LearningQuiz[] = [{ id: "quiz-meta-01", courseId: "meta-ads-mastery", title: "ทบทวนพื้นฐาน Meta Ads", questionCount: 5, passingScore: 60, dataMode: "presentation" }];
export const LEARNING_ASSIGNMENTS: LearningAssignment[] = [{ id: "assignment-food-01", courseId: "halal-food-storytelling", title: "วางเรื่องเล่าจากเมนูหนึ่งจาน", description: "สร้างโครงเรื่องสำหรับเมนูของคุณ", deadlineLabel: "กำหนดส่งจะแสดงเมื่อเปิด classroom backend", status: "pending", dataMode: "presentation" }];
export const TEACHER_LEARNER_BRIDGES: TeacherLearnerBridge[] = LEARNING_TEACHERS.map((teacher) => ({ teacherId: teacher.id, courseIds: teacher.courseIds, learnerProgressSource: "local_progress", enrollmentSource: "presentation", publishingSource: "presentation" }));

export function getCourseMetadata(courseId: string) { return COURSE_METADATA.find((item) => item.courseId === courseId); }
export function getLearningTeacher(teacherId?: string) { return LEARNING_TEACHERS.find((item) => item.id === teacherId); }
export function coursesForTeacher(teacherId: string) { const teacher = getLearningTeacher(teacherId); return learningCourses.filter((course) => teacher?.courseIds.includes(course.id)); }
export function coursesForAccess(accessType: LearningAccessType) { return learningCourses.filter((course) => getCourseMetadata(course.id)?.accessType === accessType); }
export function searchLearning(query: string) { const value = query.trim().toLowerCase(); if (!value) return learningCourses; return learningCourses.filter((course) => { const metadata = getCourseMetadata(course.id); const teacher = getLearningTeacher(metadata?.teacherId); const corpus = [course.title, course.shortDescription, course.category, course.instructor, ...(metadata?.tags ?? []), ...(teacher?.expertise ?? [])].join(" ").toLowerCase(); return corpus.includes(value); }); }
export function learningCategoriesForCourse(course: LearningCourse) { return LEARNING_CATEGORIES.filter((category) => { const metadata = getCourseMetadata(course.id); return metadata?.tags.includes(category.id) || course.category.toLowerCase().includes(category.label.toLowerCase()); }); }
