export type LocalStoreProvinceId = "narathiwat" | "yala" | "pattani" | "songkhla" | "satun" | "chiang-mai";
export type LocalStoreCategoryId = "all" | "restaurant" | "cafe" | "souvenir" | "community" | "agriculture" | "batik" | "health" | "lifestyle" | "service" | "other";
export type LocalStoreAmenity = "parking" | "wifi" | "accessibility" | "halal_information" | "pickup" | "delivery";
export type LocalStoreBadge = "local" | "community" | "otop" | "hobee_verified" | "halal_information";
export type LocalFulfilment = "pickup" | "delivery";
export type StoreDataMode = "presentation" | "live";

export type StoreOpeningPeriod = { open: string; close: string };
export type StoreOpeningHours = { weekday: number; label: string; periods: StoreOpeningPeriod[]; closed?: boolean; specialNote?: string };
export type LocalStoreMenuItem = { id: string; name: string; description?: string; price?: number; image?: string; available: boolean; signature?: boolean };
export type LocalStoreReview = { id: string; author: string; rating: number; text: string; createdAt: string; photos?: string[]; tags?: string[]; dataMode: StoreDataMode };
export type LocalStore = {
  id: string; dataMode: StoreDataMode; name: string; provinceId: LocalStoreProvinceId; district: string; subdistrict?: string; category: Exclude<LocalStoreCategoryId, "all">; shortAddress: string; address?: string;
  coverImage: string; galleryImages: string[]; logoImage?: string; story?: string; coordinates?: { lat: number; lng: number }; rating?: number; reviewsCount?: number; priceRange?: string;
  openingHours: StoreOpeningHours[]; preorderSupported: boolean; fulfilment: LocalFulfilment[]; amenities: LocalStoreAmenity[]; badges: LocalStoreBadge[]; signatureItems: LocalStoreMenuItem[]; menu: LocalStoreMenuItem[]; reviews: LocalStoreReview[];
  contact?: { phone?: string; lineUrl?: string; website?: string };
};

export type LocalStoreFilters = { category: LocalStoreCategoryId; search: string; openNow: boolean; nearby: boolean; preorder: boolean; pickup: boolean; delivery: boolean; line: boolean; halal: boolean; parking: boolean; wifi: boolean; sort: "nearby" | "rating" | "popular" | "price" };
export type LocalStorePage = { items: LocalStore[]; nextCursor: string | null; total: number; mode: StoreDataMode };
export type LocalStoreOpeningState = { isOpen: boolean | null; label: string; detail: string };

export const LOCAL_STORE_PROVINCES: { id: LocalStoreProvinceId; label: string }[] = [
  { id: "narathiwat", label: "นราธิวาส" }, { id: "yala", label: "ยะลา" }, { id: "pattani", label: "ปัตตานี" }, { id: "songkhla", label: "สงขลา" }, { id: "satun", label: "สตูล" }, { id: "chiang-mai", label: "เชียงใหม่" },
];
export const LOCAL_STORE_CATEGORIES: { id: LocalStoreCategoryId; label: string; icon: string; tone: string }[] = [
  { id: "all", label: "ทั้งหมด", icon: "apps", tone: "#FFF5D9" }, { id: "restaurant", label: "ร้านอาหาร", icon: "restaurant", tone: "#FDE9D9" }, { id: "cafe", label: "คาเฟ่", icon: "local-cafe", tone: "#F5EADF" }, { id: "souvenir", label: "ของฝาก", icon: "redeem", tone: "#FFF2C6" }, { id: "community", label: "ร้านชุมชน", icon: "groups", tone: "#E8F4F3" }, { id: "agriculture", label: "เกษตร", icon: "yard", tone: "#E4F4E9" }, { id: "batik", label: "แฟชั่น / บาติก", icon: "checkroom", tone: "#F1E8FF" }, { id: "health", label: "สุขภาพ / ร้านยา", icon: "health-and-safety", tone: "#E8F3FB" }, { id: "lifestyle", label: "บ้านและไลฟ์สไตล์", icon: "chair", tone: "#FDEFE1" }, { id: "service", label: "บริการ", icon: "handyman", tone: "#E4F4E9" }, { id: "other", label: "อื่น ๆ", icon: "more-horiz", tone: "#F1F0ED" },
];

const week = (open: string, close: string): StoreOpeningHours[] => [0, 1, 2, 3, 4, 5, 6].map((weekday) => ({ weekday, label: ["อาทิตย์", "จันทร์", "อังคาร", "พุธ", "พฤหัสบดี", "ศุกร์", "เสาร์"][weekday], periods: [{ open, close }] }));
const menuImage = "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=85&w=700";

/** Presentation-only fixtures. Values must not be treated as verified store or transaction data. */
export const LOCAL_STORE_PRESENTATION_DATA: LocalStore[] = [
  { id: "local-narathiwat-khao-yam", dataMode: "presentation", name: "ครัวข้าวยำวิถีวัง", provinceId: "narathiwat", district: "อ.แว้ง", category: "restaurant", shortAddress: "อ.แว้ง · นราธิวาส", coverImage: menuImage, galleryImages: [menuImage, "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=85&w=700"], rating: 4.8, reviewsCount: 38, priceRange: "฿", openingHours: week("06:00", "21:00"), preorderSupported: true, fulfilment: ["pickup"], amenities: ["parking", "halal_information", "pickup"], badges: ["local", "halal_information"], story: "พื้นที่เล่าเรื่องรสชาติท้องถิ่นและชุมชนผ่านอาหารใต้", signatureItems: [{ id: "rice-yam", name: "ข้าวยำวิถีวัง", description: "เมนูแนะนำของร้าน", price: 55, image: menuImage, available: true, signature: true }], menu: [{ id: "rice-yam", name: "ข้าวยำวิถีวัง", description: "เมนูแนะนำของร้าน", price: 55, image: menuImage, available: true, signature: true }, { id: "pulled-tea", name: "ชาชักเย็น", description: "ชาใต้ชงสด", price: 35, available: true }, { id: "crispy-roti", name: "โรตีกรอบ", description: "ทำใหม่ตามออเดอร์", price: 30, available: true }], reviews: [{ id: "review-local-1", author: "ผู้ใช้ HOBEE", rating: 5, text: "ข้อมูลรีวิวสำหรับ presentation UI", createdAt: "2026-08-01", dataMode: "presentation" }] },
  { id: "local-yala-tea", dataMode: "presentation", name: "บ้านชาชักเบตง", provinceId: "yala", district: "อ.เบตง", category: "cafe", shortAddress: "อ.เบตง · ยะลา", coverImage: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=85&w=1000", galleryImages: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=85&w=1000"], rating: 4.7, reviewsCount: 41, priceRange: "฿", openingHours: week("09:00", "23:00"), preorderSupported: true, fulfilment: ["pickup", "delivery"], amenities: ["wifi", "pickup", "delivery"], badges: ["local"], story: "คาเฟ่ชาชักที่เตรียมพร้อมสำหรับ flow การสั่งล่วงหน้า", signatureItems: [{ id: "betong-tea", name: "ชาชักเบตง", price: 35, available: true, signature: true }], menu: [{ id: "betong-tea", name: "ชาชักเบตง", price: 35, available: true, signature: true }, { id: "butter-roti", name: "โรตีเนยนม", price: 40, available: true }], reviews: [] },
  { id: "local-pattani-weave", dataMode: "presentation", name: "เรือนผ้าทอปัตตานี", provinceId: "pattani", district: "อ.เมือง", category: "community", shortAddress: "อ.เมือง · ปัตตานี", coverImage: "https://images.unsplash.com/photo-1523779917675-b6ed3a42a561?auto=format&fit=crop&q=85&w=1000", galleryImages: ["https://images.unsplash.com/photo-1523779917675-b6ed3a42a561?auto=format&fit=crop&q=85&w=1000"], priceRange: "ดูสินค้าที่ร้าน", openingHours: week("10:00", "18:00"), preorderSupported: false, fulfilment: [], amenities: ["parking", "accessibility"], badges: ["community", "local"], story: "พื้นที่นำเสนอสินค้าและเรื่องราวจากชุมชน", signatureItems: [], menu: [], reviews: [] },
  { id: "local-songkhla-batik", dataMode: "presentation", name: "บาติกริมเลสงขลา", provinceId: "songkhla", district: "อ.สิงหนคร", category: "batik", shortAddress: "อ.สิงหนคร · สงขลา", coverImage: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=85&w=1000", galleryImages: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=85&w=1000"], priceRange: "ดูสินค้าที่ร้าน", openingHours: week("09:30", "17:30"), preorderSupported: false, fulfilment: [], amenities: ["parking"], badges: ["local"], story: "พื้นที่สำหรับสินค้าบาติกและดีไซน์ท้องถิ่น", signatureItems: [], menu: [], reviews: [] },
  { id: "local-satun-garden", dataMode: "presentation", name: "สวนชุมชนสตูล", provinceId: "satun", district: "อ.ละงู", category: "agriculture", shortAddress: "อ.ละงู · สตูล", coverImage: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&q=85&w=1000", galleryImages: ["https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&q=85&w=1000"], openingHours: week("08:00", "17:00"), preorderSupported: true, fulfilment: ["pickup"], amenities: ["parking", "pickup"], badges: ["community", "local"], story: "พื้นที่สำหรับสินค้าเกษตรและการรับสินค้าที่ร้าน", signatureItems: [{ id: "garden-box", name: "กล่องผักชุมชน", price: 120, available: true, signature: true }], menu: [{ id: "garden-box", name: "กล่องผักชุมชน", price: 120, available: true, signature: true }], reviews: [] },
  { id: "local-chiangmai-home", dataMode: "presentation", name: "บ้านชาและไลฟ์สไตล์เชียงใหม่", provinceId: "chiang-mai", district: "อ.เมือง", category: "lifestyle", shortAddress: "อ.เมือง · เชียงใหม่", coverImage: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&q=85&w=1000", galleryImages: ["https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&q=85&w=1000"], openingHours: week("10:00", "19:00"), preorderSupported: false, fulfilment: [], amenities: ["wifi", "accessibility"], badges: ["local"], story: "พื้นที่ lifestyle local discovery สำหรับขยายจังหวัดในอนาคต", signatureItems: [], menu: [], reviews: [] },
];

export const DEFAULT_LOCAL_STORE_FILTERS: LocalStoreFilters = { category: "all", search: "", openNow: false, nearby: false, preorder: false, pickup: false, delivery: false, line: false, halal: false, parking: false, wifi: false, sort: "nearby" };

export function getStoreById(id?: string) { return LOCAL_STORE_PRESENTATION_DATA.find((store) => store.id === id); }
export function storesForProvince(provinceId: LocalStoreProvinceId) { return LOCAL_STORE_PRESENTATION_DATA.filter((store) => store.provinceId === provinceId); }
export function getOpeningState(store: LocalStore, now = new Date()): LocalStoreOpeningState { const hours = store.openingHours.find((entry) => entry.weekday === now.getDay()); if (!hours || hours.closed || !hours.periods.length) return { isOpen: false, label: "ปิดอยู่", detail: "รอข้อมูลเวลาเปิดจริง" }; const current = `${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`; const period = hours.periods.find((item) => item.open <= current && current < item.close); return period ? { isOpen: true, label: "เปิดอยู่", detail: `ปิด ${period.close}` } : { isOpen: false, label: "ปิดอยู่", detail: `เปิด ${hours.periods[0].open}` }; }
export function queryLocalStores(provinceId: LocalStoreProvinceId, filters: LocalStoreFilters, cursor = 0, pageSize = 20): LocalStorePage { let items = storesForProvince(provinceId).filter((store) => (filters.category === "all" || store.category === filters.category) && (!filters.search || `${store.name} ${store.district} ${store.category}`.toLowerCase().includes(filters.search.toLowerCase())) && (!filters.openNow || getOpeningState(store).isOpen) && (!filters.preorder || store.preorderSupported) && (!filters.pickup || store.fulfilment.includes("pickup")) && (!filters.delivery || store.fulfilment.includes("delivery")) && (!filters.halal || store.amenities.includes("halal_information")) && (!filters.parking || store.amenities.includes("parking")) && (!filters.wifi || store.amenities.includes("wifi")) && (!filters.line || Boolean(store.contact?.lineUrl))); if (filters.sort === "rating") items = [...items].sort((a, b) => (b.rating ?? -1) - (a.rating ?? -1)); if (filters.sort === "price") items = [...items].sort((a, b) => (a.menu[0]?.price ?? Number.MAX_SAFE_INTEGER) - (b.menu[0]?.price ?? Number.MAX_SAFE_INTEGER)); const page = items.slice(cursor, cursor + pageSize); return { items: page, nextCursor: cursor + pageSize < items.length ? String(cursor + pageSize) : null, total: items.length, mode: "presentation" }; }
