export type FoodTimeSlot = "morning" | "lunch" | "afternoon" | "evening" | "late_night";
export type RestaurantMenuItem = { id: string; name: string; description: string; price: number; imageUrl: string; isPopular: boolean; isHalal: boolean; customizationOptions?: { optionName: string; choices: { label: string; extraPrice: number }[] }[] };
export type RestaurantMenuCategory = { id: string; categoryName: string; timeSlotTarget: FoodTimeSlot | "all_day"; items: RestaurantMenuItem[] };
export type ComboPackage = { id: string; title: string; originalPrice: number; comboPrice: number; mainItemOptions: RestaurantMenuItem[]; beverageOptions: RestaurantMenuItem[]; sideOptions: RestaurantMenuItem[] };
export type RestaurantListing = { id: string; name: string; provinceId: "narathiwat" | "yala" | "satun" | "pattani" | "songkhla"; district: string; address: string; coordinates: { lat: number; lng: number }; rating: number; reviewsCount: number; isOpenNow: boolean; openingHours: { open: string; close: string }; isHalalCertified: boolean; preorderSupported: boolean; averagePrepTimeMinutes: number; coverImage: string; galleryImages: string[]; timeSlotsAvailable: FoodTimeSlot[]; menuCategories: RestaurantMenuCategory[]; comboPackages?: ComboPackage[]; parkingFriendly: boolean; familySetAvailable: boolean };

export const foodTimeSlots: { id: FoodTimeSlot; label: string; subtitle: string; icon: string }[] = [
  { id: "morning", label: "เช้า", subtitle: "มื้อเช้าวิถีถิ่น", icon: "🌅" }, { id: "lunch", label: "เที่ยง", subtitle: "มื้อเที่ยงจัดเต็ม", icon: "☀️" }, { id: "afternoon", label: "บ่าย", subtitle: "จิบชา & ของหวาน", icon: "☕" }, { id: "evening", label: "เย็น", subtitle: "มื้อค่ำต้อนรับคืน", icon: "🌙" }, { id: "late_night", label: "ดึก", subtitle: "มื้อดึกสายชิลล์", icon: "⭐" },
];

const riceYam: RestaurantMenuItem = { id: "food-rice-yam", name: "ข้าวยำปักษ์ใต้ทรงเครื่อง", description: "ผักสด น้ำบูดู และปลาโอ", price: 55, imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=85&w=500", isPopular: true, isHalal: true };
const chickenRice: RestaurantMenuItem = { id: "food-chicken-rice", name: "ข้าวหมกไก่สูตรเข้มข้น", description: "ข้าวหอมเครื่องเทศ ไก่นุ่ม", price: 75, imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=85&w=500", isPopular: true, isHalal: true };
const pulledTea: RestaurantMenuItem = { id: "food-tea", name: "ชาชักเย็นฟองนุ่ม", description: "ชาสูตรใต้ ชักสดแก้วต่อแก้ว", price: 35, imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=85&w=500", isPopular: true, isHalal: true, customizationOptions: [{ optionName: "ระดับความหวาน", choices: [{ label: "ปกติ", extraPrice: 0 }, { label: "หวานน้อย 50%", extraPrice: 0 }, { label: "ไม่หวาน", extraPrice: 0 }] }, { optionName: "ฟองชา", choices: [{ label: "ฟองปกติ", extraPrice: 0 }, { label: "ฟองหนา", extraPrice: 5 }] }] };
const crispyRoti: RestaurantMenuItem = { id: "food-roti", name: "โรตีกรอบนม", description: "โรตีทำใหม่ หอมเนย", price: 30, imageUrl: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&q=85&w=500", isPopular: true, isHalal: true };
const beefSoup: RestaurantMenuItem = { id: "food-beef-soup", name: "ซุปหางวัว", description: "ซุปร้อนเครื่องเทศใต้", price: 95, imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=85&w=500", isPopular: false, isHalal: true };

export const restaurantListings: RestaurantListing[] = [
  { id: "restaurant-wang", name: "ครัวข้าวยำวิถีวัง", provinceId: "narathiwat", district: "อ.แว้ง", address: "ข้อมูลที่อยู่ Preview", coordinates: { lat: 6.248, lng: 101.925 }, rating: 4.8, reviewsCount: 38, isOpenNow: true, openingHours: { open: "06:00", close: "21:00" }, isHalalCertified: true, preorderSupported: true, averagePrepTimeMinutes: 15, coverImage: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=85&w=1000", galleryImages: ["https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=85&w=800", "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=85&w=800"], timeSlotsAvailable: ["morning", "lunch", "afternoon", "evening"], parkingFriendly: true, familySetAvailable: true, menuCategories: [{ id: "morning-local", categoryName: "มื้อเช้าวิถีถิ่น", timeSlotTarget: "morning", items: [riceYam, pulledTea, crispyRoti] }, { id: "lunch-local", categoryName: "มื้อเที่ยงจัดเต็ม", timeSlotTarget: "lunch", items: [chickenRice, beefSoup, riceYam] }, { id: "tea", categoryName: "เครื่องดื่มชาชัก", timeSlotTarget: "afternoon", items: [pulledTea, crispyRoti] }, { id: "all-day", categoryName: "เมนูทานได้ทั้งวัน", timeSlotTarget: "all_day", items: [riceYam, pulledTea] }], comboPackages: [{ id: "tea-roti", title: "เซ็ตคู่หูชาชัก + โรตีกรอบ", originalPrice: 65, comboPrice: 55, mainItemOptions: [riceYam, chickenRice], beverageOptions: [pulledTea], sideOptions: [crispyRoti] }] },
  { id: "restaurant-betong", name: "บ้านชาชักเบตง", provinceId: "yala", district: "อ.เบตง", address: "ข้อมูลที่อยู่ Preview", coordinates: { lat: 5.999, lng: 101.254 }, rating: 4.7, reviewsCount: 41, isOpenNow: true, openingHours: { open: "09:00", close: "23:00" }, isHalalCertified: true, preorderSupported: true, averagePrepTimeMinutes: 10, coverImage: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=85&w=1000", galleryImages: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=85&w=800"], timeSlotsAvailable: ["morning", "lunch", "afternoon", "evening", "late_night"], parkingFriendly: false, familySetAvailable: false, menuCategories: [{ id: "tea-all-day", categoryName: "ชาชัก & โรตี", timeSlotTarget: "all_day", items: [pulledTea, crispyRoti] }, { id: "night", categoryName: "มื้อดึกสายชิลล์", timeSlotTarget: "late_night", items: [pulledTea, crispyRoti, beefSoup] }], comboPackages: [{ id: "betong-solo", title: "เซ็ตชิลล์เบตง", originalPrice: 70, comboPrice: 60, mainItemOptions: [riceYam], beverageOptions: [pulledTea], sideOptions: [crispyRoti] }] },
];

export function getFoodTimeSlot(now = new Date()): FoodTimeSlot { const hour = now.getHours(); if (hour >= 6 && hour < 10) return "morning"; if (hour >= 10 && hour < 14) return "lunch"; if (hour >= 14 && hour < 17) return "afternoon"; if (hour >= 17 && hour < 21) return "evening"; return "late_night"; }
export function menuForTimeSlot(restaurant: RestaurantListing, slot: FoodTimeSlot) { return restaurant.menuCategories.filter((category) => category.timeSlotTarget === slot || category.timeSlotTarget === "all_day"); }
export function restaurantsForTimeSlot(slot: FoodTimeSlot, filterIds: string[]) { return restaurantListings.filter((restaurant) => restaurant.timeSlotsAvailable.includes(slot) && (!filterIds.includes("fast") || restaurant.averagePrepTimeMinutes <= 15) && (!filterIds.includes("halal") || restaurant.isHalalCertified) && (!filterIds.includes("parking") || restaurant.parkingFriendly) && (!filterIds.includes("preorder") || restaurant.preorderSupported) && (!filterIds.includes("family") || restaurant.familySetAvailable)); }
