import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams, type Href } from "expo-router";
import { useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AppStatusState } from "@/components/hobee/error-screens";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { getCommunityPerson, getCommunityProvinceLabel } from "@/lib/community-hub";

export default function CommunityPersonScreen() { const { id } = useLocalSearchParams<{ id?: string }>(); const person = getCommunityPerson(id); const [following, setFollowing] = useState(person?.followState === "following"); if (!person) return <ScreenContainer><AppStatusState title="ไม่พบโปรไฟล์นี้" description="กลับไปค้นหาผู้คนใน Community อีกครั้ง" actionLabel="กลับ Community" onAction={() => router.replace("/community" as Href)} /></ScreenContainer>; return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>โปรไฟล์ชุมชน</Text><Pressable style={styles.back}><MaterialIcons name="more-horiz" size={22} color={HOBEE.colors.ink} /></Pressable></View><View style={styles.hero}><Image source={{ uri: person.avatar }} style={styles.avatar} /><Text style={styles.name}>{person.name}</Text><Text style={styles.role}>{person.role} · {getCommunityProvinceLabel(person.province)}</Text><Text style={styles.bio}>{person.bio}</Text><Pressable onPress={() => setFollowing((current) => !current)} style={[styles.follow, following && styles.following]}><Text style={styles.followText}>{following ? "กำลังติดตาม" : "ติดตาม"}</Text><MaterialIcons name={following ? "check" : "person-add"} size={17} color={HOBEE.colors.ink} /></Pressable></View><View style={styles.section}><Text style={styles.sectionTitle}>ความสนใจ</Text><View style={styles.chips}>{person.interests.map((interest) => <View key={interest} style={styles.chip}><Text style={styles.chipText}>{interest}</Text></View>)}</View></View>{person.reference ? <Pressable onPress={() => router.push(person.reference!.route as Href)} style={styles.reference}><MaterialIcons name="north-east" size={19} color={HOBEE.colors.goldDark} /><View style={styles.referenceCopy}><Text style={styles.referenceTitle}>{person.reference.label}</Text><Text style={styles.referenceText}>เปิดในโมดูล HOBEE เดิม</Text></View><MaterialIcons name="chevron-right" size={20} color={HOBEE.colors.muted} /></Pressable> : null}<View style={styles.boundary}><MaterialIcons name="info-outline" size={17} color={HOBEE.colors.muted} /><Text style={styles.boundaryText}>Followers, privacy, report และ block จะเชื่อมใน Community Profile & Safety phase โดยใช้ policy กลาง</Text></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 42 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: HOBEE.space.page }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, headerTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, hero: { alignItems: "center", gap: 7, marginHorizontal: HOBEE.space.page, borderRadius: HOBEE.radius.hero, backgroundColor: HOBEE.atmosphere.warmCream, padding: 22 }, avatar: { width: 88, height: 88, borderRadius: 44, borderWidth: 3, borderColor: HOBEE.colors.surface }, name: { color: HOBEE.colors.ink, fontSize: 22, fontWeight: "900", marginTop: 4 }, role: { color: HOBEE.colors.botanical, fontSize: 12, fontWeight: "900" }, bio: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 18, marginTop: 4, textAlign: "center" }, follow: { flexDirection: "row", alignItems: "center", gap: 7, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.gold, marginTop: 5, paddingHorizontal: 16, paddingVertical: 10 }, following: { backgroundColor: HOBEE.atmosphere.botanicalMist }, followText: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "900" }, section: { gap: 9, marginHorizontal: HOBEE.space.page, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.colors.surface, padding: 14, ...HOBEE.elevation.surface }, sectionTitle: { color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.atmosphere.skyMist, paddingHorizontal: 10, paddingVertical: 7 }, chipText: { color: HOBEE.colors.botanical, fontSize: 11, fontWeight: "900" }, reference: { flexDirection: "row", alignItems: "center", gap: 9, marginHorizontal: HOBEE.space.page, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.atmosphere.skyMist, padding: 13 }, referenceCopy: { flex: 1 }, referenceTitle: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, referenceText: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", marginTop: 3 }, boundary: { flexDirection: "row", gap: 7, marginHorizontal: HOBEE.space.page }, boundaryText: { flex: 1, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", lineHeight: 15 } });
