import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AccountQuickAction, InfoRow, ProfileHeader } from "@/components/hobee/commerce-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useLocale } from "@/contexts/locale-context";
import { useSupabaseAuth } from "@/contexts/supabase-auth-context";
import { useToast } from "@/contexts/toast-context";
import { useAdmin } from "@/hooks/use-admin";

export default function AccountScreen() {
  const { locale, setLocale, t } = useLocale(); const { user, loading, signOut } = useSupabaseAuth(); const { showToast } = useToast(); const { allowed: adminAllowed } = useAdmin();
  const signOutUser = async () => { try { await signOut(); showToast("ออกจากระบบแล้ว", "info"); } catch { showToast("ไม่สามารถออกจากระบบได้ กรุณาลองอีกครั้ง", "error"); } };
  const protectedRoute = (route: string) => { if (!user) { router.push("/auth"); return; } router.push(route as never); };
  return <ScreenContainer containerClassName="bg-[#F8F7F5]" className="px-5" safeAreaClassName="pt-3"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><ProfileHeader name={user ? "บัญชี HOBEE ของคุณ" : "ยินดีต้อนรับสู่ HOBEE"} detail={user?.email ?? "เข้าสู่ระบบเพื่อดูคำสั่งซื้อ คะแนน และสิทธิพิเศษ"} actionLabel={user ? "ออกจากระบบ" : "เข้าสู่ระบบ"} onAction={() => user ? void signOutUser() : router.push("/auth")} /><Section title="My HOBEE"><View style={styles.quickGrid}><AccountQuickAction icon="receipt-long" title="คำสั่งซื้อ" description="ติดตามสถานะ" onPress={() => protectedRoute("/orders")} /><AccountQuickAction icon="favorite-border" title="สินค้าโปรด" description="รายการที่บันทึกไว้" onPress={() => protectedRoute("/favorites")} /><AccountQuickAction icon="card-giftcard" title="Rewards" description="คะแนนและคูปอง" onPress={() => protectedRoute("/rewards")} /><AccountQuickAction icon="location-on" title="ที่อยู่" description="จัดการที่อยู่ส่ง" onPress={() => protectedRoute("/checkout/address")} /></View></Section><Section title="บัญชีและการช่วยเหลือ"><View style={styles.panel}><InfoRow icon="notifications-none" label="การแจ้งเตือน" value="ติดตามสถานะคำสั่งซื้อ" /><InfoRow icon="language" label={t("language.title")} value={locale === "th" ? "ไทย" : "English"} onPress={() => setLocale(locale === "th" ? "en" : "th")} /><InfoRow icon="help-outline" label="ช่วยเหลือ" value="ติดต่อเราและคำถามที่พบบ่อย" onPress={() => router.push("/auth")} /></View></Section>{adminAllowed ? <Section title="Business / Platform"><View style={styles.panel}><InfoRow icon="admin-panel-settings" label="HOBEE Admin Center" value="จัดการสินค้า สต็อก และคำสั่งซื้อ" onPress={() => router.push("/admin")} /></View></Section> : null}{user ? <Pressable disabled={loading} onPress={() => void signOutUser()} style={({ pressed }) => [styles.signOut, pressed && styles.pressed]}><Text style={styles.signOutText}>ออกจากระบบ</Text></Pressable> : null}<Text style={styles.version}>HOBEE Mobile · Community commerce</Text></ScrollView></ScreenContainer>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
const styles = StyleSheet.create({ content: { paddingBottom: 132 }, section: { marginTop: 25 }, sectionTitle: { marginBottom: 11, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, quickGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", rowGap: 12 }, panel: { borderRadius: 22, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 14 }, signOut: { alignSelf: "center", marginTop: 24, paddingHorizontal: 16, paddingVertical: 9 }, signOutText: { color: "#B65045", fontSize: 13, fontWeight: "900" }, version: { marginTop: 12, color: HOBEE.colors.muted, fontSize: 11, textAlign: "center" }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] } });
