import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AppHeader, EmptyState, ProductCard, ProductSkeleton, SearchBar, SectionHeader } from "@/components/hobee/shared-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useSupabaseAuth } from "@/contexts/supabase-auth-context";
import { useCatalog } from "@/hooks/use-catalog";
import { listFavoriteIds, setFavorite } from "@/lib/loyalty";

const CATEGORIES = ["ทั้งหมด", "น้ำผึ้ง", "อาหารและเครื่องดื่ม", "ของดีชุมชน"];

export default function ShopScreen() {
  const [query, setQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState("ทั้งหมด");
  const [favorites, setFavorites] = useState<Set<string>>(new Set());
  const { products, source, loading, refresh } = useCatalog();
  const { user } = useSupabaseAuth();

  useEffect(() => { if (!user) { setFavorites(new Set()); return; } void listFavoriteIds(user.id).then(setFavorites).catch(() => setFavorites(new Set())); }, [user]);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return products.filter((p) => { const queryMatch = !q || [p.name, p.shortName, p.category, p.origin].join(" ").toLowerCase().includes(q); const categoryMatch = activeCategory === "ทั้งหมด" || (activeCategory === "น้ำผึ้ง" && p.name.includes("น้ำผึ้ง")) || (activeCategory === "ของดีชุมชน" && p.badge === "LOCAL") || p.category === activeCategory; return queryMatch && categoryMatch; }); }, [activeCategory, products, query]);
  const toggleFavorite = useCallback(async (id: string) => { if (!user) { router.push("/auth"); return; } const next = !favorites.has(id); setFavorites((current) => { const draft = new Set(current); if (next) draft.add(id); else draft.delete(id); return draft; }); try { await setFavorite(user.id, id, next); } catch { setFavorites((current) => { const draft = new Set(current); if (next) draft.delete(id); else draft.add(id); return draft; }); } }, [favorites, user]);

  return <ScreenContainer containerClassName="bg-[#F8F7F5]" safeAreaClassName="pt-10" edges={["top", "left", "right"]}><FlatList data={filtered} key={activeCategory} numColumns={2} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} refreshing={loading} onRefresh={() => void refresh()} contentContainerStyle={styles.content} columnWrapperStyle={filtered.length ? styles.columns : undefined} ListHeaderComponent={<><AppHeader /><SearchBar editable value={query} onChangeText={setQuery} onClear={() => setQuery("")} placeholder="ค้นหาสินค้า ร้านค้า หรือของดีชุมชน" /><SectionHeader title="ร้านค้า" /><FlatList horizontal data={CATEGORIES} keyExtractor={(item) => item} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips} renderItem={({ item }) => { const active = item === activeCategory; return <Pressable onPress={() => setActiveCategory(item)} style={({ pressed }) => [styles.chip, active && styles.chipActive, pressed && styles.pressed]}><Text style={styles.chipText}>{item}</Text></Pressable>; }} />{source === "local" ? <View style={styles.status}><MaterialIcons name="cloud-off" size={18} color="#A26B16" /><Text style={styles.statusText}>กำลังแสดงแค็ตตาล็อกเริ่มต้น ปัดลงเพื่อรีเฟรชเมื่อเชื่อมต่อข้อมูลได้</Text></View> : null}<View style={styles.heading}><Text style={styles.headingText}>{query || activeCategory !== "ทั้งหมด" ? "ผลการค้นหา" : "สินค้าแนะนำ"}</Text>{loading ? <ActivityIndicator color={HOBEE.colors.gold} size="small" /> : <Text style={styles.count}>{filtered.length} รายการ</Text>}</View></>} renderItem={({ item }) => <ProductCard product={item} favorite={favorites.has(item.id)} onFavorite={() => void toggleFavorite(item.id)} />} ListEmptyComponent={loading ? <ProductSkeleton /> : <EmptyState title="ไม่พบสินค้าที่ค้นหา" description="ลองเปลี่ยนคำค้นหา หรือเลือกหมวดหมู่อื่นเพื่อพบของดีเพิ่มเติม" onAction={() => { setQuery(""); setActiveCategory("ทั้งหมด"); }} />} ListFooterComponent={!user ? <Pressable onPress={() => router.push("/auth")} style={({ pressed }) => [styles.member, pressed && styles.pressed]}><View style={styles.memberIcon}><MaterialIcons name="person-outline" size={20} color={HOBEE.colors.ink} /></View><View style={styles.memberCopy}><Text style={styles.memberTitle}>มีบัญชี HOBEE อยู่แล้ว?</Text><Text style={styles.memberText}>เข้าสู่ระบบเพื่อบันทึกรายการโปรดและสะสมคะแนน</Text></View><MaterialIcons name="arrow-forward" size={22} color={HOBEE.colors.goldDark} /></Pressable> : <View style={styles.footer} />} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { paddingHorizontal: 20, paddingBottom: 162, backgroundColor: HOBEE.colors.canvas }, chips: { gap: 9, paddingBottom: 18, paddingRight: 20 }, chip: { borderWidth: 1, borderColor: HOBEE.colors.border, borderRadius: 999, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 15, paddingVertical: 10 }, chipActive: { borderColor: HOBEE.colors.gold, backgroundColor: HOBEE.colors.gold }, chipText: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "800" }, status: { flexDirection: "row", alignItems: "center", gap: 9, marginBottom: 22, borderRadius: 17, backgroundColor: "#FFF3D7", paddingHorizontal: 13, paddingVertical: 11 }, statusText: { flex: 1, color: "#746A5D", fontSize: 12, fontWeight: "600", lineHeight: 17 }, heading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 15 }, headingText: { color: HOBEE.colors.ink, fontSize: 21, fontWeight: "900" }, count: { color: HOBEE.colors.muted, fontSize: 13, fontWeight: "700" }, columns: { justifyContent: "space-between", marginBottom: 16 }, member: { flexDirection: "row", alignItems: "center", gap: 11, marginTop: 25, borderRadius: 22, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 14 }, memberIcon: { width: 45, height: 45, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: "#FFF1C8" }, memberCopy: { flex: 1 }, memberTitle: { color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900" }, memberText: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 17 }, footer: { height: 10 }, pressed: { opacity: 0.8, transform: [{ scale: 0.98 }] },
});
