import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useMemo } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { formatTravelMoney } from "@/lib/travel-booking";
import { getTravelListing } from "@/lib/travel-data";
import { useTravelCatalog } from "@/lib/travel-catalog";
import { ScreenContainer } from "@/components/screen-container";

export default function TravelVoucherScreen() {
  const { id, listingId, deposit, total } = useLocalSearchParams<{ id: string; listingId: string; deposit: string; total: string }>();
  const { listings } = useTravelCatalog();
  const listing = useMemo(() => listings.find((entry) => entry.id === listingId) ?? getTravelListing(listingId), [listingId, listings]);
  if (!listing) return <ScreenContainer className="items-center justify-center"><Text>ไม่พบ Voucher นี้</Text></ScreenContainer>;
  return <ScreenContainer containerClassName="bg-[#F8F7F5]" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><MaterialIcons name="confirmation-number" size={46} color={HOBEE.colors.gold} /><Text style={styles.heroOverline}>DIGITAL VOUCHER PREVIEW</Text><Text style={styles.heroTitle}>คำขอจองพร้อมตรวจสอบ</Text><Text style={styles.heroText}>Voucher จริงจะออกหลัง availability และ payment ถูกยืนยันโดย server</Text></View><View style={styles.ticket}><View style={styles.ticketTop}><Text style={styles.brand}>HOBEE TRAVEL</Text><View style={styles.status}><Text style={styles.statusText}>PENDING CONFIRMATION</Text></View></View><Text style={styles.ref}>{id}</Text><Text style={styles.listing}>{listing.title}</Text><Text style={styles.location}>{listing.location}</Text><View style={styles.divider} /><Row label={listing.listingType === "trip" ? "วันออกเดินทาง" : "เช็คอิน / เช็คเอาต์"} value={listing.listingType === "trip" ? listing.departureDates?.[0] ?? "รอยืนยัน" : "รอยืนยันจากผู้ประกอบการ"} /><Row label="ผู้ดำเนินการ" value={listing.operatorName} /><Row label="ยอดรวมคำขอจอง" value={formatTravelMoney(Number(total) || listing.priceFrom)} /><Row label="ยอดชำระในขั้นนี้" value={formatTravelMoney(Number(deposit) || 0)} strong /><View style={styles.qr}><MaterialIcons name="qr-code-2" size={118} color={HOBEE.colors.ink} /><Text style={styles.qrText}>QR Check-in จะแสดงหลังยืนยันการจอง</Text></View></View><View style={styles.notice}><MaterialIcons name="info" size={21} color={HOBEE.colors.travelTeal} /><Text style={styles.noticeText}>หน้านี้เป็น presentation preview ไม่ใช่หลักฐานการจองหรือการชำระเงิน จนกว่าระบบ booking ฝั่ง server จะพร้อมใช้งาน</Text></View><Pressable onPress={() => router.replace("/travel" as any)} style={styles.action}><Text style={styles.actionText}>กลับสู่หน้าท่องเที่ยว</Text><MaterialIcons name="arrow-forward" size={21} color={HOBEE.colors.ink} /></Pressable></ScrollView></ScreenContainer>;
}

function Row({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={[styles.rowValue, strong && styles.rowStrong]}>{value}</Text></View>; }

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 60 }, hero: { alignItems: "center", paddingTop: 24, paddingHorizontal: 20, paddingBottom: 24 }, heroOverline: { marginTop: 11, color: HOBEE.colors.travelTeal, fontSize: 11, fontWeight: "900", letterSpacing: 1 }, heroTitle: { marginTop: 8, color: HOBEE.colors.ink, fontSize: 25, fontWeight: "900", textAlign: "center" }, heroText: { marginTop: 7, color: HOBEE.colors.muted, fontSize: 13, fontWeight: "600", lineHeight: 19, textAlign: "center" }, ticket: { overflow: "hidden", borderRadius: 26, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: "#FFFFFF", padding: 20, ...HOBEE.shadow }, ticketTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, brand: { color: HOBEE.colors.travelTeal, fontSize: 14, fontWeight: "900", letterSpacing: 1 }, status: { borderRadius: 12, backgroundColor: "#FFF0D2", paddingHorizontal: 8, paddingVertical: 5 }, statusText: { color: "#9B6714", fontSize: 9, fontWeight: "900" }, ref: { marginTop: 25, color: HOBEE.colors.ink, fontSize: 22, fontWeight: "900" }, listing: { marginTop: 9, color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900", lineHeight: 24 }, location: { marginTop: 5, color: HOBEE.colors.muted, fontSize: 13, fontWeight: "600" }, divider: { height: 1, marginVertical: 17, backgroundColor: HOBEE.colors.border }, row: { flexDirection: "row", justifyContent: "space-between", gap: 20, marginTop: 10 }, rowLabel: { flex: 1, color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600" }, rowValue: { flex: 1.2, color: HOBEE.colors.ink, fontSize: 12, fontWeight: "800", textAlign: "right" }, rowStrong: { color: HOBEE.colors.travelTeal, fontSize: 14, fontWeight: "900" }, qr: { alignItems: "center", marginTop: 25, borderTopWidth: 1, borderTopColor: HOBEE.colors.border, paddingTop: 18 }, qrText: { marginTop: 8, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600", textAlign: "center" }, notice: { flexDirection: "row", gap: 10, marginTop: 16, borderRadius: 18, backgroundColor: "#E8F7F1", padding: 14 }, noticeText: { flex: 1, color: "#326457", fontSize: 12, fontWeight: "700", lineHeight: 18 }, action: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 22, borderRadius: 20, backgroundColor: HOBEE.colors.gold, paddingVertical: 14 }, actionText: { color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900" },
});
