import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams, type Href } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AppStatusState } from "@/components/hobee/error-screens";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { getCommunityJob } from "@/lib/community-hub";

export default function CommunityJobDetailScreen() { const { id } = useLocalSearchParams<{ id?: string }>(); const job = getCommunityJob(id); if (!job) return <ScreenContainer><AppStatusState title="ไม่พบโอกาสนี้" description="กลับไปเลือกงานจาก Community อีกครั้ง" actionLabel="ดูโอกาส" onAction={() => router.replace("/community/jobs" as Href)} /></ScreenContainer>; return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>รายละเอียดโอกาส</Text><Pressable style={styles.back}><MaterialIcons name="share" size={20} color={HOBEE.colors.ink} /></Pressable></View><View style={styles.hero}><View style={styles.icon}><MaterialIcons name="work-outline" size={28} color={HOBEE.colors.goldDark} /></View><Text style={styles.title}>{job.title}</Text><Text style={styles.org}>{job.organization}</Text><Text style={styles.meta}>{job.location} · {job.jobType.replace("_", " ")}</Text></View><Section title="เกี่ยวกับบทบาท" lines={[job.description, ...job.responsibilities]} /><Section title="คุณสมบัติ" lines={job.requirements} /><Section title="สิทธิประโยชน์" lines={job.benefits} /><View style={styles.boundary}><MaterialIcons name="info-outline" size={17} color={HOBEE.colors.muted} /><Text style={styles.boundaryText}>{job.compensationLabel} · การสมัครและติดต่อจะเปิดใช้เมื่อ job backend และ policy การรับสมัครพร้อม</Text></View><Pressable style={styles.primary}><Text style={styles.primaryText}>{job.appliedState === "not_applied" ? "ดูตัวอย่างการสมัคร" : "สถานะการสมัคร"}</Text><MaterialIcons name="arrow-forward" size={18} color={HOBEE.colors.ink} /></Pressable></ScrollView></ScreenContainer>; }
function Section({ title, lines }: { title: string; lines: string[] }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{lines.map((line) => <View key={line} style={styles.line}><MaterialIcons name="check-circle" size={16} color={HOBEE.colors.botanical} /><Text style={styles.lineText}>{line}</Text></View>)}</View>; }
const styles = StyleSheet.create({ content: { gap: 14, paddingBottom: 42 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: HOBEE.space.page }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, headerTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, hero: { alignItems: "center", gap: 6, marginHorizontal: HOBEE.space.page, borderRadius: HOBEE.radius.hero, backgroundColor: HOBEE.atmosphere.warmCream, padding: 22 }, icon: { width: 58, height: 58, alignItems: "center", justifyContent: "center", borderRadius: 20, backgroundColor: HOBEE.colors.surface }, title: { color: HOBEE.colors.ink, fontSize: 23, fontWeight: "900", textAlign: "center", marginTop: 4 }, org: { color: HOBEE.colors.botanical, fontSize: 13, fontWeight: "900" }, meta: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700" }, section: { gap: 9, marginHorizontal: HOBEE.space.page, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.colors.surface, padding: 14, ...HOBEE.elevation.surface }, sectionTitle: { color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900" }, line: { flexDirection: "row", alignItems: "flex-start", gap: 7 }, lineText: { flex: 1, color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 18 }, boundary: { flexDirection: "row", gap: 7, marginHorizontal: HOBEE.space.page }, boundaryText: { flex: 1, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", lineHeight: 15 }, primary: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8, marginHorizontal: HOBEE.space.page, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.gold, paddingVertical: 13 }, primaryText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" } });
