import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, type Href } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { COMMUNITY_JOBS } from "@/lib/community-hub";

export default function CommunityJobsScreen() { return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><View style={styles.copy}><Text style={styles.eyebrow}>HOBEE OPPORTUNITY</Text><Text style={styles.title}>งานและโอกาส</Text></View><Pressable onPress={() => router.push("/community/search" as Href)} style={styles.back}><MaterialIcons name="search" size={21} color={HOBEE.colors.ink} /></Pressable></View><FlatList data={COMMUNITY_JOBS} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} renderItem={({ item }) => <Pressable onPress={() => router.push(`/community/jobs/${item.id}` as Href)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.cardIcon}><MaterialIcons name="work-outline" size={22} color={HOBEE.colors.goldDark} /></View><View style={styles.cardCopy}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardMeta}>{item.organization} · {item.location}</Text><View style={styles.tags}>{item.tags.map((tag) => <View key={tag} style={styles.tag}><Text style={styles.tagText}>{tag}</Text></View>)}</View><Text style={styles.cardBoundary}>{item.compensationLabel}</Text></View><MaterialIcons name="chevron-right" size={21} color={HOBEE.colors.muted} /></Pressable>} ListHeaderComponent={<View style={styles.hero}><MaterialIcons name="diversity-3" size={30} color={HOBEE.colors.botanical} /><Text style={styles.heroTitle}>โอกาสที่เริ่มจากชุมชน</Text><Text style={styles.heroText}>ประกาศงานและโอกาสจะแสดงจากผู้ประกาศที่ผ่าน policy เมื่อ Opportunity backend พร้อม</Text></View>} /></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 11, padding: HOBEE.space.page }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, copy: { flex: 1 }, eyebrow: { color: HOBEE.colors.goldDark, fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, title: { color: HOBEE.colors.ink, fontSize: 20, fontWeight: "900", marginTop: 2 }, content: { paddingHorizontal: HOBEE.space.page, paddingBottom: 42 }, hero: { alignItems: "center", borderRadius: HOBEE.radius.hero, backgroundColor: HOBEE.atmosphere.botanicalMist, marginBottom: 14, padding: 20 }, heroTitle: { color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900", marginTop: 9 }, heroText: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 18, marginTop: 6, textAlign: "center" }, card: { flexDirection: "row", alignItems: "flex-start", gap: 10, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.colors.surface, marginBottom: 11, padding: 13, ...HOBEE.elevation.surface }, cardIcon: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: HOBEE.atmosphere.warmCream }, cardCopy: { flex: 1, gap: 4 }, cardTitle: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" }, cardMeta: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700" }, tags: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginTop: 3 }, tag: { borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.atmosphere.skyMist, paddingHorizontal: 7, paddingVertical: 4 }, tagText: { color: HOBEE.colors.botanical, fontSize: 9, fontWeight: "900" }, cardBoundary: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", marginTop: 3 }, pressed: { opacity: 0.8, transform: [{ scale: HOBEE.motion.cardPressScale }] } });
