import { MaterialIcons } from "@expo/vector-icons";
import type { ReactNode } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";

export type AdminWorkspace = "overview" | "products" | "orders" | "inventory";

const navItems: { key: AdminWorkspace; label: string; icon: keyof typeof MaterialIcons.glyphMap }[] = [
  { key: "overview", label: "ภาพรวม", icon: "grid-view" },
  { key: "products", label: "สินค้า", icon: "inventory-2" },
  { key: "orders", label: "คำสั่งซื้อ", icon: "receipt-long" },
  { key: "inventory", label: "คลังสินค้า", icon: "warehouse" },
];

export function AdminPortalShell({ active, title, subtitle, onNavigate, children }: { active: AdminWorkspace; title: string; subtitle: string; onNavigate: (workspace: AdminWorkspace) => void; children: ReactNode }) {
  return <View style={styles.page}><View style={styles.shell}><View style={styles.side}><View style={styles.brand}><View style={styles.mark}><MaterialIcons name="auto-awesome" size={19} color={HOBEE.colors.ink} /></View><View><Text style={styles.brandName}>HOBEE</Text><Text style={styles.brandSub}>ADMIN PORTAL</Text></View></View><View style={styles.nav}>{navItems.map((item) => <Pressable key={item.key} accessibilityRole="button" onPress={() => onNavigate(item.key)} style={({ pressed }) => [styles.navItem, active === item.key && styles.navItemActive, pressed && styles.pressed]}><MaterialIcons name={item.icon} size={20} color={active === item.key ? HOBEE.colors.ink : "#A8AAA8"} /><Text style={[styles.navText, active === item.key && styles.navTextActive]}>{item.label}</Text></Pressable>)}</View><View style={styles.sideFooter}><View style={styles.adminAvatar}><Text style={styles.adminAvatarText}>A</Text></View><View><Text style={styles.adminLabel}>HOBEE Admin</Text><Text style={styles.adminState}>สิทธิ์ผู้ดูแลระบบ</Text></View></View></View><View style={styles.main}><View style={styles.top}><View><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>{subtitle}</Text></View><View style={styles.topMeta}><View style={styles.liveDot} /><Text style={styles.liveText}>Supabase Live</Text></View></View>{children}</View></View></View>;
}

export function AdminMetric({ label, value, icon, tone = "gold" }: { label: string; value: string | number; icon: keyof typeof MaterialIcons.glyphMap; tone?: "gold" | "teal" | "rose" }) {
  const color = tone === "teal" ? HOBEE.colors.travelTeal : tone === "rose" ? HOBEE.colors.error : HOBEE.colors.goldDark;
  return <View style={styles.metric}><View style={[styles.metricIcon, { backgroundColor: `${color}1A` }]}><MaterialIcons name={icon} size={20} color={color} /></View><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>;
}

export function AdminCard({ children, style }: { children: ReactNode; style?: object }) { return <View style={[styles.card, style]}>{children}</View>; }
export function AdminCardTitle({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { return <View style={styles.cardTitleRow}><Text style={styles.cardTitle}>{title}</Text>{action ? <Pressable onPress={onAction}><Text style={styles.cardAction}>{action}</Text></Pressable> : null}</View>; }

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: "#F3F4F2" }, shell: { flex: 1, flexDirection: "row", alignSelf: "center", width: "100%", maxWidth: 1440, minHeight: "100%" }, side: { width: 238, borderRightWidth: 1, borderRightColor: "#292C2A", backgroundColor: HOBEE.colors.darkCard, paddingHorizontal: 16, paddingTop: 26, paddingBottom: 20 }, brand: { flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 8 }, mark: { width: 34, height: 34, alignItems: "center", justifyContent: "center", borderRadius: 11, backgroundColor: HOBEE.colors.gold }, brandName: { color: "#FFFFFF", fontSize: 17, fontWeight: "900", letterSpacing: 0.6 }, brandSub: { marginTop: 1, color: "#B2B5B1", fontSize: 9, fontWeight: "900", letterSpacing: 1.2 }, nav: { gap: 5, marginTop: 42 }, navItem: { flexDirection: "row", alignItems: "center", gap: 12, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 12 }, navItemActive: { backgroundColor: HOBEE.colors.gold }, navText: { color: "#A8AAA8", fontSize: 14, fontWeight: "800" }, navTextActive: { color: HOBEE.colors.ink }, sideFooter: { flexDirection: "row", alignItems: "center", gap: 9, marginTop: "auto", borderTopWidth: 1, borderTopColor: "#292C2A", padding: 10 }, adminAvatar: { width: 32, height: 32, alignItems: "center", justifyContent: "center", borderRadius: 16, backgroundColor: "#2B5F51" }, adminAvatarText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, adminLabel: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, adminState: { marginTop: 2, color: "#A8AAA8", fontSize: 10, fontWeight: "600" }, main: { flex: 1, paddingHorizontal: 34, paddingVertical: 29 }, top: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 26 }, title: { color: HOBEE.colors.ink, fontSize: 28, fontWeight: "900", letterSpacing: -0.5 }, subtitle: { marginTop: 5, color: HOBEE.colors.muted, fontSize: 13, fontWeight: "600" }, topMeta: { flexDirection: "row", alignItems: "center", gap: 6, borderRadius: 16, backgroundColor: "#FFFFFF", paddingHorizontal: 10, paddingVertical: 8 }, liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: HOBEE.colors.travelTeal }, liveText: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "800" }, metric: { flex: 1, minWidth: 135, borderRadius: 18, backgroundColor: "#FFFFFF", padding: 16 }, metricIcon: { width: 37, height: 37, alignItems: "center", justifyContent: "center", borderRadius: 12 }, metricValue: { marginTop: 15, color: HOBEE.colors.ink, fontSize: 25, fontWeight: "900" }, metricLabel: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 12, fontWeight: "700" }, card: { borderRadius: 20, backgroundColor: "#FFFFFF", padding: 19 }, cardTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 15 }, cardTitle: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, cardAction: { color: HOBEE.colors.goldDark, fontSize: 12, fontWeight: "900" }, pressed: { opacity: 0.76 },
});
