import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { goBackOr } from "@/lib/back-navigation";
import { restaurantListings } from "@/lib/restaurant-data";

export default function FoodQueueScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const restaurant = restaurantListings.find((entry) => entry.id === id); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.header}><Pressable onPress={() => goBackOr(router, `/travel/restaurant/${id}`)} style={styles.headerAction}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>Restaurant Queue</Text><View style={styles.headerAction}><MaterialIcons name="format-list-numbered" size={20} color={HOBEE.colors.travelTeal} /></View></View><View style={styles.content}><View style={styles.icon}><MaterialIcons name="hourglass-empty" size={40} color={HOBEE.colors.goldDark} /></View><Text style={styles.title}>{restaurant?.name ?? "ร้านอาหาร"}</Text><Text style={styles.description}>เข้าคิวและรับการแจ้งเตือนเมื่อถึงคิว</Text><View style={styles.card}><Text style={styles.label}>QUEUE STATUS</Text><Text style={styles.value}>รอสถานะจากร้าน</Text><Text style={styles.note}>ไม่แสดงเลขคิวหรือเวลารอจำลอง ระบบจะแสดงข้อมูลเมื่อ queue integration พร้อม</Text></View><Pressable onPress={() => router.push({ pathname: "/travel/food/reservation/[id]" as never, params: { id } })} style={({ pressed }) => [styles.primary, pressed && styles.pressed]}><Text style={styles.primaryText}>จองโต๊ะแทน</Text></Pressable></View></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 18, paddingVertical: 10 }, headerAction: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: "#F2F0EB" }, headerTitle: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, content: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10, padding: 26 }, icon: { width: 78, height: 78, alignItems: "center", justifyContent: "center", borderRadius: 39, backgroundColor: HOBEE.atmosphere.warmCream }, title: { color: HOBEE.colors.ink, fontSize: 20, fontWeight: "900", textAlign: "center" }, description: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", textAlign: "center" }, card: { width: "100%", gap: 6, marginTop: 10, borderRadius: 19, backgroundColor: HOBEE.atmosphere.skyMist, padding: 16 }, label: { color: HOBEE.colors.travelTeal, fontSize: 9, fontWeight: "900", letterSpacing: 1 }, value: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, note: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "600", lineHeight: 15 }, primary: { width: "100%", marginTop: 8, alignItems: "center", borderRadius: 15, backgroundColor: HOBEE.colors.gold, paddingVertical: 13 }, primaryText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
