import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { COMMUNITY_PROVINCES } from "@/lib/community-hub";

export default function CommunityCreateClubScreen() { const [name, setName] = useState(""); const [privateClub, setPrivateClub] = useState(false); const [province, setProvince] = useState("narathiwat"); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="close" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.title}>สร้างชมรม</Text><View style={styles.back} /></View><ScrollView contentContainerStyle={styles.content}><View style={styles.cover}><MaterialIcons name="add-photo-alternate" size={30} color={HOBEE.colors.goldDark} /><Text style={styles.coverTitle}>ภาพปกชมรม</Text><Text style={styles.coverText}>เลือกสื่อได้เมื่อ Media integration พร้อม</Text></View><TextInput value={name} onChangeText={setName} placeholder="ชื่อชมรม" placeholderTextColor={HOBEE.colors.muted} style={styles.input} /><TextInput placeholder="อธิบายเป้าหมายและสิ่งที่สมาชิกจะได้พบ" placeholderTextColor={HOBEE.colors.muted} multiline textAlignVertical="top" style={[styles.input, styles.description]} /><Text style={styles.label}>จังหวัดหรือพื้นที่หลัก</Text><View style={styles.chips}>{COMMUNITY_PROVINCES.slice(0, 5).map((item) => <Pressable key={item.id} onPress={() => setProvince(item.id)} style={[styles.chip, province === item.id && styles.chipActive]}><Text style={styles.chipText}>{item.label}</Text></Pressable>)}</View><Pressable onPress={() => setPrivateClub((current) => !current)} style={styles.privateRow}><View style={styles.privateCopy}><Text style={styles.privateTitle}>ชมรมส่วนตัว</Text><Text style={styles.privateText}>ผู้เข้าร่วมส่งคำขอและรอการอนุมัติ</Text></View><MaterialIcons name={privateClub ? "toggle-on" : "toggle-off"} size={37} color={privateClub ? HOBEE.colors.goldDark : HOBEE.colors.muted} /></Pressable><View style={styles.notice}><MaterialIcons name="info-outline" size={17} color={HOBEE.colors.goldDark} /><Text style={styles.noticeText}>การสร้างชมรมเป็น preview เท่านั้น จนกว่าจะมี membership, moderator และ moderation backend</Text></View><Pressable style={styles.primary}><Text style={styles.primaryText}>บันทึกเป็นตัวอย่าง</Text><MaterialIcons name="arrow-forward" size={18} color={HOBEE.colors.ink} /></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: HOBEE.space.page }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, title: { color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, content: { gap: 13, padding: HOBEE.space.page, paddingBottom: 42 }, cover: { alignItems: "center", borderRadius: HOBEE.radius.card, borderWidth: 1, borderStyle: "dashed", borderColor: HOBEE.colors.gold, backgroundColor: HOBEE.atmosphere.warmCream, padding: 24 }, coverTitle: { color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900", marginTop: 8 }, coverText: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600", marginTop: 4 }, input: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "700", borderRadius: HOBEE.radius.medium, backgroundColor: HOBEE.colors.surface, padding: 14, ...HOBEE.elevation.surface }, description: { minHeight: 130 }, label: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900", marginTop: 3 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 10, paddingVertical: 8 }, chipActive: { backgroundColor: HOBEE.colors.gold }, chipText: { color: HOBEE.colors.ink, fontSize: 11, fontWeight: "800" }, privateRow: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.atmosphere.skyMist, padding: 14 }, privateCopy: { flex: 1 }, privateTitle: { color: HOBEE.colors.ink, fontSize: 14, fontWeight: "900" }, privateText: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600", marginTop: 4 }, notice: { flexDirection: "row", gap: 7, borderRadius: HOBEE.radius.medium, backgroundColor: HOBEE.atmosphere.peachMist, padding: 11 }, noticeText: { flex: 1, color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700", lineHeight: 16 }, primary: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.gold, paddingVertical: 13 }, primaryText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" } });
