import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, type Href } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { CommunityClubCard } from "@/components/hobee/community-ui";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { COMMUNITY_CLUBS } from "@/lib/community-hub";

export default function CommunityClubsScreen() { return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><View style={styles.copy}><Text style={styles.eyebrow}>HOBEE COMMUNITY</Text><Text style={styles.title}>ชมรมและกลุ่ม</Text></View><Pressable onPress={() => router.push("/community/clubs/create" as Href)} style={styles.create}><MaterialIcons name="add" size={20} color={HOBEE.colors.ink} /></Pressable></View><FlatList data={COMMUNITY_CLUBS} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} renderItem={({ item }) => <CommunityClubCard club={item} onPress={() => router.push(`/community/clubs/${item.id}` as Href)} />} ListHeaderComponent={<View style={styles.hero}><MaterialIcons name="groups" size={30} color={HOBEE.colors.botanical} /><Text style={styles.heroTitle}>หาคนที่สนใจสิ่งเดียวกัน</Text><Text style={styles.heroText}>ค้นพบชมรมสาธารณะ ชมรมส่วนตัว และกิจกรรมที่ดำเนินการโดยสมาชิกในพื้นที่</Text></View>} /></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 11, padding: HOBEE.space.page }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, copy: { flex: 1 }, eyebrow: { color: HOBEE.colors.goldDark, fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, title: { color: HOBEE.colors.ink, fontSize: 20, fontWeight: "900", marginTop: 2 }, create: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.gold }, content: { paddingHorizontal: HOBEE.space.page, paddingBottom: 42 }, hero: { alignItems: "center", borderRadius: HOBEE.radius.hero, backgroundColor: HOBEE.atmosphere.botanicalMist, marginBottom: 14, padding: 20 }, heroTitle: { color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900", marginTop: 9 }, heroText: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 18, marginTop: 6, textAlign: "center" } });
