import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";

export default function ReservationSuccessScreen() { const { id, date, time, guests } = useLocalSearchParams<{ id: string; date?: string; time?: string; guests?: string }>(); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.content}><View style={styles.icon}><MaterialIcons name="event-available" size={42} color={HOBEE.colors.botanical} /></View><Text style={styles.title}>สร้าง Reservation Preview แล้ว</Text><Text style={styles.description}>วันที่ {date ?? "—"} เวลา {time ?? "—"} สำหรับ {guests ?? "—"} ท่าน</Text><View style={styles.card}><Text style={styles.cardLabel}>RESERVATION STATUS</Text><Text style={styles.cardTitle}>รอร้านยืนยัน</Text><Text style={styles.cardText}>นี่คือ presentation preview เท่านั้น จะไม่มีการจองโต๊ะจริงจนกว่า reservation service ของร้านเชื่อมต่อ</Text></View><Pressable onPress={() => router.replace("/travel/my-trips" as never)} style={({ pressed }) => [styles.primary, pressed && styles.pressed]}><Text style={styles.primaryText}>ดูการจองของฉัน</Text></Pressable><Pressable onPress={() => router.replace({ pathname: "/travel/restaurant/[id]" as never, params: { id } })} style={({ pressed }) => [styles.secondary, pressed && styles.pressed]}><Text style={styles.secondaryText}>กลับไปที่ร้าน</Text></Pressable></View></ScreenContainer>; }
const styles = StyleSheet.create({ content: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12, padding: 26 }, icon: { width: 82, height: 82, alignItems: "center", justifyContent: "center", borderRadius: 41, backgroundColor: HOBEE.atmosphere.botanicalMist }, title: { color: HOBEE.colors.ink, fontSize: 22, fontWeight: "900", textAlign: "center" }, description: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "700", textAlign: "center" }, card: { width: "100%", gap: 6, marginTop: 8, borderRadius: 20, backgroundColor: HOBEE.atmosphere.warmCream, padding: 16 }, cardLabel: { color: HOBEE.colors.goldDark, fontSize: 9, fontWeight: "900", letterSpacing: 1 }, cardTitle: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, cardText: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "600", lineHeight: 17 }, primary: { width: "100%", marginTop: 8, alignItems: "center", borderRadius: 15, backgroundColor: HOBEE.colors.gold, paddingVertical: 13 }, primaryText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, secondary: { width: "100%", alignItems: "center", borderRadius: 15, backgroundColor: "#F2F0EB", paddingVertical: 13 }, secondaryText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
