import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AppHeader, FixedAppShell, SearchBar, SectionHeader, useHeaderElevation } from "@/components/hobee/shared-ui";
import { TravelListingCard } from "@/components/hobee/travel-ui";
import { travelListings, travelProvinces } from "@/lib/travel-data";
import { ScreenContainer } from "@/components/screen-container";

const LOCAL_CUES = [
  { icon: "restaurant", title: "อาหารฮาลาล", text: "แนะนำจุดแวะกินตามข้อมูลรายการและชุมชน" },
  { icon: "palette", title: "กิจกรรมชุมชน", text: "Workshop และประสบการณ์ที่ผู้ประกอบการประกาศ" },
  { icon: "auto-stories", title: "เรื่องเล่า Creator", text: "เชื่อมต่อเรื่องราวท้องถิ่นจาก Discover" },
] as const;

export default function LocalLifeScreen() {
  const [province, setProvince] = useState<(typeof travelProvinces)[number]["id"]>("all");
  const { elevated, onScroll } = useHeaderElevation();
  const listings = useMemo(() => province === "all" ? travelListings : travelListings.filter((listing) => listing.provinceId === province), [province]);
  const openListing = (id: string) => router.push({ pathname: "/travel/[id]" as any, params: { id } });
  return <ScreenContainer containerClassName="bg-[#F8F7F5]" safeAreaClassName="pt-7" edges={["top", "left", "right"]}><FixedAppShell elevated={elevated} header={<AppHeader showLocation={false} brandSuffix="TRAVEL" />} search={<SearchBar onPress={() => router.push("/travel")} placeholder="ค้นหากิจกรรม ร้านอาหาร หรือ Creator" />}><ScrollView style={styles.scroll} onScroll={onScroll} scrollEventThrottle={16} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{travelProvinces.map((item) => <Pressable key={item.id} onPress={() => setProvince(item.id)} style={[styles.chip, province === item.id && styles.chipActive]}><Text style={[styles.chipText, province === item.id && styles.chipTextActive]}>{item.label}</Text></Pressable>)}</ScrollView><View style={styles.intro}><Text style={styles.eyebrow}>LOCAL LIFE HUB</Text><Text style={styles.title}>{province === "all" ? "วิถีถิ่นที่รอให้คุณค้นพบ" : `เรื่องดีของ${travelProvinces.find((item) => item.id === province)?.label}`}</Text><Text style={styles.copy}>เลือกสนับสนุนผู้ประกอบการในพื้นที่ ผ่านที่พัก ทริป อาหาร และกิจกรรมที่มีข้อมูลแหล่งที่มา</Text></View><SectionHeader title="แนะนำจากพื้นที่" /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.rail}>{listings.map((listing) => <TravelListingCard key={listing.id} listing={listing} onPress={() => openListing(listing.id)} />)}</ScrollView><SectionHeader title="ไปให้ลึกกว่าเดิม" /><View style={styles.cueList}>{LOCAL_CUES.map((cue) => <View key={cue.title} style={styles.cue}><View style={styles.cueIcon}><MaterialIcons name={cue.icon} size={25} color={HOBEE.colors.travelTeal} /></View><View style={styles.cueCopy}><Text style={styles.cueTitle}>{cue.title}</Text><Text style={styles.cueText}>{cue.text}</Text></View></View>)}</View><Pressable onPress={() => router.push("/(tabs)/discover")} style={styles.creator}><Text style={styles.creatorEyebrow}>STORY & COMMUNITY</Text><Text style={styles.creatorTitle}>ฟังเรื่องเล่าจาก Creator ท้องถิ่น</Text><Text style={styles.creatorText}>เปิด Discover เพื่อเลือกอ่านเรื่องราวจากชุมชนและวางแผนการเดินทางของคุณ</Text><View style={styles.creatorAction}><Text style={styles.creatorActionText}>ไปที่ Discover</Text><MaterialIcons name="arrow-forward" size={20} color={HOBEE.colors.ink} /></View></Pressable></ScrollView></FixedAppShell></ScreenContainer>;
}

const styles = StyleSheet.create({
  scroll: { flex: 1 }, content: { paddingBottom: 160, backgroundColor: HOBEE.colors.canvas }, chips: { gap: 8, paddingHorizontal: 20, paddingTop: 16, paddingBottom: 16 }, chip: { borderWidth: 1, borderColor: HOBEE.colors.border, borderRadius: 17, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 13, paddingVertical: 9 }, chipActive: { borderColor: HOBEE.colors.travelTeal, backgroundColor: HOBEE.colors.travelTeal }, chipText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "800" }, chipTextActive: { color: "#FFFFFF" }, intro: { marginHorizontal: 20, borderRadius: 25, backgroundColor: "#DDF4EE", padding: 21 }, eyebrow: { color: HOBEE.colors.travelTeal, fontSize: 11, fontWeight: "900", letterSpacing: 1 }, title: { marginTop: 9, color: HOBEE.colors.ink, fontSize: 25, fontWeight: "900", lineHeight: 31 }, copy: { marginTop: 8, color: "#4B625C", fontSize: 14, fontWeight: "600", lineHeight: 20 }, rail: { gap: 13, paddingHorizontal: 20, paddingBottom: 8 }, cueList: { gap: 11, marginHorizontal: 20 }, cue: { flexDirection: "row", alignItems: "center", gap: 13, borderRadius: 21, borderWidth: 1, borderColor: HOBEE.colors.border, backgroundColor: HOBEE.colors.surface, padding: 14, ...HOBEE.shadow }, cueIcon: { width: 47, height: 47, alignItems: "center", justifyContent: "center", borderRadius: 16, backgroundColor: "#E8F7F1" }, cueCopy: { flex: 1 }, cueTitle: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, cueText: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 17 }, creator: { margin: 20, borderRadius: 25, backgroundColor: HOBEE.colors.gold, padding: 22 }, creatorEyebrow: { color: "#5C4820", fontSize: 11, fontWeight: "900", letterSpacing: 1 }, creatorTitle: { marginTop: 10, color: HOBEE.colors.ink, fontSize: 23, fontWeight: "900", lineHeight: 29 }, creatorText: { marginTop: 8, color: "#5C523D", fontSize: 13, fontWeight: "600", lineHeight: 19 }, creatorAction: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 7, marginTop: 15, borderRadius: 17, backgroundColor: "#FFFFFF", paddingHorizontal: 14, paddingVertical: 10 }, creatorActionText: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" },
});
