import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AppStatusState } from "@/components/hobee/error-screens";
import { ScreenContainer } from "@/components/screen-container";
import { travelBookingStateLabel, TRAVEL_BOOKING_PRESENTATIONS, type TravelBookingState } from "@/lib/travel-booking-presentation";
import { goBackOr } from "@/lib/back-navigation";
import { useTravelCatalog } from "@/lib/travel-catalog";

const TABS: TravelBookingState[] = ["upcoming", "pending", "completed", "cancelled"];
export default function MyTripsScreen() {
  const { listings } = useTravelCatalog(); const [active, setActive] = useState<TravelBookingState>("upcoming");
  const items = useMemo(() => TRAVEL_BOOKING_PRESENTATIONS.filter((booking) => booking.state === active).flatMap((booking) => { const listing = listings.find((entry) => entry.id === booking.listingId); return listing ? [{ booking, listing }] : []; }), [active, listings]);
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => goBackOr(router, "/travel")} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.title}>ทริปของฉัน</Text><Pressable onPress={() => router.push("/travel" as never)} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="explore" size={20} color={HOBEE.colors.travelTeal} /></Pressable></View><View style={styles.tabs}>{TABS.map((tab) => <Pressable key={tab} onPress={() => setActive(tab)} style={[styles.tab, active === tab && styles.tabActive]}><Text style={[styles.tabText, active === tab && styles.tabTextActive]}>{travelBookingStateLabel(tab)}</Text></Pressable>)}</View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>{items.length ? items.map(({ booking, listing }) => <Pressable key={booking.id} onPress={() => router.push({ pathname: "/travel/bookings/[id]", params: { id: booking.id } } as never)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><Image source={{ uri: listing.images[0] }} style={styles.image} /><View style={styles.copy}><View style={styles.cardTop}><Text style={styles.state}>{travelBookingStateLabel(booking.state)}</Text><MaterialIcons name="chevron-right" size={20} color={HOBEE.colors.muted} /></View><Text numberOfLines={2} style={styles.cardTitle}>{listing.title}</Text><Text style={styles.cardMeta}>{booking.dateLabel}</Text><Text style={styles.cardMeta}>{booking.paymentLabel}</Text><Text style={styles.operator}>{booking.operatorLabel}</Text></View></Pressable>) : <AppStatusState icon="luggage" tone="gold" title={`ยังไม่มีทริปในแท็บ “${travelBookingStateLabel(active)}”`} description="รายการ booking จริงจะแสดงเมื่อเชื่อม booking backend และ order relationship พร้อม" actionLabel="ค้นหาทริป" onAction={() => router.replace("/travel" as never)} />}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", height: 62, paddingHorizontal: 18 }, back: { alignItems: "center", justifyContent: "center", width: 38, height: 38, borderRadius: 19, backgroundColor: HOBEE.colors.surface, ...HOBEE.elevation.surface }, title: { color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, tabs: { flexDirection: "row", gap: 5, paddingHorizontal: 16, paddingBottom: 9 }, tab: { flex: 1, alignItems: "center", borderRadius: 13, backgroundColor: "#ECE8E2", paddingVertical: 9 }, tabActive: { backgroundColor: HOBEE.colors.travelTeal }, tabText: { color: HOBEE.colors.muted, fontSize: 10, fontWeight: "800" }, tabTextActive: { color: HOBEE.colors.surface }, content: { gap: 11, padding: 18, paddingBottom: 42 }, card: { flexDirection: "row", gap: 11, overflow: "hidden", borderRadius: 19, backgroundColor: HOBEE.colors.surface, padding: 9, ...HOBEE.elevation.surface }, image: { width: 92, height: 118, borderRadius: 13, backgroundColor: HOBEE.atmosphere.warmCream }, copy: { flex: 1 }, cardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, state: { color: HOBEE.colors.travelTeal, fontSize: 10, fontWeight: "900" }, cardTitle: { marginTop: 7, color: HOBEE.colors.ink, fontSize: 14, lineHeight: 19, fontWeight: "900" }, cardMeta: { marginTop: 4, color: HOBEE.colors.muted, fontSize: 10, lineHeight: 14, fontWeight: "600" }, operator: { marginTop: 7, color: HOBEE.colors.goldDark, fontSize: 10, fontWeight: "900" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
