import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AppStatusState } from "@/components/hobee/error-screens";
import { ScreenContainer } from "@/components/screen-container";
import { TRAVEL_SAFETY_CONTRACTS } from "@/lib/travel-ecosystem";

export default function TravelSafetyScreen() { return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.round}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.title}>Travel Safety</Text><View style={styles.round}><MaterialIcons name="health-and-safety" size={19} color={HOBEE.colors.error} /></View></View><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><MaterialIcons name="emergency" size={30} color={HOBEE.colors.error} /><Text style={styles.heroTitle}>ความปลอดภัยระหว่างเดินทาง</Text><Text style={styles.heroText}>เราจะไม่แสดงหมายเลขหรือช่องทางฉุกเฉินที่ยังไม่ได้รับการตรวจสอบจากแหล่งข้อมูลที่เชื่อถือได้</Text></View>{TRAVEL_SAFETY_CONTRACTS.map((item) => <View key={item.id} style={styles.card}><View style={styles.icon}><MaterialIcons name={item.id === "hospital" ? "local-hospital" : item.id === "operator" ? "storefront" : "support-agent"} size={21} color={HOBEE.colors.travelTeal} /></View><View style={styles.copy}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardText}>{item.description}</Text><Text style={styles.status}>รอ verified source</Text></View></View>)}<View style={styles.state}><AppStatusState icon="location-off" tone="gold" title="Location & offline boundary" description="หากผู้ใช้ปิด location หรือออฟไลน์ ให้แสดงเมือง/จังหวัดที่เลือกและไม่มีการคาดเดาตำแหน่งปัจจุบัน" actionLabel="เลือกจังหวัด" onAction={() => router.push("/travel/my-province" as never)} /></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", height: 62, paddingHorizontal: 18 }, round: { alignItems: "center", justifyContent: "center", width: 39, height: 39, borderRadius: 20, backgroundColor: HOBEE.colors.surface, ...HOBEE.elevation.surface }, title: { color: HOBEE.colors.ink, fontSize: 17, fontWeight: "900" }, content: { gap: 11, padding: 20, paddingBottom: 42 }, hero: { alignItems: "center", gap: 8, borderRadius: 22, backgroundColor: HOBEE.atmosphere.peachMist, padding: 20 }, heroTitle: { color: HOBEE.colors.ink, fontSize: 19, fontWeight: "900" }, heroText: { color: HOBEE.colors.muted, fontSize: 11, lineHeight: 16, textAlign: "center", fontWeight: "600" }, card: { flexDirection: "row", alignItems: "flex-start", gap: 10, borderRadius: 17, backgroundColor: HOBEE.colors.surface, padding: 12, ...HOBEE.elevation.surface }, icon: { alignItems: "center", justifyContent: "center", width: 42, height: 42, borderRadius: 14, backgroundColor: HOBEE.atmosphere.botanicalMist }, copy: { flex: 1 }, cardTitle: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, cardText: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 10, lineHeight: 14, fontWeight: "600" }, status: { marginTop: 5, color: HOBEE.colors.goldDark, fontSize: 9, fontWeight: "900" }, state: { marginTop: 6, borderRadius: 20, backgroundColor: HOBEE.atmosphere.warmCream } });
