import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AppStatusState } from "@/components/hobee/error-screens";
import { ScreenContainer } from "@/components/screen-container";
import { searchTravelEcosystem } from "@/lib/travel-ecosystem";
import { useTravelCatalog } from "@/lib/travel-catalog";
import { goBackOr } from "@/lib/back-navigation";

const SUGGESTIONS = ["สตูล", "ปัตตานี", "ที่พัก", "เวิร์กช็อป", "อาหาร"]; const RECENT = ["เกาะหลีเป๊ะ", "เบตง", "ทริปฮาลาล"];
export default function TravelSearchScreen() { const { listings } = useTravelCatalog(); const [query, setQuery] = useState(""); const results = useMemo(() => searchTravelEcosystem(query, listings), [query, listings]); return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => goBackOr(router, "/travel")} style={styles.round}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><View style={styles.search}><MaterialIcons name="search" size={20} color={HOBEE.colors.muted} /><TextInput autoFocus value={query} onChangeText={setQuery} placeholder="ค้นหาจังหวัด สถานที่ ทริป หรือที่พัก" placeholderTextColor={HOBEE.colors.muted} style={styles.input} /><Pressable onPress={() => setQuery("")}><MaterialIcons name="close" size={19} color={HOBEE.colors.muted} /></Pressable></View></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">{!query ? <><Text style={styles.title}>ลองค้นหา</Text><View style={styles.suggestions}>{SUGGESTIONS.map((value) => <Pressable key={value} onPress={() => setQuery(value)} style={styles.chip}><Text style={styles.chipText}>{value}</Text></Pressable>)}</View><Text style={styles.recentTitle}>การค้นหาล่าสุด</Text>{RECENT.map((value) => <Pressable key={value} onPress={() => setQuery(value)} style={styles.recent}><MaterialIcons name="history" size={18} color={HOBEE.colors.muted} /><Text style={styles.recentText}>{value}</Text><MaterialIcons name="north-west" size={16} color={HOBEE.colors.muted} /></Pressable>)}</> : results.length ? <><Text style={styles.resultTitle}>ผลการค้นหา</Text>{results.map((result) => <Pressable key={`${result.kind}-${result.id}`} onPress={() => router.push(result.route as never)} style={({ pressed }) => [styles.result, pressed && styles.pressed]}>{result.image ? <Image source={{ uri: result.image }} style={styles.resultImage} /> : <View style={styles.resultIcon}><MaterialIcons name="explore" size={20} color={HOBEE.colors.travelTeal} /></View>}<View style={styles.resultCopy}><Text style={styles.resultKind}>{result.kind}</Text><Text style={styles.resultName}>{result.title}</Text><Text style={styles.resultSub}>{result.subtitle}</Text></View><MaterialIcons name="chevron-right" size={21} color={HOBEE.colors.muted} /></Pressable>)}</> : <AppStatusState icon="search-off" tone="gold" title="ไม่พบผลลัพธ์" description="ลองค้นหาด้วยชื่อจังหวัด สถานที่ ทริป ที่พัก หรือเวิร์กช็อป" actionLabel="ล้างคำค้น" onAction={() => setQuery("")} />}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 9, height: 62, paddingHorizontal: 18 }, round: { alignItems: "center", justifyContent: "center", width: 38, height: 38, borderRadius: 19, backgroundColor: HOBEE.colors.surface }, search: { flex: 1, flexDirection: "row", alignItems: "center", gap: 7, borderRadius: 17, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 11, ...HOBEE.elevation.surface }, input: { flex: 1, height: 42, color: HOBEE.colors.ink, fontSize: 12, fontWeight: "700" }, content: { gap: 10, padding: 20, paddingBottom: 42 }, title: { color: HOBEE.colors.ink, fontSize: 20, fontWeight: "900" }, suggestions: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { borderRadius: 13, backgroundColor: HOBEE.atmosphere.botanicalMist, paddingHorizontal: 11, paddingVertical: 8 }, chipText: { color: HOBEE.colors.travelTeal, fontSize: 10, fontWeight: "900" }, recentTitle: { marginTop: 15, color: HOBEE.colors.ink, fontSize: 15, fontWeight: "900" }, recent: { flexDirection: "row", alignItems: "center", gap: 9, borderRadius: 14, backgroundColor: HOBEE.colors.surface, padding: 12, ...HOBEE.elevation.surface }, recentText: { flex: 1, color: HOBEE.colors.ink, fontSize: 12, fontWeight: "800" }, resultTitle: { marginBottom: 3, color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, result: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 17, backgroundColor: HOBEE.colors.surface, padding: 9, ...HOBEE.elevation.surface }, resultImage: { width: 58, height: 58, borderRadius: 12, backgroundColor: HOBEE.atmosphere.warmCream }, resultIcon: { alignItems: "center", justifyContent: "center", width: 58, height: 58, borderRadius: 12, backgroundColor: HOBEE.atmosphere.botanicalMist }, resultCopy: { flex: 1 }, resultKind: { color: HOBEE.colors.travelTeal, fontSize: 8, fontWeight: "900", textTransform: "uppercase" }, resultName: { marginTop: 2, color: HOBEE.colors.ink, fontSize: 12, fontWeight: "900" }, resultSub: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 9, fontWeight: "600" }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
