import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { HOBEE } from "@/components/hobee/design-tokens";
import { AppStatusState } from "@/components/hobee/error-screens";
import { ScreenContainer } from "@/components/screen-container";
import { FOREIGN_VISITOR_SERVICES } from "@/lib/travel-ecosystem";
import { goBackOr } from "@/lib/back-navigation";

const LANGUAGES = ["English", "Bahasa Melayu", "العربية", "中文"];
export default function ForeignVisitorScreen() { return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#F8F7F5]"><View style={styles.header}><Pressable onPress={() => goBackOr(router, "/travel")} style={styles.round}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><Text style={styles.headerTitle}>International Visitor</Text><Pressable onPress={() => router.push("/travel/safety" as never)} style={styles.round}><MaterialIcons name="health-and-safety" size={20} color={HOBEE.colors.travelTeal} /></Pressable></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.hero}><MaterialIcons name="public" size={32} color={HOBEE.colors.gold} /><Text style={styles.eyebrow}>WELCOME TO THAILAND</Text><Text style={styles.heroTitle}>Travel with a local perspective</Text><Text style={styles.heroCopy}>Essential services will become bookable when verified providers and secure backend wiring are ready.</Text></View><Text style={styles.sectionTitle}>Choose language</Text><View style={styles.languageRow}>{LANGUAGES.map((language) => <View key={language} style={styles.language}><MaterialIcons name="language" size={15} color={HOBEE.colors.travelTeal} /><Text style={styles.languageText}>{language}</Text></View>)}</View><Text style={styles.sectionTitle}>Visitor services</Text><View style={styles.serviceList}>{FOREIGN_VISITOR_SERVICES.map((service) => <Pressable key={service.id} onPress={() => service.id === "stay" || service.id === "tours" ? router.push("/travel" as never) : undefined} style={({ pressed }) => [styles.service, pressed && (service.id === "stay" || service.id === "tours") && styles.pressed]}><View style={styles.serviceIcon}><MaterialIcons name={service.icon as keyof typeof MaterialIcons.glyphMap} size={22} color={HOBEE.colors.travelTeal} /></View><View style={styles.serviceCopy}><Text style={styles.serviceTitle}>{service.title}</Text><Text style={styles.serviceText}>{service.description}</Text></View><View style={[styles.status, service.status === "presentation" && styles.statusReady]}><Text style={[styles.statusText, service.status === "presentation" && styles.statusTextReady]}>{service.status === "presentation" ? "Explore" : "Coming later"}</Text></View></Pressable>)}</View><View style={styles.safety}><AppStatusState icon="emergency" tone="rose" title="Help & Emergency" description="ข้อมูลติดต่อฉุกเฉินจะปรากฏหลังมี source ที่ผ่าน verification เพื่อไม่แสดงหมายเลขที่ยังไม่ยืนยัน" actionLabel="Travel safety" onAction={() => router.push("/travel/safety" as never)} /></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", height: 62, paddingHorizontal: 18 }, round: { alignItems: "center", justifyContent: "center", width: 39, height: 39, borderRadius: 20, backgroundColor: HOBEE.colors.surface, ...HOBEE.elevation.surface }, headerTitle: { color: HOBEE.colors.ink, fontSize: 16, fontWeight: "900" }, content: { gap: 18, padding: 20, paddingBottom: 42 }, hero: { alignItems: "flex-start", borderRadius: 24, backgroundColor: HOBEE.colors.darkCard, padding: 20 }, eyebrow: { marginTop: 14, color: HOBEE.colors.gold, fontSize: 9, fontWeight: "900", letterSpacing: 1 }, heroTitle: { marginTop: 5, color: HOBEE.colors.surface, fontSize: 25, lineHeight: 31, fontWeight: "900" }, heroCopy: { marginTop: 7, color: "#E4E0D8", fontSize: 12, lineHeight: 18, fontWeight: "600" }, sectionTitle: { color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, languageRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, language: { flexDirection: "row", alignItems: "center", gap: 5, borderRadius: 13, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 10, paddingVertical: 9, ...HOBEE.elevation.surface }, languageText: { color: HOBEE.colors.ink, fontSize: 10, fontWeight: "800" }, serviceList: { gap: 9 }, service: { flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 18, backgroundColor: HOBEE.colors.surface, padding: 12, ...HOBEE.elevation.surface }, serviceIcon: { alignItems: "center", justifyContent: "center", width: 43, height: 43, borderRadius: 14, backgroundColor: HOBEE.atmosphere.botanicalMist }, serviceCopy: { flex: 1 }, serviceTitle: { color: HOBEE.colors.ink, fontSize: 13, fontWeight: "900" }, serviceText: { marginTop: 3, color: HOBEE.colors.muted, fontSize: 10, lineHeight: 14, fontWeight: "600" }, status: { borderRadius: 9, backgroundColor: HOBEE.atmosphere.warmCream, paddingHorizontal: 7, paddingVertical: 5 }, statusReady: { backgroundColor: HOBEE.atmosphere.botanicalMist }, statusText: { color: HOBEE.colors.goldDark, fontSize: 8, fontWeight: "900" }, statusTextReady: { color: HOBEE.colors.travelTeal }, safety: { marginTop: 2, borderRadius: 22, backgroundColor: HOBEE.atmosphere.peachMist }, pressed: { opacity: 0.78, transform: [{ scale: HOBEE.motion.pressScale }] } });
