import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AdminCard, AdminCardTitle, AdminPortalShell, type AdminWorkspace } from "@/components/admin/admin-portal-ui";
import { AppStatusState } from "@/components/hobee/error-screens";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { useAdmin } from "@/hooks/use-admin";

type AdminPresentation = { title: string; subtitle: string; icon: keyof typeof MaterialIcons.glyphMap; tone: "gold" | "green" | "blue" | "rose"; sections: Array<{ title: string; description: string; icon: keyof typeof MaterialIcons.glyphMap; action?: string }> };
const WORKSPACES: Record<string, AdminPresentation> = {
  organizations: { title: "องค์กรและพนักงาน", subtitle: "Organization, membership และ staff governance", icon: "domain", tone: "green", sections: [{ title: "องค์กร", description: "ดูสถานะองค์กร การเป็นเจ้าของ และข้อกำหนดการเข้าถึงเมื่อมี organization source", icon: "domain", action: "เปิดองค์กร" }, { title: "พนักงานและสมาชิก", description: "จัดการสมาชิก บทบาท การเชิญ และขอบเขตสิทธิ์ด้วย policy เดิม", icon: "groups", action: "จัดการสมาชิก" }, { title: "Role approvals", description: "พิจารณาคำขอบทบาทด้วย audit trail ที่มีอยู่แล้ว", icon: "verified-user", action: "เปิดการอนุมัติ" }] },
  customers: { title: "ลูกค้าและผู้ใช้", subtitle: "Customer care, account lifecycle และ authorization", icon: "group", tone: "blue", sections: [{ title: "Customer directory", description: "รายชื่อลูกค้าและประวัติที่ผู้ดูแลมีสิทธิ์เข้าถึงจะเชื่อมที่นี่", icon: "people" }, { title: "Account access", description: "ตรวจสถานะบัญชีและการอนุญาตโดยไม่เปิดเผยข้อมูลรับรอง", icon: "manage-accounts" }, { title: "Support and cases", description: "ติดตามคำขอหลังการขายและการแจ้งเตือนที่เกี่ยวข้อง", icon: "support-agent", action: "เปิดเคสหลังการขาย" }] },
  payments: { title: "การชำระเงิน", subtitle: "Payment monitoring, provider events และ reconciliation", icon: "account-balance-wallet", tone: "gold", sections: [{ title: "Payment monitor", description: "สถานะ intent และ webhook จะแสดงจาก server-side source เมื่อ Vercel พร้อม", icon: "payments" }, { title: "Refund operations", description: "การคืนเงินต้องผ่าน protected backend operation และ audit trail", icon: "replay" }, { title: "Reconciliation", description: "ตรวจการจับคู่ order, payment และ payout โดยไม่คำนวณยอดจำลอง", icon: "fact-check" }] },
  shipping: { title: "การจัดส่ง", subtitle: "Fulfilment, tracking และ carrier operations", icon: "local-shipping", tone: "green", sections: [{ title: "Fulfilment queue", description: "คิวเตรียมจัดส่งและข้อมูล tracking ที่อนุญาตจะเชื่อมที่นี่", icon: "inventory" }, { title: "Tracking monitor", description: "สถานะ carrier และเหตุการณ์การจัดส่งจาก integration ที่ได้รับอนุมัติ", icon: "route" }, { title: "Delivery exceptions", description: "รายการผิดปกติและการติดต่อผู้รับตาม policy การจัดส่ง", icon: "warning-amber" }] },
  activity: { title: "Audit Log", subtitle: "บันทึกเหตุการณ์ผู้ดูแลและการเปลี่ยนแปลงสำคัญ", icon: "assignment", tone: "blue", sections: [{ title: "Admin activity", description: "กิจกรรมของผู้ดูแลจะแสดงตามสิทธิ์และ retention policy", icon: "history" }, { title: "Security events", description: "เหตุการณ์ด้านสิทธิ์ การอนุมัติ และการดำเนินการที่มีผลต่อข้อมูล", icon: "security" }, { title: "Export and review", description: "การส่งออกข้อมูลต้องเปิดใช้เฉพาะเมื่อ owner กำหนด source และ policy", icon: "file-download" }] },
  system: { title: "ระบบและการเชื่อมต่อ", subtitle: "Health, integration readiness และ operational handoff", icon: "hub", tone: "rose", sections: [{ title: "Supabase", description: "ตรวจสถานะ data source, RLS และ migration ตามสิทธิ์ที่มี", icon: "storage" }, { title: "Vercel backend", description: "รอการเชื่อมทีม owner ก่อนตรวจ deployment และ server-only secrets จริง", icon: "cloud-queue" }, { title: "External providers", description: "Payment, carrier และ push provider จะแสดงเฉพาะสถานะที่ยืนยันได้", icon: "settings-input-component" }] },
  settings: { title: "ตั้งค่าแพลตฟอร์ม", subtitle: "Governance, policies และ configuration boundaries", icon: "settings", tone: "gold", sections: [{ title: "Commerce policy", description: "นโยบายสินค้า คำสั่งซื้อ และหลังการขาย ใช้ contracts เดิมของระบบ", icon: "policy" }, { title: "Notification policy", description: "กำหนด channel และ preferences เมื่อ notification source พร้อม", icon: "notifications-active" }, { title: "Security settings", description: "การตั้งค่าระบบสำคัญดำเนินการผ่าน owner-controlled dashboard เท่านั้น", icon: "admin-panel-settings" }] },
  reports: { title: "รายงานและวิเคราะห์", subtitle: "Operational reporting โดยไม่แสดงข้อมูลจำลอง", icon: "query-stats", tone: "blue", sections: [{ title: "Commerce reports", description: "รายงานคำสั่งซื้อ ยอดชำระ และสินค้าเมื่อ data source พร้อม", icon: "insights" }, { title: "Travel reports", description: "รายงานทริป ห้องพัก และการจองตามข้อมูลที่ได้รับสิทธิ์", icon: "travel-explore" }, { title: "Workforce reports", description: "รายงานองค์กรและบทบาทตาม policy ของเจ้าของข้อมูล", icon: "badge" }] },
  notifications: { title: "การแจ้งเตือนแพลตฟอร์ม", subtitle: "Operational alerts และ delivery controls", icon: "notifications-none", tone: "green", sections: [{ title: "Notification outbox", description: "ติดตาม event ที่ส่งแล้ว รอส่ง หรือ retry จาก server-side outbox", icon: "outbox" }, { title: "Channel health", description: "สถานะ push และ channel ที่เปิดใช้จริงเท่านั้น", icon: "wifi-tethering" }, { title: "Preferences", description: "ตรวจนโยบายการสื่อสารโดยเคารพการตั้งค่าผู้ใช้", icon: "tune" }] },
};

function navigate(workspace: AdminWorkspace) { if (workspace === "overview") router.replace("/admin"); else if (workspace === "products") router.push("/admin/products" as never); else if (workspace === "travel") router.push("/admin/travel" as never); else if (workspace === "orders") router.push("/admin/orders" as never); else if (workspace === "inventory") router.push({ pathname: "/admin/products" as never, params: { filter: "low-stock" } } as never); else router.push(`/admin/workspace/${workspace}` as never); }

export default function AdminWorkspacePresentationScreen() {
  const { workspace } = useLocalSearchParams<{ workspace?: string }>(); const view = WORKSPACES[workspace ?? ""];
  const { allowed, loading, user, refresh } = useAdmin();
  if (loading) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.center}><Text style={styles.loading}>กำลังตรวจสิทธิ์ผู้ดูแล</Text></View></ScreenContainer>;
  if (!allowed) return <ScreenContainer edges={["top", "bottom", "left", "right"]}><View style={styles.center}><AppStatusState icon={user ? "admin-panel-settings" : "login"} tone="rose" title={user ? "สำหรับผู้ดูแลระบบ" : "กรุณาเข้าสู่ระบบ"} description={user ? "บัญชีนี้ยังไม่มีสิทธิ์ผู้ดูแลสำหรับพื้นที่นี้" : "เข้าสู่ระบบด้วยบัญชีผู้ดูแลก่อนเปิด Admin Portal"} actionLabel={!user ? "เข้าสู่ระบบ" : undefined} onAction={!user ? () => router.push("/auth?redirectTo=/admin") : undefined} /></View></ScreenContainer>;
  if (!view) return <ScreenContainer><View style={styles.center}><AppStatusState title="ไม่พบพื้นที่ผู้ดูแล" description="เลือกโมดูลอีกครั้งจาก Admin Portal" actionLabel="กลับ Admin" onAction={() => router.replace("/admin")} /></View></ScreenContainer>;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F7F8F6]"><AdminPortalShell active={workspace as AdminWorkspace} title={view.title} subtitle={view.subtitle} onNavigate={navigate} onRefresh={refresh}><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><View style={[styles.heroIcon, { backgroundColor: toneBackground(view.tone) }]}><MaterialIcons name={view.icon} size={26} color={toneColor(view.tone)} /></View><View style={styles.heroCopy}><Text style={styles.title}>{view.title}</Text><Text style={styles.subtitle}>{view.subtitle}</Text></View></View><View style={styles.grid}>{view.sections.map((section) => <AdminCard key={section.title} style={styles.card}><AdminCardTitle title={section.title} action={section.action} onAction={section.action === "เปิดเคสหลังการขาย" ? () => router.push("/admin/after-sales" as never) : section.action === "เปิดการอนุมัติ" ? () => router.push("/admin/role-approvals" as never) : undefined} /><View style={styles.sectionBody}><View style={[styles.sectionIcon, { backgroundColor: toneBackground(view.tone) }]}><MaterialIcons name={section.icon} size={21} color={toneColor(view.tone)} /></View><Text style={styles.sectionDescription}>{section.description}</Text></View><View style={styles.boundary}><MaterialIcons name="verified-user" size={15} color={HOBEE.colors.muted} /><Text style={styles.boundaryText}>Presentation mode — จะแสดงข้อมูลเฉพาะเมื่อ data source และสิทธิ์พร้อม</Text></View></AdminCard>)}</View></ScrollView></AdminPortalShell></ScreenContainer>;
}
function toneColor(tone: AdminPresentation["tone"]) { return tone === "green" ? HOBEE.colors.botanical : tone === "blue" ? HOBEE.colors.info : tone === "rose" ? HOBEE.colors.error : HOBEE.colors.goldDark; }
function toneBackground(tone: AdminPresentation["tone"]) { return tone === "green" ? HOBEE.atmosphere.botanicalMist : tone === "blue" ? HOBEE.atmosphere.skyMist : tone === "rose" ? HOBEE.atmosphere.peachMist : HOBEE.atmosphere.warmCream; }
const styles = StyleSheet.create({ center: { flex: 1, alignItems: "center", justifyContent: "center" }, loading: { color: HOBEE.colors.muted, fontSize: 13, fontWeight: "800" }, content: { gap: 14, paddingBottom: 12 }, hero: { flexDirection: "row", alignItems: "center", gap: 14, borderRadius: 16, backgroundColor: "#FFFFFF", padding: 18, ...HOBEE.elevation.surface }, heroIcon: { width: 52, height: 52, alignItems: "center", justifyContent: "center", borderRadius: 16 }, heroCopy: { flex: 1, gap: 4 }, title: { color: HOBEE.colors.ink, fontSize: 18, fontWeight: "900" }, subtitle: { color: HOBEE.colors.muted, fontSize: 11, fontWeight: "700" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 14 }, card: { flex: 1, minWidth: 260 }, sectionBody: { gap: 11, minHeight: 120 }, sectionIcon: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 13 }, sectionDescription: { color: HOBEE.colors.muted, fontSize: 12, fontWeight: "600", lineHeight: 18 }, boundary: { flexDirection: "row", alignItems: "flex-start", gap: 7, borderTopWidth: 1, borderTopColor: "#EEF0ED", paddingTop: 11 }, boundaryText: { flex: 1, color: HOBEE.colors.muted, fontSize: 10, fontWeight: "700", lineHeight: 14 } });
