import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, type Href } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { CommunityRecommendationCard } from "@/components/hobee/community-ui";
import { HOBEE } from "@/components/hobee/design-tokens";
import { ScreenContainer } from "@/components/screen-container";
import { COMMUNITY_RECOMMENDATIONS, COMMUNITY_STORIES } from "@/lib/community-hub";

export default function CommunityStoriesScreen() { const stories = COMMUNITY_RECOMMENDATIONS.filter((item) => item.entityType === "STORY"); return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={HOBEE.colors.ink} /></Pressable><View style={styles.headerCopy}><Text style={styles.eyebrow}>HOBEE COMMUNITY</Text><Text style={styles.title}>เรื่องราวจากชุมชน</Text></View><Pressable onPress={() => router.push("/community/create" as Href)} style={styles.create}><MaterialIcons name="edit" size={18} color={HOBEE.colors.ink} /></Pressable></View><FlatList data={stories} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} renderItem={({ item }) => <CommunityRecommendationCard item={item} onPress={() => router.push(item.route as Href)} />} ListHeaderComponent={<View style={styles.intro}><Text style={styles.introText}>รวมเรื่องเล่าจากผู้คน สถานที่ ของดี และประสบการณ์ที่เชื่อมกับโดเมน HOBEE เดิม</Text><View style={styles.tagRow}>{Array.from(new Set(COMMUNITY_STORIES.flatMap((story) => story.tags))).map((tag) => <Pressable key={tag} onPress={() => router.push(`/community/topics/${encodeURIComponent(tag.slice(1))}` as Href)} style={styles.tag}><Text style={styles.tagText}>{tag}</Text></Pressable>)}</View></View>} /></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 11, padding: HOBEE.space.page }, back: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.surface }, headerCopy: { flex: 1 }, eyebrow: { color: HOBEE.colors.goldDark, fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, title: { color: HOBEE.colors.ink, fontSize: 20, fontWeight: "900", marginTop: 2 }, create: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: HOBEE.colors.gold }, content: { paddingHorizontal: HOBEE.space.page, paddingBottom: 42 }, intro: { gap: 12, borderRadius: HOBEE.radius.card, backgroundColor: HOBEE.atmosphere.warmCream, marginBottom: 14, padding: 14 }, introText: { color: HOBEE.colors.ink, fontSize: 12, fontWeight: "600", lineHeight: 18 }, tagRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, tag: { borderRadius: HOBEE.radius.pill, backgroundColor: HOBEE.colors.surface, paddingHorizontal: 9, paddingVertical: 6 }, tagText: { color: HOBEE.colors.botanical, fontSize: 11, fontWeight: "900" } });
